/*
 *  TMC262_1420_Fields.h
 *  Author: LK
 *  Generated by MaskShiftConverter (unchecked)
 */

#ifndef TMC262_1420_FIELDS_H
#define TMC262_1420_FIELDS_H

#define TMC262_1420_DRVCTRL_SDOFF_MASK  (0xFFFFF)
#define TMC262_1420_DRVCTRL_MASK        (0xFFFFF & ~((0x0F<<4) | (0x7F <<10)))
#define TMC262_1420_CHOPCONF_MASK       (0xFFFFF)
#define TMC262_1420_SMARTEN_MASK        (0xFFFFF & ~((0x01<<4) | (0x01<<7) | (0x01<<12)))
#define TMC262_1420_SGCSCONF_MASK       (0xFFFFF & ~((0x07<<5) | (0x01<<15)))
#define TMC262_1420_DRVCONF_MASK        (0xFFFFF & ~((0x0F<<0) | (0x01<<11)))

#define TMC262_1420_MSTEP_MASK                   0x0FFC00 // DRVSTATUS / MSTEP // ustep position
#define TMC262_1420_MSTEP_SHIFT                  10 // min.: 0, max.: 1023, default: 0
#define TMC262_1420_STATUS_MASK                  0xFF // DRVSTATUS / STATUS // All Status flags (manually added)
#define TMC262_1420_STATUS_SHIFT                 0 // min.: 0, max.: 256, default 0
#define TMC262_1420_STST_MASK                    0x80 // DRVSTATUS / MSTEP //
#define TMC262_1420_STST_SHIFT                   7 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OLB_MASK                     0x40 // DRVSTATUS / MSTEP //
#define TMC262_1420_OLB_SHIFT                    6 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OLA_MASK                     0x20 // DRVSTATUS / MSTEP //
#define TMC262_1420_OLA_SHIFT                    5 // min.: 0, max.: 1, default: 0
#define TMC262_1420_S2GB_MASK                    0x10 // DRVSTATUS / MSTEP //
#define TMC262_1420_S2GB_SHIFT                   4 // min.: 0, max.: 1, default: 0
#define TMC262_1420_S2GA_MASK                    0x08 // DRVSTATUS / MSTEP //
#define TMC262_1420_S2GA_SHIFT                   3 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OTPW_MASK                    0x04 // DRVSTATUS / MSTEP //
#define TMC262_1420_OTPW_SHIFT                   2 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OT_MASK                      0x02 // DRVSTATUS / MSTEP //
#define TMC262_1420_OT_SHIFT                     1 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SG_MASK                      0x01 // DRVSTATUS / MSTEP //
#define TMC262_1420_SG_SHIFT                     0 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SG2_MASK                    0x0FFC00 // DRVSTATUS / SG // stallGuard2 value
#define TMC262_1420_SG2_SHIFT                   10 // min.: 0, max.: 1023, default: 0
#define TMC262_1420_STST_MASK                    0x80 // DRVSTATUS / SG //
#define TMC262_1420_STST_SHIFT                   7 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OLB_MASK                     0x40 // DRVSTATUS / SG //
#define TMC262_1420_OLB_SHIFT                    6 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OLA_MASK                     0x20 // DRVSTATUS / SG //
#define TMC262_1420_OLA_SHIFT                    5 // min.: 0, max.: 1, default: 0
#define TMC262_1420_S2GB_MASK                    0x10 // DRVSTATUS / SG //
#define TMC262_1420_S2GB_SHIFT                   4 // min.: 0, max.: 1, default: 0
#define TMC262_1420_S2GA_MASK                    0x08 // DRVSTATUS / SG //
#define TMC262_1420_S2GA_SHIFT                   3 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OTPW_MASK                    0x04 // DRVSTATUS / SG //
#define TMC262_1420_OTPW_SHIFT                   2 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OT_MASK                      0x02 // DRVSTATUS / SG //
#define TMC262_1420_OT_SHIFT                     1 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SG_MASK                      0x01 // DRVSTATUS / SG //
#define TMC262_1420_SG_SHIFT                     0 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SGU_MASK                     0x0F8000 // DRVSTATUS / SG_SE // Upper stallGuard2 value bit9:5
#define TMC262_1420_SGU_SHIFT                    15 // min.: 0, max.: 31, default: 0
#define TMC262_1420_SE_MASK                      0x7C00 // DRVSTATUS / SG_SE // Actual coolstep scaling value
#define TMC262_1420_SE_SHIFT                     10 // min.: 0, max.: 31, default: 0
#define TMC262_1420_STST_MASK                    0x80 // DRVSTATUS / SG_SE //
#define TMC262_1420_STST_SHIFT                   7 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OLB_MASK                     0x40 // DRVSTATUS / SG_SE //
#define TMC262_1420_OLB_SHIFT                    6 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OLA_MASK                     0x20 // DRVSTATUS / SG_SE //
#define TMC262_1420_OLA_SHIFT                    5 // min.: 0, max.: 1, default: 0
#define TMC262_1420_S2GB_MASK                    0x10 // DRVSTATUS / SG_SE //
#define TMC262_1420_S2GB_SHIFT                   4 // min.: 0, max.: 1, default: 0
#define TMC262_1420_S2GA_MASK                    0x08 // DRVSTATUS / SG_SE //
#define TMC262_1420_S2GA_SHIFT                   3 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OTPW_MASK                    0x04 // DRVSTATUS / SG_SE //
#define TMC262_1420_OTPW_SHIFT                   2 // min.: 0, max.: 1, default: 0
#define TMC262_1420_OT_MASK                      0x02 // DRVSTATUS / SG_SE //
#define TMC262_1420_OT_SHIFT                     1 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SG_MASK                      0x01 // DRVSTATUS / SG_SE //
#define TMC262_1420_SG_SHIFT                     0 // min.: 0, max.: 1, default: 0
#define TMC262_1420_REGISTER_ADDRESS_BITS_MASK   0xC00000 // DRVCTRL // Locked for Register Browser
#define TMC262_1420_REGISTER_ADDRESS_BITS_SHIFT  18 // min.: 0, max.: 0, default: 0
#define TMC262_1420_INTPOL_MASK                  0x0200 // DRVCTRL // Enabling step pulse interpolation by 16
#define TMC262_1420_INTPOL_SHIFT                 9 // min.: 0, max.: 1, default: 0
#define TMC262_1420_DEDGE_MASK                   0x0100 // DRVCTRL // Enabling double edge STEP pulse detection
#define TMC262_1420_DEDGE_SHIFT                  8 // min.: 0, max.: 1, default: 0
#define TMC262_1420_MRES_MASK                    0x0F // DRVCTRL // ustep resolution
#define TMC262_1420_MRES_SHIFT                   0 // min.: 0, max.: 8, default: 0
//#define TMC262_1420_REGISTER_ADDRESS_BITS_MASK 0x0E0000 // DRVCTRL // Locked for Register Browser
//#define TMC262_1420_REGISTER_ADDRESS_BITS_SHIFT 17 // min.: 0, max.: 0, default: 0
#define TMC262_1420_PHA_MASK                     0x020000 // DRVCTRL // Current flow from OA1 -> OA2 (if PHA=0), else from OA2 -> OA1
#define TMC262_1420_PHA_SHIFT                    17 // min.: 0, max.: 1, default: 0
#define TMC262_1420_CA_MASK                      0x01FE00 // DRVCTRL // Magnitude of current flow through coil A
#define TMC262_1420_CA_SHIFT                     9 // min.: 0, max.: 255, default: 0
#define TMC262_1420_PHB_MASK                     0x0100 // DRVCTRL // Current flow from OB1 -> OB2 (if PHB=0), else from OB2 -> OB1
#define TMC262_1420_PHB_SHIFT                    8 // min.: 0, max.: 1, default: 0
#define TMC262_1420_CB_MASK                      0xFF // DRVCTRL // Magnitude of current flow through coil B
#define TMC262_1420_CB_SHIFT                     0 // min.: 0, max.: 255, default: 0
//#define TMC262_1420_REGISTER_ADDRESS_BITS_MASK 0x0E0000 // CHOPCONF // Locked for Register Browser
//#define TMC262_1420_REGISTER_ADDRESS_BITS_SHIFT 17 // min.: 4, max.: 4, default: 0
#define TMC262_1420_TBL_MASK                     0x018000 // CHOPCONF // Blanking time [clock cycles]
#define TMC262_1420_TBL_SHIFT                    15 // min.: 0, max.: 3, default: 0
#define TMC262_1420_CHM_MASK                     0x4000 // CHOPCONF //
#define TMC262_1420_CHM_SHIFT                    14 // min.: 0, max.: 1, default: 0
#define TMC262_1420_RNDTF_MASK                   0x2000 // CHOPCONF //
#define TMC262_1420_RNDTF_SHIFT                  13 // min.: 0, max.: 1, default: 0
#define TMC262_1420_HDEC_MASK                    0x1800 // CHOPCONF // Hysteresis decrement interval [clock cycles]
#define TMC262_1420_HDEC_SHIFT                   11 // min.: 0, max.: 3, default: 0
#define TMC262_1420_HEND_MASK                    0x0780 // CHOPCONF // Hysteresis end (low) value; HEND+HSTART < 16
#define TMC262_1420_HEND_SHIFT                   7 // min.: 0, max.: 15, default: 0
#define TMC262_1420_HSTRT_MASK                   0x70 // CHOPCONF // Hysteresis start value
#define TMC262_1420_HSTRT_SHIFT                  4 // min.: 0, max.: 7, default: 0
#define TMC262_1420_HDEC1_MASK                   0x2000 // CHOPCONF // Fast decay mode settings
#define TMC262_1420_HDEC1_SHIFT                  12 // min.: 0, max.: 1, default: 0
#define TMC262_1420_HEND_MASK                    0x0780 // CHOPCONF // Sine wave offset
#define TMC262_1420_HEND_SHIFT                   7 // min.: 0, max.: 15, default: 0
#define TMC262_1420_HDEC0_MASK                   0x1000 // CHOPCONF // MSB of fast decay time setting
#define TMC262_1420_HDEC0_SHIFT                  11 // min.: 0, max.: 1, default: 0
// todo: CHECK 3: Redefinition of HSTRT doesn't really make sense here? (LH)
//#define TMC262_1420_HSTRT_MASK                   0x70 // CHOPCONF // LSBs of fast decay setting
//#define TMC262_1420_HSTRT_SHIFT                  0 // min.: 0, max.: 7, default: 0
#define TMC262_1420_TOFF_MASK                    0x0F // CHOPCONF // Slow decay duration. TOFF=0 => ShutOff
#define TMC262_1420_TOFF_SHIFT                   0 // min.: 0, max.: 15, default: 0
//#define TMC262_1420_REGISTER_ADDRESS_BITS_MASK 0x0E0000 // SMARTEN // Locked for Register Browser
//#define TMC262_1420_REGISTER_ADDRESS_BITS_SHIFT 17 // min.: 5, max.: 5, default: 0
#define TMC262_1420_SEIMIN_MASK                  0x8000 // SMARTEN // Minimum coolstep current
#define TMC262_1420_SEIMIN_SHIFT                 15 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SEDN_MASK                    0x6000 // SMARTEN // StallGuard2 value count
#define TMC262_1420_SEDN_SHIFT                   13 // min.: 0, max.: 3, default: 0
#define TMC262_1420_SEUP_MASK                    0x60 // SMARTEN // Current increment size; StallGuard2 value sample count
#define TMC262_1420_SEUP_SHIFT                   5 // min.: 0, max.: 3, default: 0
#define TMC262_1420_SEMAX_MASK                   0x0F00 // SMARTEN // Upper coolstep threshold offset
#define TMC262_1420_SEMAX_SHIFT                  8 // min.: 0, max.: 15, default: 0
#define TMC262_1420_SEMIN_MASK                   0x0F // SMARTEN // Lower coolstep threshold. SEMIN=0 => coolStep disabled
#define TMC262_1420_SEMIN_SHIFT                  0 // min.: 0, max.: 15, default: 0
//#define //TMC262_1420_REGISTER_ADDRESS_BITS_MASK 0x0E0000 // SGCSCONF // Locked for Register Browser
//#define //TMC262_1420_REGISTER_ADDRESS_BITS_SHIFT 20 // min.: 6, max.: 6, default: 0
#define TMC262_1420_SFILT_MASK                   0x010000 // SGCSCONF // stallGuard2 filter mode enable
#define TMC262_1420_SFILT_SHIFT                  16 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SGT_MASK                     0x7F00 // SGCSCONF // StallGuard2 threshold value
#define TMC262_1420_SGT_SHIFT                    8 // min.: 0, max.: 127, default: 0
#define TMC262_1420_CS_MASK                      0x1F // SGCSCONF // Current scale value
#define TMC262_1420_CS_SHIFT                     0 // min.: 0, max.: 31, default: 0
//#define //TMC262_1420_REGISTER_ADDRESS_BITS_MASK 0x0E0000 // DRVCONF // Locked for Register Browser
//#define //TMC262_1420_REGISTER_ADDRESS_BITS_SHIFT 20 // min.: 7, max.: 7, default: 0
#define TMC262_1420_TST_MASK                     0x010000 // DRVCONF // Reserved Test mode
#define TMC262_1420_TST_SHIFT                    16 // min.: 0, max.: 1, default: 0
#define TMC262_1420_SLPH_MASK                    0xC000 // DRVCONF // Slope control, high side
#define TMC262_1420_SLPH_SHIFT                   14 // min.: 0, max.: 3, default: 0
#define TMC262_1420_SLPL_MASK                    0x3000 // DRVCONF // Slope control, low side
#define TMC262_1420_SLPL_SHIFT                   12 // min.: 0, max.: 3, default: 0
#define TMC262_1420_DISS2G_MASK                  0x0400 // DRVCONF // Disable Short to ground protection
#define TMC262_1420_DISS2G_SHIFT                 10 // min.: 0, max.: 1, default: 0
#define TMC262_1420_TS2G_MASK                    0x0300 // DRVCONF // Short to ground detection timer
#define TMC262_1420_TS2G_SHIFT                   8 // min.: 0, max.: 3, default: 0
#define TMC262_1420_SDOFF_MASK                   0x80 // DRVCONF // Disable S/D interface
#define TMC262_1420_SDOFF_SHIFT                  7 // min.: 0, max.: 1, default: 0
#define TMC262_1420_VSENSE_MASK                  0x40 // DRVCONF // Sense resistor voltage-based current scaling
#define TMC262_1420_VSENSE_SHIFT                 6 // min.: 0, max.: 1, default: 0
#define TMC262_1420_RDSEL_MASK                   0x30 // DRVCONF // RD bit selection => DRVSTATUS(19:10)
#define TMC262_1420_RDSEL_SHIFT                  4 // min.: 0, max.: 2, default: 0

#endif /* TMC262_1420_FIELDS_H */
