/*******************************************************************************
* Copyright © 2019 TRINAMIC Motion Control GmbH & Co. KG
* (now owned by Analog Devices Inc.),
*
* Copyright © 2023 Analog Devices Inc. All Rights Reserved. This software is
* proprietary & confidential to Analog Devices, Inc. and its licensors.
*******************************************************************************/


// Autogenerated C header for registers in TMC2160
// Version: 1.0.0

#ifndef TMC2160_REGISTERS
#define TMC2160_REGISTERS

#define TMC2160_GCONF         0x00
#define TMC2160_GSTAT         0x01
#define TMC2160_IOIN___OUTPUT 0x04
#define TMC2160_X_COMPARE     0x05
#define TMC2160_OTP_PROG      0x06
#define TMC2160_OTP_READ      0x07
#define TMC2160_FACTORY_CONF  0x08
#define TMC2160_SHORT_CONF    0x09
#define TMC2160_DRV_CONF      0x0A
#define TMC2160_GLOBAL_SCALER 0x0B
#define TMC2160_OFFSET_READ   0x0C
#define TMC2160_IHOLD_IRUN    0x10
#define TMC2160_TPOWERDOWN    0x11
#define TMC2160_TSTEP         0x12
#define TMC2160_TPWMTHRS      0x13
#define TMC2160_TCOOLTHRS     0x14
#define TMC2160_THIGH         0x15
#define TMC2160_XDIRECT       0x2D
#define TMC2160_VDCMIN        0x33
#define TMC2160_MSLUT__       0x60
//#define TMC2160_MSLUT__       0x61
//#define TMC2160_MSLUT__       0x62
//#define TMC2160_MSLUT__       0x63
//#define TMC2160_MSLUT__       0x64
//#define TMC2160_MSLUT__       0x65
//#define TMC2160_MSLUT__       0x66
//#define TMC2160_MSLUT__       0x67
#define TMC2160_MSLUTSEL      0x68
#define TMC2160_MSLUTSTART    0x69
#define TMC2160_MSCNT         0x6A
#define TMC2160_MSCURACT      0x6B
#define TMC2160_CHOPCONF      0x6C
#define TMC2160_COOLCONF      0x6D
#define TMC2160_DCCTRL        0x6E
#define TMC2160_DRV_STATUS    0x6F
#define TMC2160_PWMCONF       0x70
#define TMC2160_PWM_SCALE     0x71
#define TMC2160_PWM_AUTO      0x72
#define TMC2160_LOST_STEPS    0x73

#endif
