/*******************************************************************************
* Copyright © 2025 Analog Devices Inc. All Rights Reserved.
* This software is proprietary to Analog Devices, Inc. and its licensors.
*******************************************************************************/

#ifndef TMC9660_BL_HW_ABSTRACTION_H_
#define TMC9660_BL_HW_ABSTRACTION_H_

#include <stdbool.h>
#include <stdint.h>

#ifndef TMC_REGISTERFIELD32_DEFINED
#define TMC_REGISTERFIELD32_DEFINED
typedef struct
{
    uint32_t mask;
    uint8_t shift;
    uint32_t address;
    bool isSigned;
} RegisterField32;


static inline uint32_t field_extract32(uint32_t data, RegisterField32 field)
{
    uint32_t value = (data & field.mask) >> field.shift;

    if (field.isSigned)
    {
        // Apply signedness conversion
        uint32_t baseMask = field.mask >> field.shift;
        uint32_t signMask = baseMask & (~baseMask >> 1);
        value = (value ^ signMask) - signMask;
    }

    return value;
}

static inline uint32_t field_update32(uint32_t data, RegisterField32 field, uint32_t value)
{
    return (data & (~field.mask)) | ((value << field.shift) & field.mask);
}

#endif /* TMC_REGISTERFIELD32_DEFINED */

#ifndef TMC_REGISTERFIELD16_DEFINED
#define TMC_REGISTERFIELD16_DEFINED
typedef struct
{
    uint16_t mask;
    uint8_t shift;
    uint32_t address;
    bool isSigned;
} RegisterField16;

static inline uint16_t field_extract16(uint16_t data, RegisterField16 field)
{
    uint16_t value = (data & field.mask) >> field.shift;

    if (field.isSigned)
    {
        // Apply signedness conversion
        uint16_t baseMask = field.mask >> field.shift;
        uint16_t signMask = baseMask & (~baseMask >> 1);
        value = (value ^ signMask) - signMask;
    }

    return value;
}

static inline uint16_t field_update16(uint16_t data, RegisterField16 field, uint16_t value)
{
    return (data & (~field.mask)) | ((value << field.shift) & field.mask);
}
#endif /* TMC_REGISTERFIELD16_DEFINED */

// CONFIG addresses
#define CONFIG_BOOT_00_POWER                    0x00020000
#define CONFIG_BOOT_01_ADDRESS                  0x00020002
#define CONFIG_BOOT_02_UART_TXEN_DELAY          0x00020004
#define CONFIG_BOOT_03_BOOT_INTERFACE           0x00020006
#define CONFIG_BOOT_04_BOOTSTRAP                0x00020008
#define CONFIG_BOOT_05_FLASH                    0x0002000A
#define CONFIG_BOOT_06_EEPROM                   0x0002000C
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT      0x0002000E
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT       0x00020010
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT    0x00020012
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT  0x00020014
#define CONFIG_BOOT_0B_GPIO_16_18_INIT          0x00020016
#define CONFIG_BOOT_0C_CLK_SEL_INIT             0x00020018
#define CONFIG_BOOT_0E_PLL_CONFIG0              0x0002001C
#define CONFIG_BOOT_0F_PLL_CONFIG1              0x0002001E
#define CONFIG_BOOT_10_APP_CONFIG_0             0x00020020
#define CONFIG_BOOT_11_APP_CONFIG_1             0x00020022
#define CONFIG_BOOT_12_APP_CONFIG_2             0x00020024
#define CONFIG_BOOT_13_APP_CONFIG_3             0x00020026
#define CONFIG_BOOT_14_APP_CONFIG_4             0x00020028
#define CONFIG_BOOT_15_RESERVED                 0x0002002A
#define CONFIG_BOOT_16_RESERVED                 0x0002002C
#define CONFIG_BOOT_17_RESERVED                 0x0002002E
#define CONFIG_BOOT_18_RESERVED                 0x00020030
#define CONFIG_BOOT_19_RESERVED                 0x00020032
#define CONFIG_BOOT_1A_RESERVED                 0x00020034
#define CONFIG_BOOT_1B_RESERVED                 0x00020036
#define CONFIG_BOOT_1C_RESERVED                 0x00020038
#define CONFIG_BOOT_1D_RESERVED                 0x0002003A
#define CONFIG_BOOT_1E_RESERVED                 0x0002003C
#define CONFIG_BOOT_1F_RESERVED                 0x0002003E

// BOOT_00_POWER fields
#define CONFIG_BOOT_00_POWER_VEXT1_MASK                         0x0003
#define CONFIG_BOOT_00_POWER_VEXT1_SHIFT                        0
#define CONFIG_BOOT_00_POWER_VEXT1_FIELD                        ((RegisterField16) { CONFIG_BOOT_00_POWER_VEXT1_MASK, CONFIG_BOOT_00_POWER_VEXT1_SHIFT, CONFIG_BOOT_00_POWER, false })
#define CONFIG_BOOT_00_POWER_VEXT2_MASK                         0x000C
#define CONFIG_BOOT_00_POWER_VEXT2_SHIFT                        2
#define CONFIG_BOOT_00_POWER_VEXT2_FIELD                        ((RegisterField16) { CONFIG_BOOT_00_POWER_VEXT2_MASK, CONFIG_BOOT_00_POWER_VEXT2_SHIFT, CONFIG_BOOT_00_POWER, false })
#define CONFIG_BOOT_00_POWER_SS_VEXT1_MASK                      0x0030
#define CONFIG_BOOT_00_POWER_SS_VEXT1_SHIFT                     4
#define CONFIG_BOOT_00_POWER_SS_VEXT1_FIELD                     ((RegisterField16) { CONFIG_BOOT_00_POWER_SS_VEXT1_MASK, CONFIG_BOOT_00_POWER_SS_VEXT1_SHIFT, CONFIG_BOOT_00_POWER, false })
#define CONFIG_BOOT_00_POWER_SS_VEXT2_MASK                      0x00C0
#define CONFIG_BOOT_00_POWER_SS_VEXT2_SHIFT                     6
#define CONFIG_BOOT_00_POWER_SS_VEXT2_FIELD                     ((RegisterField16) { CONFIG_BOOT_00_POWER_SS_VEXT2_MASK, CONFIG_BOOT_00_POWER_SS_VEXT2_SHIFT, CONFIG_BOOT_00_POWER, false })
#define CONFIG_BOOT_00_POWER_LDO_SHORT_FAULT_MASK               0x0100
#define CONFIG_BOOT_00_POWER_LDO_SHORT_FAULT_SHIFT              8
#define CONFIG_BOOT_00_POWER_LDO_SHORT_FAULT_FIELD              ((RegisterField16) { CONFIG_BOOT_00_POWER_LDO_SHORT_FAULT_MASK, CONFIG_BOOT_00_POWER_LDO_SHORT_FAULT_SHIFT, CONFIG_BOOT_00_POWER, false })

// BOOT_01_ADDRESS fields
#define CONFIG_BOOT_01_DEVICE_ADDRESS_MASK                      0x00FF
#define CONFIG_BOOT_01_DEVICE_ADDRESS_SHIFT                     0
#define CONFIG_BOOT_01_DEVICE_ADDRESS_FIELD                     ((RegisterField16) { CONFIG_BOOT_01_DEVICE_ADDRESS_MASK, CONFIG_BOOT_01_DEVICE_ADDRESS_SHIFT, CONFIG_BOOT_01_ADDRESS, false })
#define CONFIG_BOOT_01_MASTER_ADDRESS_MASK                      0xFF00
#define CONFIG_BOOT_01_MASTER_ADDRESS_SHIFT                     8
#define CONFIG_BOOT_01_MASTER_ADDRESS_FIELD                     ((RegisterField16) { CONFIG_BOOT_01_MASTER_ADDRESS_MASK, CONFIG_BOOT_01_MASTER_ADDRESS_SHIFT, CONFIG_BOOT_01_ADDRESS, false })

// BOOT_02_UART_TXEN_DELAY fields
#define CONFIG_BOOT_02_UART_TXEN_POST_DELAY_MASK                0x00FF
#define CONFIG_BOOT_02_UART_TXEN_POST_DELAY_SHIFT               0
#define CONFIG_BOOT_02_UART_TXEN_POST_DELAY_FIELD               ((RegisterField16) { CONFIG_BOOT_02_UART_TXEN_POST_DELAY_MASK, CONFIG_BOOT_02_UART_TXEN_POST_DELAY_SHIFT, CONFIG_BOOT_02_UART_TXEN_DELAY, false })
#define CONFIG_BOOT_02_UART_TXEN_PRE_DELAY_MASK                 0xFF00
#define CONFIG_BOOT_02_UART_TXEN_PRE_DELAY_SHIFT                8
#define CONFIG_BOOT_02_UART_TXEN_PRE_DELAY_FIELD                ((RegisterField16) { CONFIG_BOOT_02_UART_TXEN_PRE_DELAY_MASK, CONFIG_BOOT_02_UART_TXEN_PRE_DELAY_SHIFT, CONFIG_BOOT_02_UART_TXEN_DELAY, false })

// BOOT_03_BOOT_INTERFACE fields
#define CONFIG_BOOT_03_INTERFACE_BL_DISABLE_UART_MASK           0x0001
#define CONFIG_BOOT_03_INTERFACE_BL_DISABLE_UART_SHIFT          0
#define CONFIG_BOOT_03_INTERFACE_BL_DISABLE_UART_FIELD          ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_DISABLE_UART_MASK, CONFIG_BOOT_03_INTERFACE_BL_DISABLE_UART_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })
#define CONFIG_BOOT_03_INTERFACE_BL_DISABLE_SPI_MASK            0x0002
#define CONFIG_BOOT_03_INTERFACE_BL_DISABLE_SPI_SHIFT           1
#define CONFIG_BOOT_03_INTERFACE_BL_DISABLE_SPI_FIELD           ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_DISABLE_SPI_MASK, CONFIG_BOOT_03_INTERFACE_BL_DISABLE_SPI_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })
#define CONFIG_BOOT_03_INTERFACE_BL_SPI_SELECT_MASK             0x0004
#define CONFIG_BOOT_03_INTERFACE_BL_SPI_SELECT_SHIFT            2
#define CONFIG_BOOT_03_INTERFACE_BL_SPI_SELECT_FIELD            ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_SPI_SELECT_MASK, CONFIG_BOOT_03_INTERFACE_BL_SPI_SELECT_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })
#define CONFIG_BOOT_03_INTERFACE_BL_UART_RX_MASK                0x0008
#define CONFIG_BOOT_03_INTERFACE_BL_UART_RX_SHIFT               3
#define CONFIG_BOOT_03_INTERFACE_BL_UART_RX_FIELD               ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_UART_RX_MASK, CONFIG_BOOT_03_INTERFACE_BL_UART_RX_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })
#define CONFIG_BOOT_03_INTERFACE_BL_UART_TX_MASK                0x0010
#define CONFIG_BOOT_03_INTERFACE_BL_UART_TX_SHIFT               4
#define CONFIG_BOOT_03_INTERFACE_BL_UART_TX_FIELD               ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_UART_TX_MASK, CONFIG_BOOT_03_INTERFACE_BL_UART_TX_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })
#define CONFIG_BOOT_03_INTERFACE_BL_UART_TXEN_MASK              0x0060
#define CONFIG_BOOT_03_INTERFACE_BL_UART_TXEN_SHIFT             5
#define CONFIG_BOOT_03_INTERFACE_BL_UART_TXEN_FIELD             ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_UART_TXEN_MASK, CONFIG_BOOT_03_INTERFACE_BL_UART_TXEN_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })
#define CONFIG_BOOT_03_INTERFACE_BL_UART_BAUDRATE_MASK          0x0380
#define CONFIG_BOOT_03_INTERFACE_BL_UART_BAUDRATE_SHIFT         7
#define CONFIG_BOOT_03_INTERFACE_BL_UART_BAUDRATE_FIELD         ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_UART_BAUDRATE_MASK, CONFIG_BOOT_03_INTERFACE_BL_UART_BAUDRATE_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })
#define CONFIG_BOOT_03_INTERFACE_BL_SPI0_SCK_MASK               0x0400
#define CONFIG_BOOT_03_INTERFACE_BL_SPI0_SCK_SHIFT              10
#define CONFIG_BOOT_03_INTERFACE_BL_SPI0_SCK_FIELD              ((RegisterField16) { CONFIG_BOOT_03_INTERFACE_BL_SPI0_SCK_MASK, CONFIG_BOOT_03_INTERFACE_BL_SPI0_SCK_SHIFT, CONFIG_BOOT_03_BOOT_INTERFACE, false })

// BOOT_04_BOOTSTRAP fields
#define CONFIG_BOOT_04_BOOTSTRAP_BOOT_APP_MASK                       0x0003
#define CONFIG_BOOT_04_BOOTSTRAP_BOOT_APP_SHIFT                      0
#define CONFIG_BOOT_04_BOOTSTRAP_BOOT_APP_FIELD                      ((RegisterField16) { CONFIG_BOOT_04_BOOTSTRAP_BOOT_APP_MASK, CONFIG_BOOT_04_BOOTSTRAP_BOOT_APP_SHIFT, CONFIG_BOOT_04_BOOTSTRAP, false })
#define CONFIG_BOOT_04_BOOTSTRAP_BL_ENTRY_FAULT_MASK                 0x0004
#define CONFIG_BOOT_04_BOOTSTRAP_BL_ENTRY_FAULT_SHIFT                2
#define CONFIG_BOOT_04_BOOTSTRAP_BL_ENTRY_FAULT_FIELD                ((RegisterField16) { CONFIG_BOOT_04_BOOTSTRAP_BL_ENTRY_FAULT_MASK, CONFIG_BOOT_04_BOOTSTRAP_BL_ENTRY_FAULT_SHIFT, CONFIG_BOOT_04_BOOTSTRAP, false })
#define CONFIG_BOOT_04_BOOTSTRAP_BL_EXIT_FAULT_MASK                  0x0008
#define CONFIG_BOOT_04_BOOTSTRAP_BL_EXIT_FAULT_SHIFT                 3
#define CONFIG_BOOT_04_BOOTSTRAP_BL_EXIT_FAULT_FIELD                 ((RegisterField16) { CONFIG_BOOT_04_BOOTSTRAP_BL_EXIT_FAULT_MASK, CONFIG_BOOT_04_BOOTSTRAP_BL_EXIT_FAULT_SHIFT, CONFIG_BOOT_04_BOOTSTRAP, false })
#define CONFIG_BOOT_04_BOOTSTRAP_EXT_MEM_RETRIES_MASK                0x00F0
#define CONFIG_BOOT_04_BOOTSTRAP_EXT_MEM_RETRIES_SHIFT               4
#define CONFIG_BOOT_04_BOOTSTRAP_EXT_MEM_RETRIES_FIELD               ((RegisterField16) { CONFIG_BOOT_04_BOOTSTRAP_EXT_MEM_RETRIES_MASK, CONFIG_BOOT_04_BOOTSTRAP_EXT_MEM_RETRIES_SHIFT, CONFIG_BOOT_04_BOOTSTRAP, false })
#define CONFIG_BOOT_04_BOOTSTRAP_DISABLE_SELF_TEST_MASK              0x0100
#define CONFIG_BOOT_04_BOOTSTRAP_DISABLE_SELF_TEST_SHIFT             8
#define CONFIG_BOOT_04_BOOTSTRAP_DISABLE_SELF_TEST_FIELD             ((RegisterField16) { CONFIG_BOOT_04_BOOTSTRAP_DISABLE_SELF_TEST_MASK, CONFIG_BOOT_04_BOOTSTRAP_DISABLE_SELF_TEST_SHIFT, CONFIG_BOOT_04_BOOTSTRAP, false })
#define CONFIG_BOOT_04_BOOTSTRAP_BL_CONFIG_FAULT_MASK                0x0200
#define CONFIG_BOOT_04_BOOTSTRAP_BL_CONFIG_FAULT_SHIFT               9
#define CONFIG_BOOT_04_BOOTSTRAP_BL_CONFIG_FAULT_FIELD               ((RegisterField16) { CONFIG_BOOT_04_BOOTSTRAP_BL_CONFIG_FAULT_MASK, CONFIG_BOOT_04_BOOTSTRAP_BL_CONFIG_FAULT_SHIFT, CONFIG_BOOT_04_BOOTSTRAP, false })
#define CONFIG_BOOT_04_BOOTSTRAP_LOAD_ROM_CODE_MASK                  0x1000
#define CONFIG_BOOT_04_BOOTSTRAP_LOAD_ROM_CODE_SHIFT                 12
#define CONFIG_BOOT_04_BOOTSTRAP_LOAD_ROM_CODE_FIELD                 ((RegisterField16) { CONFIG_BOOT_04_BOOTSTRAP_LOAD_ROM_CODE_MASK, CONFIG_BOOT_04_BOOTSTRAP_LOAD_ROM_CODE_SHIFT, CONFIG_BOOT_04_BOOTSTRAP, false })

// BOOT_05_FLASH fields
#define CONFIG_BOOT_05_SPI_FLASH_EN_MASK                        0x0001
#define CONFIG_BOOT_05_SPI_FLASH_EN_SHIFT                       0
#define CONFIG_BOOT_05_SPI_FLASH_EN_FIELD                       ((RegisterField16) { CONFIG_BOOT_05_SPI_FLASH_EN_MASK, CONFIG_BOOT_05_SPI_FLASH_EN_SHIFT, CONFIG_BOOT_05_FLASH, false })
#define CONFIG_BOOT_05_FLASH_SPI_CS_SW_MASK                     0x00F8
#define CONFIG_BOOT_05_FLASH_SPI_CS_SW_SHIFT                    3
#define CONFIG_BOOT_05_FLASH_SPI_CS_SW_FIELD                    ((RegisterField16) { CONFIG_BOOT_05_FLASH_SPI_CS_SW_MASK, CONFIG_BOOT_05_FLASH_SPI_CS_SW_SHIFT, CONFIG_BOOT_05_FLASH, false })
#define CONFIG_BOOT_05_FLASH_SPI_DIV_MASK                       0x0F00
#define CONFIG_BOOT_05_FLASH_SPI_DIV_SHIFT                      8
#define CONFIG_BOOT_05_FLASH_SPI_DIV_FIELD                      ((RegisterField16) { CONFIG_BOOT_05_FLASH_SPI_DIV_MASK, CONFIG_BOOT_05_FLASH_SPI_DIV_SHIFT, CONFIG_BOOT_05_FLASH, false })

// BOOT_06_EEPROM fields
#define CONFIG_BOOT_06_I2C_EEPROM_EN_MASK                       0x0001
#define CONFIG_BOOT_06_I2C_EEPROM_EN_SHIFT                      0
#define CONFIG_BOOT_06_I2C_EEPROM_EN_FIELD                      ((RegisterField16) { CONFIG_BOOT_06_I2C_EEPROM_EN_MASK, CONFIG_BOOT_06_I2C_EEPROM_EN_SHIFT, CONFIG_BOOT_06_EEPROM, false })
#define CONFIG_BOOT_06_EEPROM_I2C_SDA_MASK                      0x0006
#define CONFIG_BOOT_06_EEPROM_I2C_SDA_SHIFT                     1
#define CONFIG_BOOT_06_EEPROM_I2C_SDA_FIELD                     ((RegisterField16) { CONFIG_BOOT_06_EEPROM_I2C_SDA_MASK, CONFIG_BOOT_06_EEPROM_I2C_SDA_SHIFT, CONFIG_BOOT_06_EEPROM, false })
#define CONFIG_BOOT_06_EEPROM_I2C_SCL_MASK                      0x0018
#define CONFIG_BOOT_06_EEPROM_I2C_SCL_SHIFT                     3
#define CONFIG_BOOT_06_EEPROM_I2C_SCL_FIELD                     ((RegisterField16) { CONFIG_BOOT_06_EEPROM_I2C_SCL_MASK, CONFIG_BOOT_06_EEPROM_I2C_SCL_SHIFT, CONFIG_BOOT_06_EEPROM, false })
#define CONFIG_BOOT_06_EEPROM_I2C_ADDR_MASK                     0x00E0
#define CONFIG_BOOT_06_EEPROM_I2C_ADDR_SHIFT                    5
#define CONFIG_BOOT_06_EEPROM_I2C_ADDR_FIELD                    ((RegisterField16) { CONFIG_BOOT_06_EEPROM_I2C_ADDR_MASK, CONFIG_BOOT_06_EEPROM_I2C_ADDR_SHIFT, CONFIG_BOOT_06_EEPROM, false })
#define CONFIG_BOOT_06_EEPROM_I2C_MUL_MASK                      0x0700
#define CONFIG_BOOT_06_EEPROM_I2C_MUL_SHIFT                     8
#define CONFIG_BOOT_06_EEPROM_I2C_MUL_FIELD                     ((RegisterField16) { CONFIG_BOOT_06_EEPROM_I2C_MUL_MASK, CONFIG_BOOT_06_EEPROM_I2C_MUL_SHIFT, CONFIG_BOOT_06_EEPROM, false })

// BOOT_07_GPIO_DATA_0_15_INIT fields
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO0_OUT_MASK       0x0001
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO0_OUT_SHIFT      0
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO0_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO0_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO0_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO1_OUT_MASK       0x0002
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO1_OUT_SHIFT      1
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO1_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO1_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO1_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO2_OUT_MASK       0x0004
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO2_OUT_SHIFT      2
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO2_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO2_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO2_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO3_OUT_MASK       0x0008
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO3_OUT_SHIFT      3
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO3_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO3_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO3_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO4_OUT_MASK       0x0010
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO4_OUT_SHIFT      4
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO4_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO4_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO4_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO5_OUT_MASK       0x0020
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO5_OUT_SHIFT      5
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO5_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO5_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO5_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO6_OUT_MASK       0x0040
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO6_OUT_SHIFT      6
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO6_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO6_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO6_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO7_OUT_MASK       0x0080
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO7_OUT_SHIFT      7
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO7_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO7_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO7_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO8_OUT_MASK       0x0100
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO8_OUT_SHIFT      8
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO8_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO8_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO8_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO9_OUT_MASK       0x0200
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO9_OUT_SHIFT      9
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO9_OUT_FIELD      ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO9_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO9_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO10_OUT_MASK      0x0400
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO10_OUT_SHIFT     10
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO10_OUT_FIELD     ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO10_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO10_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO11_OUT_MASK      0x0800
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO11_OUT_SHIFT     11
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO11_OUT_FIELD     ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO11_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO11_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO12_OUT_MASK      0x1000
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO12_OUT_SHIFT     12
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO12_OUT_FIELD     ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO12_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO12_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO13_OUT_MASK      0x2000
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO13_OUT_SHIFT     13
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO13_OUT_FIELD     ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO13_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO13_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO14_OUT_MASK      0x4000
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO14_OUT_SHIFT     14
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO14_OUT_FIELD     ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO14_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO14_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO15_OUT_MASK      0x8000
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO15_OUT_SHIFT     15
#define CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO15_OUT_FIELD     ((RegisterField16) { CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO15_OUT_MASK, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT_GPIO15_OUT_SHIFT, CONFIG_BOOT_07_GPIO_DATA_0_15_INIT, false })

// BOOT_08_GPIO_DIR_0_15_INIT fields
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO0_OUT_EN_MASK     0x0001
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO0_OUT_EN_SHIFT    0
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO0_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO0_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO0_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO1_OUT_EN_MASK     0x0002
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO1_OUT_EN_SHIFT    1
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO1_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO1_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO1_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO2_OUT_EN_MASK     0x0004
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO2_OUT_EN_SHIFT    2
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO2_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO2_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO2_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO3_OUT_EN_MASK     0x0008
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO3_OUT_EN_SHIFT    3
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO3_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO3_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO3_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO4_OUT_EN_MASK     0x0010
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO4_OUT_EN_SHIFT    4
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO4_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO4_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO4_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO5_OUT_EN_MASK     0x0020
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO5_OUT_EN_SHIFT    5
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO5_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO5_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO5_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO6_OUT_EN_MASK     0x0040
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO6_OUT_EN_SHIFT    6
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO6_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO6_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO6_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO7_OUT_EN_MASK     0x0080
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO7_OUT_EN_SHIFT    7
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO7_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO7_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO7_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO8_OUT_EN_MASK     0x0100
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO8_OUT_EN_SHIFT    8
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO8_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO8_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO8_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO9_OUT_EN_MASK     0x0200
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO9_OUT_EN_SHIFT    9
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO9_OUT_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO9_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO9_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO10_OUT_EN_MASK    0x0400
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO10_OUT_EN_SHIFT   10
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO10_OUT_EN_FIELD   ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO10_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO10_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO11_OUT_EN_MASK    0x0800
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO11_OUT_EN_SHIFT   11
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO11_OUT_EN_FIELD   ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO11_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO11_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO12_OUT_EN_MASK    0x1000
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO12_OUT_EN_SHIFT   12
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO12_OUT_EN_FIELD   ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO12_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO12_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO13_OUT_EN_MASK    0x2000
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO13_OUT_EN_SHIFT   13
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO13_OUT_EN_FIELD   ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO13_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO13_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO14_OUT_EN_MASK    0x4000
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO14_OUT_EN_SHIFT   14
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO14_OUT_EN_FIELD   ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO14_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO14_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO15_OUT_EN_MASK    0x8000
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO15_OUT_EN_SHIFT   15
#define CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO15_OUT_EN_FIELD   ((RegisterField16) { CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO15_OUT_EN_MASK, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT_GPIO15_OUT_EN_SHIFT, CONFIG_BOOT_08_GPIO_DIR_0_15_INIT, false })

// BOOT_09_GPIO_PULLUP_0_15_INIT fields
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO0_PU_MASK      0x0001
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO0_PU_SHIFT     0
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO0_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO0_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO0_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO1_PU_MASK      0x0002
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO1_PU_SHIFT     1
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO1_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO1_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO1_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO2_PU_MASK      0x0004
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO2_PU_SHIFT     2
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO2_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO2_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO2_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO3_PU_MASK      0x0008
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO3_PU_SHIFT     3
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO3_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO3_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO3_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO4_PU_MASK      0x0010
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO4_PU_SHIFT     4
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO4_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO4_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO4_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO5_PU_MASK      0x0020
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO5_PU_SHIFT     5
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO5_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO5_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO5_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO6_PU_MASK      0x0040
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO6_PU_SHIFT     6
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO6_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO6_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO6_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO7_PU_MASK      0x0080
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO7_PU_SHIFT     7
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO7_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO7_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO7_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO8_PU_MASK      0x0100
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO8_PU_SHIFT     8
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO8_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO8_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO8_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO9_PU_MASK      0x0200
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO9_PU_SHIFT     9
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO9_PU_FIELD     ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO9_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO9_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO10_PU_MASK     0x0400
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO10_PU_SHIFT    10
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO10_PU_FIELD    ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO10_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO10_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO11_PU_MASK     0x0800
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO11_PU_SHIFT    11
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO11_PU_FIELD    ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO11_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO11_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO12_PU_MASK     0x1000
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO12_PU_SHIFT    12
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO12_PU_FIELD    ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO12_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO12_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO13_PU_MASK     0x2000
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO13_PU_SHIFT    13
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO13_PU_FIELD    ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO13_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO13_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO14_PU_MASK     0x4000
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO14_PU_SHIFT    14
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO14_PU_FIELD    ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO14_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO14_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO15_PU_MASK     0x8000
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO15_PU_SHIFT    15
#define CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO15_PU_FIELD    ((RegisterField16) { CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO15_PU_MASK, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT_GPIO15_PU_SHIFT, CONFIG_BOOT_09_GPIO_PULLUP_0_15_INIT, false })

// BOOT_0A_GPIO_PULLDOWN_0_15_INIT fields
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO0_PD_MASK    0x0001
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO0_PD_SHIFT   0
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO0_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO0_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO0_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO1_PD_MASK    0x0002
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO1_PD_SHIFT   1
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO1_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO1_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO1_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO2_PD_MASK    0x0004
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO2_PD_SHIFT   2
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO2_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO2_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO2_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO3_PD_MASK    0x0008
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO3_PD_SHIFT   3
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO3_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO3_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO3_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO4_PD_MASK    0x0010
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO4_PD_SHIFT   4
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO4_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO4_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO4_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO5_PD_MASK    0x0020
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO5_PD_SHIFT   5
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO5_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO5_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO5_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO6_PD_MASK    0x0040
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO6_PD_SHIFT   6
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO6_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO6_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO6_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO7_PD_MASK    0x0080
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO7_PD_SHIFT   7
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO7_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO7_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO7_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO8_PD_MASK    0x0100
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO8_PD_SHIFT   8
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO8_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO8_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO8_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO9_PD_MASK    0x0200
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO9_PD_SHIFT   9
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO9_PD_FIELD   ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO9_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO9_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO10_PD_MASK   0x0400
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO10_PD_SHIFT  10
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO10_PD_FIELD  ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO10_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO10_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO11_PD_MASK   0x0800
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO11_PD_SHIFT  11
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO11_PD_FIELD  ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO11_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO11_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO12_PD_MASK   0x1000
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO12_PD_SHIFT  12
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO12_PD_FIELD  ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO12_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO12_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO13_PD_MASK   0x2000
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO13_PD_SHIFT  13
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO13_PD_FIELD  ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO13_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO13_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO14_PD_MASK   0x4000
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO14_PD_SHIFT  14
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO14_PD_FIELD  ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO14_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO14_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO15_PD_MASK   0x8000
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO15_PD_SHIFT  15
#define CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO15_PD_FIELD  ((RegisterField16) { CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO15_PD_MASK, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT_GPIO15_PD_SHIFT, CONFIG_BOOT_0A_GPIO_PULLDOWN_0_15_INIT, false })

// BOOT_0B_GPIO_16_18_INIT fields
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_MASK          0x0001
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_SHIFT         0
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_FIELD         ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_MASK          0x0002
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_SHIFT         1
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_FIELD         ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_MASK          0x0004
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_SHIFT         2
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_FIELD         ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_EN_MASK       0x0008
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_EN_SHIFT      3
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_EN_FIELD      ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_EN_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_OUT_EN_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_EN_MASK       0x0010
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_EN_SHIFT      4
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_EN_FIELD      ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_EN_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_OUT_EN_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_EN_MASK       0x0020
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_EN_SHIFT      5
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_EN_FIELD      ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_EN_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_OUT_EN_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PD_MASK           0x0040
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PD_SHIFT          6
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PD_FIELD          ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PD_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PD_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PD_MASK           0x0080
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PD_SHIFT          7
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PD_FIELD          ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PD_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PD_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PD_MASK           0x0100
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PD_SHIFT          8
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PD_FIELD          ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PD_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PD_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PU_MASK           0x0200
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PU_SHIFT          9
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PU_FIELD          ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PU_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO16_PU_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PU_MASK           0x0400
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PU_SHIFT          10
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PU_FIELD          ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PU_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO17_PU_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PU_MASK           0x0800
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PU_SHIFT          11
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PU_FIELD          ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PU_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO18_PU_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO2_ANALOG_EN_MASK     0x1000
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO2_ANALOG_EN_SHIFT    12
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO2_ANALOG_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO2_ANALOG_EN_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO2_ANALOG_EN_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO3_ANALOG_EN_MASK     0x2000
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO3_ANALOG_EN_SHIFT    13
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO3_ANALOG_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO3_ANALOG_EN_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO3_ANALOG_EN_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO4_ANALOG_EN_MASK     0x4000
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO4_ANALOG_EN_SHIFT    14
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO4_ANALOG_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO4_ANALOG_EN_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO4_ANALOG_EN_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO5_ANALOG_EN_MASK     0x8000
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO5_ANALOG_EN_SHIFT    15
#define CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO5_ANALOG_EN_FIELD    ((RegisterField16) { CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO5_ANALOG_EN_MASK, CONFIG_BOOT_0B_GPIO_16_18_INIT_GPIO5_ANALOG_EN_SHIFT, CONFIG_BOOT_0B_GPIO_16_18_INIT, false })

// BOOT_0C_CLK_SEL_INIT fields
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_FB_DIV_MASK             0x0000007F
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_FB_DIV_SHIFT            0
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_FB_DIV_FIELD            ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_FB_DIV_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_FB_DIV_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_XTAL_MASK           0x00000100
#define CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_XTAL_SHIFT          8
#define CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_XTAL_FIELD          ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_XTAL_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_XTAL_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_CFG_MASK               0x00000E00
#define CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_CFG_SHIFT              9
#define CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_CFG_FIELD              ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_CFG_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_CFG_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_BOOST_MASK             0x00001000
#define CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_BOOST_SHIFT            12
#define CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_BOOST_FIELD            ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_BOOST_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_XTAL_BOOST_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_INT_MASK            0x00002000
#define CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_INT_SHIFT           13
#define CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_INT_FIELD           ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_INT_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_EXT_NOT_INT_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_OUT_SEL_MASK            0x00030000
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_OUT_SEL_SHIFT           16
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_OUT_SEL_FIELD           ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_OUT_SEL_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_OUT_SEL_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_RDIV_MASK                   0x007C0000
#define CONFIG_BOOT_0C_CLK_SEL_INIT_RDIV_SHIFT                  18
#define CONFIG_BOOT_0C_CLK_SEL_INIT_RDIV_FIELD                  ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_RDIV_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_RDIV_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_SYS_CLK_DIV_MASK            0x01800000
#define CONFIG_BOOT_0C_CLK_SEL_INIT_SYS_CLK_DIV_SHIFT           23
#define CONFIG_BOOT_0C_CLK_SEL_INIT_SYS_CLK_DIV_FIELD           ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_SYS_CLK_DIV_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_SYS_CLK_DIV_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_STATUS_MASK             0x40000000
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_STATUS_SHIFT            30
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_STATUS_FIELD            ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_STATUS_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_STATUS_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_CONFIG_BOOT_MASK        0x80000000
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_CONFIG_BOOT_SHIFT       31
#define CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_CONFIG_BOOT_FIELD       ((RegisterField32) { CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_CONFIG_BOOT_MASK, CONFIG_BOOT_0C_CLK_SEL_INIT_PLL_CONFIG_BOOT_SHIFT, CONFIG_BOOT_0C_CLK_SEL_INIT, false })

// BOOT_0E_PLL_CONFIG0 fields
#define CONFIG_BOOT_0E_CONFIG0_ONE_PER_MIN_MASK                 0x001F
#define CONFIG_BOOT_0E_CONFIG0_ONE_PER_MIN_SHIFT                0
#define CONFIG_BOOT_0E_CONFIG0_ONE_PER_MIN_FIELD                ((RegisterField16) { CONFIG_BOOT_0E_CONFIG0_ONE_PER_MIN_MASK, CONFIG_BOOT_0E_CONFIG0_ONE_PER_MIN_SHIFT, CONFIG_BOOT_0E_PLL_CONFIG0, false })
#define CONFIG_BOOT_0E_CONFIG0_PLL_DEL_SEL_MASK                 0x0060
#define CONFIG_BOOT_0E_CONFIG0_PLL_DEL_SEL_SHIFT                5
#define CONFIG_BOOT_0E_CONFIG0_PLL_DEL_SEL_FIELD                ((RegisterField16) { CONFIG_BOOT_0E_CONFIG0_PLL_DEL_SEL_MASK, CONFIG_BOOT_0E_CONFIG0_PLL_DEL_SEL_SHIFT, CONFIG_BOOT_0E_PLL_CONFIG0, false })
#define CONFIG_BOOT_0E_CONFIG0_N16_PER_MIN_MSB_MASK             0x0080
#define CONFIG_BOOT_0E_CONFIG0_N16_PER_MIN_MSB_SHIFT            7
#define CONFIG_BOOT_0E_CONFIG0_N16_PER_MIN_MSB_FIELD            ((RegisterField16) { CONFIG_BOOT_0E_CONFIG0_N16_PER_MIN_MSB_MASK, CONFIG_BOOT_0E_CONFIG0_N16_PER_MIN_MSB_SHIFT, CONFIG_BOOT_0E_PLL_CONFIG0, false })
#define CONFIG_BOOT_0E_CONFIG0_ONE_PER_MAX_MASK                 0x1F00
#define CONFIG_BOOT_0E_CONFIG0_ONE_PER_MAX_SHIFT                8
#define CONFIG_BOOT_0E_CONFIG0_ONE_PER_MAX_FIELD                ((RegisterField16) { CONFIG_BOOT_0E_CONFIG0_ONE_PER_MAX_MASK, CONFIG_BOOT_0E_CONFIG0_ONE_PER_MAX_SHIFT, CONFIG_BOOT_0E_PLL_CONFIG0, false })
#define CONFIG_BOOT_0E_CONFIG0_PLL_ERR_OTP_MASK                 0x2000
#define CONFIG_BOOT_0E_CONFIG0_PLL_ERR_OTP_SHIFT                13
#define CONFIG_BOOT_0E_CONFIG0_PLL_ERR_OTP_FIELD                ((RegisterField16) { CONFIG_BOOT_0E_CONFIG0_PLL_ERR_OTP_MASK, CONFIG_BOOT_0E_CONFIG0_PLL_ERR_OTP_SHIFT, CONFIG_BOOT_0E_PLL_CONFIG0, false })
#define CONFIG_BOOT_0E_CONFIG0_SEL_ERR_OTP_MASK                 0x4000
#define CONFIG_BOOT_0E_CONFIG0_SEL_ERR_OTP_SHIFT                14
#define CONFIG_BOOT_0E_CONFIG0_SEL_ERR_OTP_FIELD                ((RegisterField16) { CONFIG_BOOT_0E_CONFIG0_SEL_ERR_OTP_MASK, CONFIG_BOOT_0E_CONFIG0_SEL_ERR_OTP_SHIFT, CONFIG_BOOT_0E_PLL_CONFIG0, false })
#define CONFIG_BOOT_0E_CONFIG0_N16_PER_MAX_MSB_MASK             0x8000
#define CONFIG_BOOT_0E_CONFIG0_N16_PER_MAX_MSB_SHIFT            15
#define CONFIG_BOOT_0E_CONFIG0_N16_PER_MAX_MSB_FIELD            ((RegisterField16) { CONFIG_BOOT_0E_CONFIG0_N16_PER_MAX_MSB_MASK, CONFIG_BOOT_0E_CONFIG0_N16_PER_MAX_MSB_SHIFT, CONFIG_BOOT_0E_PLL_CONFIG0, false })

// BOOT_0F_PLL_CONFIG1 fields
#define CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MIN_MASK             0x00FF
#define CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MIN_SHIFT            0
#define CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MIN_FIELD            ((RegisterField16) { CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MIN_MASK, CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MIN_SHIFT, CONFIG_BOOT_0F_PLL_CONFIG1, false })
#define CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MAX_MASK             0xFF00
#define CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MAX_SHIFT            8
#define CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MAX_FIELD            ((RegisterField16) { CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MAX_MASK, CONFIG_BOOT_0F_PLL_CONFIG1_N16_PER_MAX_SHIFT, CONFIG_BOOT_0F_PLL_CONFIG1, false })

// BOOT_10_APP_CONFIG_0 fields
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_ENABLE_MASK            0x0001
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_ENABLE_SHIFT           0
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_ENABLE_FIELD           ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_HALL_ENABLE_MASK, CONFIG_BOOT_10_APP_CONFIG_0_HALL_ENABLE_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_ENABLE_MASK            0x0002
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_ENABLE_SHIFT           1
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_ENABLE_FIELD           ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_ABN1_ENABLE_MASK, CONFIG_BOOT_10_APP_CONFIG_0_ABN1_ENABLE_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_UX_MASK                0x0030
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_UX_SHIFT               4
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_UX_FIELD               ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_HALL_UX_MASK, CONFIG_BOOT_10_APP_CONFIG_0_HALL_UX_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_V_MASK                 0x00C0
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_V_SHIFT                6
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_V_FIELD                ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_HALL_V_MASK, CONFIG_BOOT_10_APP_CONFIG_0_HALL_V_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_WY_MASK                0x0300
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_WY_SHIFT               8
#define CONFIG_BOOT_10_APP_CONFIG_0_HALL_WY_FIELD               ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_HALL_WY_MASK, CONFIG_BOOT_10_APP_CONFIG_0_HALL_WY_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_A_MASK                 0x0C00
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_A_SHIFT                10
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_A_FIELD                ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_ABN1_A_MASK, CONFIG_BOOT_10_APP_CONFIG_0_ABN1_A_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_B_MASK                 0x3000
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_B_SHIFT                12
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_B_FIELD                ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_ABN1_B_MASK, CONFIG_BOOT_10_APP_CONFIG_0_ABN1_B_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_N_MASK                 0xC000
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_N_SHIFT                14
#define CONFIG_BOOT_10_APP_CONFIG_0_ABN1_N_FIELD                ((RegisterField16) { CONFIG_BOOT_10_APP_CONFIG_0_ABN1_N_MASK, CONFIG_BOOT_10_APP_CONFIG_0_ABN1_N_SHIFT, CONFIG_BOOT_10_APP_CONFIG_0, false })

// BOOT_11_APP_CONFIG_1 fields
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_L_PIN_MASK              0x0003
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_L_PIN_SHIFT             0
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_L_PIN_FIELD             ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_REF_L_PIN_MASK, CONFIG_BOOT_11_APP_CONFIG_1_REF_L_PIN_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_R_PIN_MASK              0x000C
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_R_PIN_SHIFT             2
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_R_PIN_FIELD             ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_REF_R_PIN_MASK, CONFIG_BOOT_11_APP_CONFIG_1_REF_R_PIN_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_H_PIN_MASK              0x0070
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_H_PIN_SHIFT             4
#define CONFIG_BOOT_11_APP_CONFIG_1_REF_H_PIN_FIELD             ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_REF_H_PIN_MASK, CONFIG_BOOT_11_APP_CONFIG_1_REF_H_PIN_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_STEPDIR_ENABLE_MASK         0x0100
#define CONFIG_BOOT_11_APP_CONFIG_1_STEPDIR_ENABLE_SHIFT        8
#define CONFIG_BOOT_11_APP_CONFIG_1_STEPDIR_ENABLE_FIELD        ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_STEPDIR_ENABLE_MASK, CONFIG_BOOT_11_APP_CONFIG_1_STEPDIR_ENABLE_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_STEP_PIN_MASK               0x0600
#define CONFIG_BOOT_11_APP_CONFIG_1_STEP_PIN_SHIFT              9
#define CONFIG_BOOT_11_APP_CONFIG_1_STEP_PIN_FIELD              ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_STEP_PIN_MASK, CONFIG_BOOT_11_APP_CONFIG_1_STEP_PIN_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_DIR_PIN_MASK                0x0800
#define CONFIG_BOOT_11_APP_CONFIG_1_DIR_PIN_SHIFT               11
#define CONFIG_BOOT_11_APP_CONFIG_1_DIR_PIN_FIELD               ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_DIR_PIN_MASK, CONFIG_BOOT_11_APP_CONFIG_1_DIR_PIN_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_ENABLE_MASK            0x1000
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_ENABLE_SHIFT           12
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_ENABLE_FIELD           ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_ABN2_ENABLE_MASK, CONFIG_BOOT_11_APP_CONFIG_1_ABN2_ENABLE_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_A_MASK                 0x2000
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_A_SHIFT                13
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_A_FIELD                ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_ABN2_A_MASK, CONFIG_BOOT_11_APP_CONFIG_1_ABN2_A_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_B_MASK                 0xC000
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_B_SHIFT                14
#define CONFIG_BOOT_11_APP_CONFIG_1_ABN2_B_FIELD                ((RegisterField16) { CONFIG_BOOT_11_APP_CONFIG_1_ABN2_B_MASK, CONFIG_BOOT_11_APP_CONFIG_1_ABN2_B_SHIFT, CONFIG_BOOT_11_APP_CONFIG_1, false })

// BOOT_12_APP_CONFIG_2 fields
#define CONFIG_BOOT_12_APP_CONFIG_2_WDG_DISABLE_MASK            0x0001
#define CONFIG_BOOT_12_APP_CONFIG_2_WDG_DISABLE_SHIFT           0
#define CONFIG_BOOT_12_APP_CONFIG_2_WDG_DISABLE_FIELD           ((RegisterField16) { CONFIG_BOOT_12_APP_CONFIG_2_WDG_DISABLE_MASK, CONFIG_BOOT_12_APP_CONFIG_2_WDG_DISABLE_SHIFT, CONFIG_BOOT_12_APP_CONFIG_2, false })
#define CONFIG_BOOT_12_APP_CONFIG_2_WDG_TIMEOUT_MASK            0x000E
#define CONFIG_BOOT_12_APP_CONFIG_2_WDG_TIMEOUT_SHIFT           1
#define CONFIG_BOOT_12_APP_CONFIG_2_WDG_TIMEOUT_FIELD           ((RegisterField16) { CONFIG_BOOT_12_APP_CONFIG_2_WDG_TIMEOUT_MASK, CONFIG_BOOT_12_APP_CONFIG_2_WDG_TIMEOUT_SHIFT, CONFIG_BOOT_12_APP_CONFIG_2, false })
#define CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_ENABLE_MASK    0x0010
#define CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_ENABLE_SHIFT   4
#define CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_ENABLE_FIELD   ((RegisterField16) { CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_ENABLE_MASK, CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_ENABLE_SHIFT, CONFIG_BOOT_12_APP_CONFIG_2, false })
#define CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_OUTPUT_MASK    0x03E0
#define CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_OUTPUT_SHIFT   5
#define CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_OUTPUT_FIELD   ((RegisterField16) { CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_OUTPUT_MASK, CONFIG_BOOT_12_APP_CONFIG_2_BRAKECHOPPER_OUTPUT_SHIFT, CONFIG_BOOT_12_APP_CONFIG_2, false })
#define CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_ENABLE_MASK      0x1000
#define CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_ENABLE_SHIFT     12
#define CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_ENABLE_FIELD     ((RegisterField16) { CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_ENABLE_MASK, CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_ENABLE_SHIFT, CONFIG_BOOT_12_APP_CONFIG_2, false })
#define CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_OUTPUT_MASK      0x6000
#define CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_OUTPUT_SHIFT     13
#define CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_OUTPUT_FIELD     ((RegisterField16) { CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_OUTPUT_MASK, CONFIG_BOOT_12_APP_CONFIG_2_MECH_BRAKE_OUTPUT_SHIFT, CONFIG_BOOT_12_APP_CONFIG_2, false })

// BOOT_13_APP_CONFIG_3 fields
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_ENABLE_MASK         0x0001
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_ENABLE_SHIFT        0
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_ENABLE_FIELD        ((RegisterField16) { CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_ENABLE_MASK, CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_ENABLE_SHIFT, CONFIG_BOOT_13_APP_CONFIG_3, false })
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_BLOCK_MASK          0x0002
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_BLOCK_SHIFT         1
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_BLOCK_FIELD         ((RegisterField16) { CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_BLOCK_MASK, CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_BLOCK_SHIFT, CONFIG_BOOT_13_APP_CONFIG_3, false })
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_MODE_MASK           0x000C
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_MODE_SHIFT          2
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_MODE_FIELD          ((RegisterField16) { CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_MODE_MASK, CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_MODE_SHIFT, CONFIG_BOOT_13_APP_CONFIG_3, false })
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_FREQ_MASK           0x00F0
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_FREQ_SHIFT          4
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_FREQ_FIELD          ((RegisterField16) { CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_FREQ_MASK, CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_FREQ_SHIFT, CONFIG_BOOT_13_APP_CONFIG_3, false })
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_PIN_MASK         0x0300
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_PIN_SHIFT        8
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_PIN_FIELD        ((RegisterField16) { CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_PIN_MASK, CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_PIN_SHIFT, CONFIG_BOOT_13_APP_CONFIG_3, false })
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_POL_MASK         0x0400
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_POL_SHIFT        10
#define CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_POL_FIELD        ((RegisterField16) { CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_POL_MASK, CONFIG_BOOT_13_APP_CONFIG_3_SPI_ENC_CS_POL_SHIFT, CONFIG_BOOT_13_APP_CONFIG_3, false })

// BOOT_14_APP_CONFIG_4 fields
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_TMCL_SCRIPT_MASK        0x0003
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_TMCL_SCRIPT_SHIFT       0
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_TMCL_SCRIPT_FIELD       ((RegisterField16) { CONFIG_BOOT_14_APP_CONFIG_4_MEM_TMCL_SCRIPT_MASK, CONFIG_BOOT_14_APP_CONFIG_4_MEM_TMCL_SCRIPT_SHIFT, CONFIG_BOOT_14_APP_CONFIG_4, false })
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_PARAMETERS_MASK         0x000C
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_PARAMETERS_SHIFT        2
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_PARAMETERS_FIELD        ((RegisterField16) { CONFIG_BOOT_14_APP_CONFIG_4_MEM_PARAMETERS_MASK, CONFIG_BOOT_14_APP_CONFIG_4_MEM_PARAMETERS_SHIFT, CONFIG_BOOT_14_APP_CONFIG_4, false })
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_STIMULUS_MASK           0x0010
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_STIMULUS_SHIFT          4
#define CONFIG_BOOT_14_APP_CONFIG_4_MEM_STIMULUS_FIELD          ((RegisterField16) { CONFIG_BOOT_14_APP_CONFIG_4_MEM_STIMULUS_MASK, CONFIG_BOOT_14_APP_CONFIG_4_MEM_STIMULUS_SHIFT, CONFIG_BOOT_14_APP_CONFIG_4, false })

// BOOT_15_RESERVED fields
#define CONFIG_BOOT_15_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_15_RESERVED_SHIFT                           0
#define CONFIG_BOOT_15_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_15_RESERVED_MASK, CONFIG_BOOT_15_RESERVED_SHIFT, CONFIG_BOOT_15_RESERVED, false })

// BOOT_16_RESERVED fields
#define CONFIG_BOOT_16_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_16_RESERVED_SHIFT                           0
#define CONFIG_BOOT_16_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_16_RESERVED_MASK, CONFIG_BOOT_16_RESERVED_SHIFT, CONFIG_BOOT_16_RESERVED, false })

// BOOT_17_RESERVED fields
#define CONFIG_BOOT_17_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_17_RESERVED_SHIFT                           0
#define CONFIG_BOOT_17_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_17_RESERVED_MASK, CONFIG_BOOT_17_RESERVED_SHIFT, CONFIG_BOOT_17_RESERVED, false })

// BOOT_18_RESERVED fields
#define CONFIG_BOOT_18_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_18_RESERVED_SHIFT                           0
#define CONFIG_BOOT_18_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_18_RESERVED_MASK, CONFIG_BOOT_18_RESERVED_SHIFT, CONFIG_BOOT_18_RESERVED, false })

// BOOT_19_RESERVED fields
#define CONFIG_BOOT_19_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_19_RESERVED_SHIFT                           0
#define CONFIG_BOOT_19_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_19_RESERVED_MASK, CONFIG_BOOT_19_RESERVED_SHIFT, CONFIG_BOOT_19_RESERVED, false })

// BOOT_1A_RESERVED fields
#define CONFIG_BOOT_1A_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_1A_RESERVED_SHIFT                           0
#define CONFIG_BOOT_1A_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_1A_RESERVED_MASK, CONFIG_BOOT_1A_RESERVED_SHIFT, CONFIG_BOOT_1A_RESERVED, false })

// BOOT_1B_RESERVED fields
#define CONFIG_BOOT_1B_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_1B_RESERVED_SHIFT                           0
#define CONFIG_BOOT_1B_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_1B_RESERVED_MASK, CONFIG_BOOT_1B_RESERVED_SHIFT, CONFIG_BOOT_1B_RESERVED, false })

// BOOT_1C_RESERVED fields
#define CONFIG_BOOT_1C_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_1C_RESERVED_SHIFT                           0
#define CONFIG_BOOT_1C_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_1C_RESERVED_MASK, CONFIG_BOOT_1C_RESERVED_SHIFT, CONFIG_BOOT_1C_RESERVED, false })

// BOOT_1D_RESERVED fields
#define CONFIG_BOOT_1D_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_1D_RESERVED_SHIFT                           0
#define CONFIG_BOOT_1D_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_1D_RESERVED_MASK, CONFIG_BOOT_1D_RESERVED_SHIFT, CONFIG_BOOT_1D_RESERVED, false })

// BOOT_1E_RESERVED fields
#define CONFIG_BOOT_1E_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_1E_RESERVED_SHIFT                           0
#define CONFIG_BOOT_1E_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_1E_RESERVED_MASK, CONFIG_BOOT_1E_RESERVED_SHIFT, CONFIG_BOOT_1E_RESERVED, false })

// BOOT_1F_RESERVED fields
#define CONFIG_BOOT_1F_RESERVED_MASK                            0xFFFF
#define CONFIG_BOOT_1F_RESERVED_SHIFT                           0
#define CONFIG_BOOT_1F_RESERVED_FIELD                           ((RegisterField16) { CONFIG_BOOT_1F_RESERVED_MASK, CONFIG_BOOT_1F_RESERVED_SHIFT, CONFIG_BOOT_1F_RESERVED, false })

#endif /* TMC9660_BL_HW_ABSTRACTION_H_ */
