/*******************************************************************************
* Copyright © 2025 Analog Devices Inc. All Rights Reserved.
* This software is proprietary to Analog Devices, Inc. and its licensors.
*******************************************************************************/

#ifndef TMC9660_PARAM_HW_ABSTRACTION_H_
#define TMC9660_PARAM_HW_ABSTRACTION_H_

#define TMC9660_PARAM_MOTOR_TYPE                                      0
#define TMC9660_PARAM_MOTOR_POLE_PAIRS                                1
#define TMC9660_PARAM_MOTOR_DIRECTION                                 2
#define TMC9660_PARAM_MOTOR_PWM_FREQUENCY                             3
#define TMC9660_PARAM_COMMUTATION_MODE                                4
#define TMC9660_PARAM_OUTPUT_VOLTAGE_LIMIT                            5
#define TMC9660_PARAM_MAX_TORQUE                                      6
#define TMC9660_PARAM_MAX_FLUX                                        7
#define TMC9660_PARAM_PWM_SWITCHING_SCHEME                            8
#define TMC9660_PARAM_IDLE_MOTOR_PWM_BEHAVIOR                         9
#define TMC9660_PARAM_ADC_SHUNT_TYPE                                  12
#define TMC9660_PARAM_ADC_I0_RAW                                      13
#define TMC9660_PARAM_ADC_I1_RAW                                      14
#define TMC9660_PARAM_ADC_I2_RAW                                      15
#define TMC9660_PARAM_ADC_I3_RAW                                      16
#define TMC9660_PARAM_CSA_GAIN_ADC_I0_TO_ADC_I2                       17
#define TMC9660_PARAM_CSA_GAIN_ADC_I3                                 18
#define TMC9660_PARAM_CSA_FILTER_ADC_I0_TO_ADC_I2                     19
#define TMC9660_PARAM_CSA_FILTER_ADC_I3                               20
#define TMC9660_PARAM_CURRENT_SCALING_FACTOR                          21
#define TMC9660_PARAM_PHASE_UX1_ADC_MAPPING                           22
#define TMC9660_PARAM_PHASE_VX2_ADC_MAPPING                           23
#define TMC9660_PARAM_PHASE_WY1_ADC_MAPPING                           24
#define TMC9660_PARAM_PHASE_Y2_ADC_MAPPING                            25
#define TMC9660_PARAM_ADC_I0_SCALE                                    26
#define TMC9660_PARAM_ADC_I1_SCALE                                    27
#define TMC9660_PARAM_ADC_I2_SCALE                                    28
#define TMC9660_PARAM_ADC_I3_SCALE                                    29
#define TMC9660_PARAM_ADC_I0_INVERTED                                 30
#define TMC9660_PARAM_ADC_I1_INVERTED                                 31
#define TMC9660_PARAM_ADC_I2_INVERTED                                 32
#define TMC9660_PARAM_ADC_I3_INVERTED                                 33
#define TMC9660_PARAM_ADC_I0_OFFSET                                   34
#define TMC9660_PARAM_ADC_I1_OFFSET                                   35
#define TMC9660_PARAM_ADC_I2_OFFSET                                   36
#define TMC9660_PARAM_ADC_I3_OFFSET                                   37
#define TMC9660_PARAM_ADC_I0                                          38
#define TMC9660_PARAM_ADC_I1                                          39
#define TMC9660_PARAM_ADC_I2                                          40
#define TMC9660_PARAM_ADC_I3                                          41
#define TMC9660_PARAM_OPENLOOP_ANGLE                                  45
#define TMC9660_PARAM_OPENLOOP_CURRENT                                46
#define TMC9660_PARAM_OPENLOOP_VOLTAGE                                47
#define TMC9660_PARAM_ACCELERATION_FF_GAIN                            50
#define TMC9660_PARAM_ACCELERATION_FF_SHIFT                           51
#define TMC9660_PARAM_RAMP_ENABLE                                     52
#define TMC9660_PARAM_DIRECT_VELOCITY_MODE                            53
#define TMC9660_PARAM_RAMP_AMAX                                       54
#define TMC9660_PARAM_RAMP_A1                                         55
#define TMC9660_PARAM_RAMP_A2                                         56
#define TMC9660_PARAM_RAMP_DMAX                                       57
#define TMC9660_PARAM_RAMP_D1                                         58
#define TMC9660_PARAM_RAMP_D2                                         59
#define TMC9660_PARAM_RAMP_VMAX                                       60
#define TMC9660_PARAM_RAMP_V1                                         61
#define TMC9660_PARAM_RAMP_V2                                         62
#define TMC9660_PARAM_RAMP_VSTART                                     63
#define TMC9660_PARAM_RAMP_VSTOP                                      64
#define TMC9660_PARAM_RAMP_TVMAX                                      65
#define TMC9660_PARAM_RAMP_TZEROWAIT                                  66
#define TMC9660_PARAM_ACCELERATION_FEEDFORWARD_ENABLE                 67
#define TMC9660_PARAM_VELOCITY_FEEDFORWARD_ENABLE                     68
#define TMC9660_PARAM_RAMP_VELOCITY                                   69
#define TMC9660_PARAM_RAMP_POSITION                                   70
#define TMC9660_PARAM_HALL_PHI_E                                      74
#define TMC9660_PARAM_HALL_SECTOR_OFFSET                              75
#define TMC9660_PARAM_HALL_FILTER_LENGTH                              76
#define TMC9660_PARAM_HALL_POSITION_0_OFFSET                          77
#define TMC9660_PARAM_HALL_POSITION_60_OFFSET                         78
#define TMC9660_PARAM_HALL_POSITION_120_OFFSET                        79
#define TMC9660_PARAM_HALL_POSITION_180_OFFSET                        80
#define TMC9660_PARAM_HALL_POSITION_240_OFFSET                        81
#define TMC9660_PARAM_HALL_POSITION_300_OFFSET                        82
#define TMC9660_PARAM_HALL_INVERT_DIRECTION                           83
#define TMC9660_PARAM_HALL_EXTRAPOLATION_ENABLE                       84
#define TMC9660_PARAM_HALL_PHI_E_OFFSET                               85
#define TMC9660_PARAM_ABN_1_PHI_E                                     89
#define TMC9660_PARAM_ABN_1_STEPS                                     90
#define TMC9660_PARAM_ABN_1_DIRECTION                                 91
#define TMC9660_PARAM_ABN_1_INIT_METHOD                               92
#define TMC9660_PARAM_ABN_1_INIT_STATE                                93
#define TMC9660_PARAM_ABN_1_INIT_DELAY                                94
#define TMC9660_PARAM_ABN_1_INIT_VELOCITY                             95
#define TMC9660_PARAM_ABN_1_N_CHANNEL_PHI_E_OFFSET                    96
#define TMC9660_PARAM_ABN_1_N_CHANNEL_INVERTED                        97
#define TMC9660_PARAM_ABN_1_N_CHANNEL_FILTERING                       98
#define TMC9660_PARAM_ABN_1_CLEAR_ON_NEXT_NULL                        99
#define TMC9660_PARAM_ABN_1_VALUE                                     100
#define TMC9660_PARAM_TARGET_TORQUE                                   104
#define TMC9660_PARAM_ACTUAL_TORQUE                                   105
#define TMC9660_PARAM_TARGET_FLUX                                     106
#define TMC9660_PARAM_ACTUAL_FLUX                                     107
#define TMC9660_PARAM_TORQUE_OFFSET                                   108
#define TMC9660_PARAM_TORQUE_P                                        109
#define TMC9660_PARAM_TORQUE_I                                        110
#define TMC9660_PARAM_FLUX_P                                          111
#define TMC9660_PARAM_FLUX_I                                          112
#define TMC9660_PARAM_SEPARATE_TORQUE_FLUX_PI_PARAMTERS               113
#define TMC9660_PARAM_CURRENT_NORM_P                                  114
#define TMC9660_PARAM_CURRENT_NORM_I                                  115
#define TMC9660_PARAM_TORQUE_PI_ERROR                                 116
#define TMC9660_PARAM_FLUX_PI_ERROR                                   117
#define TMC9660_PARAM_TORQUE_PI_INTEGRATOR                            118
#define TMC9660_PARAM_FLUX_PI_INTEGRATOR                              119
#define TMC9660_PARAM_FLUX_OFFSET                                     120
#define TMC9660_PARAM_VELOCITY_SENSOR_SELECTION                       123
#define TMC9660_PARAM_TARGET_VELOCITY                                 124
#define TMC9660_PARAM_ACTUAL_VELOCITY                                 125
#define TMC9660_PARAM_VELOCITY_OFFSET                                 126
#define TMC9660_PARAM_VELOCITY_P                                      127
#define TMC9660_PARAM_VELOCITY_I                                      128
#define TMC9660_PARAM_VELOCITY_NORM_P                                 129
#define TMC9660_PARAM_VELOCITY_NORM_I                                 130
#define TMC9660_PARAM_VELOCITY_PI_INTEGRATOR                          131
#define TMC9660_PARAM_VELOCITY_PI_ERROR                               132
#define TMC9660_PARAM_VELOCITY_SCALING_FACTOR                         133
#define TMC9660_PARAM_STOP_ON_VELOCITY_DEVIATION                      134
#define TMC9660_PARAM_VELOCITY_LOOP_DOWNSAMPLING                      135
#define TMC9660_PARAM_VELOCITY_REACHED_THRESHOLD                      136
#define TMC9660_PARAM_VELOCITY_METER_SWITCH_THRESHOLD                 137
#define TMC9660_PARAM_VELOCITY_METER_SWITCH_HYSTERESIS                138
#define TMC9660_PARAM_VELOCITY_METER_MODE                             139
#define TMC9660_PARAM_POSITION_SENSOR_SELECTION                       142
#define TMC9660_PARAM_TARGET_POSITION                                 143
#define TMC9660_PARAM_ACTUAL_POSITION                                 144
#define TMC9660_PARAM_POSITION_SCALING_FACTOR                         145
#define TMC9660_PARAM_POSITION_P                                      146
#define TMC9660_PARAM_POSITION_I                                      147
#define TMC9660_PARAM_POSITION_NORM_P                                 148
#define TMC9660_PARAM_POSITION_NORM_I                                 149
#define TMC9660_PARAM_POSITION_PI_INTEGRATOR                          150
#define TMC9660_PARAM_POSITION_PI_ERROR                               151
#define TMC9660_PARAM_STOP_ON_POSITION_DEVIATION                      152
#define TMC9660_PARAM_POSITION_LOOP_DOWNSAMPLING                      153
#define TMC9660_PARAM_LATCH_POSITION                                  154
#define TMC9660_PARAM_POSITION_LIMIT_LOW                              155
#define TMC9660_PARAM_POSITION_LIMIT_HIGH                             156
#define TMC9660_PARAM_POSITION_REACHED_THRESHOLD                      157
#define TMC9660_PARAM_REFERENCE_SWITCH_ENABLE                         161
#define TMC9660_PARAM_REFERENCE_SWITCH_POLARITY_AND_SWAP              162
#define TMC9660_PARAM_REFERENCE_SWITCH_LATCH_SETTINGS                 163
#define TMC9660_PARAM_EVENT_STOP_SETTINGS                             164
#define TMC9660_PARAM_REFERENCE_SWITCH_SEARCH_MODE                    165
#define TMC9660_PARAM_REFERENCE_SWITCH_SEARCH_SPEED                   166
#define TMC9660_PARAM_REFERENCE_SWITCH_SPEED                          167
#define TMC9660_PARAM_RIGHT_LIMIT_SWITCH_POSITION                     168
#define TMC9660_PARAM_HOME_SWITCH_POSITION                            169
#define TMC9660_PARAM_LAST_REFERENCE_POSITION                         170
#define TMC9660_PARAM_ABN_2_STEPS                                     174
#define TMC9660_PARAM_ABN_2_DIRECTION                                 175
#define TMC9660_PARAM_ABN_2_GEAR_RATIO                                176
#define TMC9660_PARAM_ABN_2_ENABLE                                    177
#define TMC9660_PARAM_ABN_2_VALUE                                     178
#define TMC9660_PARAM_SPI_ENCODE_CS_SETTLE_DELAY_TIME                 181
#define TMC9660_PARAM_SPI_ENCODER_CS_IDLE_DELAY_TIME                  182
#define TMC9660_PARAM_SPI_ENCODER_MAIN_TRANSFER_CMD_SIZE              183
#define TMC9660_PARAM_SPI_ENCODER_SECONDARY_TRANSFER_CMD_SIZE         184
#define TMC9660_PARAM_SPI_ENCODER_TRANSFER_DATA_3_0                   185
#define TMC9660_PARAM_SPI_ENCODER_TRANSFER_DATA_7_4                   186
#define TMC9660_PARAM_SPI_ENCODER_TRANSFER_DATA_11_8                  187
#define TMC9660_PARAM_SPI_ENCODER_TRANSFER_DATA_15_12                 188
#define TMC9660_PARAM_SPI_ENCODER_TRANSFER                            189
#define TMC9660_PARAM_SPI_ENCODER_POSITION_COUNTER_MASK               190
#define TMC9660_PARAM_SPI_ENCODER_POSITION_COUNTER_SHIFT              191
#define TMC9660_PARAM_SPI_ENCODER_POSITION_COUNTER_VALUE              192
#define TMC9660_PARAM_SPI_ENCODER_COMMUTATION_ANGLE                   193
#define TMC9660_PARAM_SPI_ENCODER_INITIALIZATION_METHOD               194
#define TMC9660_PARAM_SPI_ENCODER_DIRECTION                           195
#define TMC9660_PARAM_SPI_ENCODER_OFFSET                              196
#define TMC9660_PARAM_SPI_LUT_CORRECTION_ENABLE                       197
#define TMC9660_PARAM_SPI_LUT_ADDRESS_SELECT                          198
#define TMC9660_PARAM_SPI_LUT_DATA                                    199
#define TMC9660_PARAM_SPI_LUT_COMMON_SHIFT_FACTOR                     201
#define TMC9660_PARAM_STEP_DIR_STEP_DIVIDER_SHIFT                     205
#define TMC9660_PARAM_STEP_DIR_ENABLE                                 206
#define TMC9660_PARAM_STEP_DIR_EXTRAPOLATION_ENABLE                   207
#define TMC9660_PARAM_STEP_DIR_STEP_SIGNAL_TIMEOUT_LIMIT              208
#define TMC9660_PARAM_STEP_DIR_MAXIMUM_EXTRAPOLATION_VELOCITY         209
#define TMC9660_PARAM_BRAKE_CHOPPER_ENABLE                            212
#define TMC9660_PARAM_BRAKE_CHOPPER_VOLTAGE_LIMIT                     213
#define TMC9660_PARAM_BRAKE_CHOPPER_HYSTERESIS                        214
#define TMC9660_PARAM_RELEASE_BRAKE                                   216
#define TMC9660_PARAM_BRAKE_RELEASING_DUTY_CYCLE                      217
#define TMC9660_PARAM_BRAKE_HOLDING_DUTY_CYCLE                        218
#define TMC9660_PARAM_BRAKE_RELEASING_DURATION                        219
#define TMC9660_PARAM_INVERT_BRAKE_OUTPUT                             221
#define TMC9660_PARAM_THERMAL_WINDING_TIME_CONSTANT_1                 224
#define TMC9660_PARAM_IIT_LIMIT_1                                     225
#define TMC9660_PARAM_IIT_SUM_1                                       226
#define TMC9660_PARAM_THERMAL_WINDING_TIME_CONSTANT_2                 227
#define TMC9660_PARAM_IIT_LIMIT_2                                     228
#define TMC9660_PARAM_IIT_SUM_2                                       229
#define TMC9660_PARAM_RESET_IIT_SUMS                                  230
#define TMC9660_PARAM_ACTUAL_TOTAL_MOTOR_CURRENT                      231
#define TMC9660_PARAM_BREAK_BEFORE_MAKE_TIME_LOW_UVW                  235
#define TMC9660_PARAM_BREAK_BEFORE_MAKE_TIME_HIGH_UVW                 236
#define TMC9660_PARAM_BREAK_BEFORE_MAKE_TIME_LOW_Y2                   237
#define TMC9660_PARAM_BREAK_BEFORE_MAKE_TIME_HIGH_Y2                  238
#define TMC9660_PARAM_USE_ADAPTIVE_DRIVE_TIME_UVW                     239
#define TMC9660_PARAM_USE_ADAPTIVE_DRIVE_TIME_Y2                      240
#define TMC9660_PARAM_DRIVE_TIME_SINK_UVW                             241
#define TMC9660_PARAM_DRIVE_TIME_SOURCE_UVW                           242
#define TMC9660_PARAM_DRIVE_TIME_SINK_Y2                              243
#define TMC9660_PARAM_DRIVE_TIME_SOURCE_Y2                            244
#define TMC9660_PARAM_UVW_SINK_CURRENT                                245
#define TMC9660_PARAM_UVW_SOURCE_CURRENT                              246
#define TMC9660_PARAM_Y2_SINK_CURRENT                                 247
#define TMC9660_PARAM_Y2_SOURCE_CURRENT                               248
#define TMC9660_PARAM_BOOTSTRAP_CURRENT_LIMIT                         249
#define TMC9660_PARAM_UNDERVOLTAGE_PROTECTION_SUPPLY_LEVEL            250
#define TMC9660_PARAM_UNDERVOLTAGE_PROTECTION_VDRV_ENABLE             251
#define TMC9660_PARAM_UNDERVOLTAGE_PROTECTION_BST_UVW_ENABLE          252
#define TMC9660_PARAM_UNDERVOLTAGE_PROTECTION_BST_Y2_ENABLE           253
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_LOW_SIDE_ENABLE      254
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_HIGH_SIDE_ENABLE     255
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_LOW_SIDE_ENABLE       256
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_HIGH_SIDE_ENABLE      257
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_LOW_SIDE_THRESHOLD   258
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_HIGH_SIDE_THRESHOLD  259
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_LOW_SIDE_THRESHOLD    260
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_HIGH_SIDE_THRESHOLD   261
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_LOW_SIDE_BLANKING    262
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_HIGH_SIDE_BLANKING   263
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_LOW_SIDE_BLANKING     264
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_HIGH_SIDE_BLANKING    265
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_LOW_SIDE_DEGLITCH    266
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_HIGH_SIDE_DEGLITCH   267
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_LOW_SIDE_DEGLITCH     268
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_HIGH_SIDE_DEGLITCH    269
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_UVW_LOW_SIDE_USE_VDS     270
#define TMC9660_PARAM_OVERCURRENT_PROTECTION_Y2_LOW_SIDE_USE_VDS      271
#define TMC9660_PARAM_VGS_SHORT_ON_PROTECTION_UVW_LOW_SIDE_ENABLE     272
#define TMC9660_PARAM_VGS_SHORT_OFF_PROTECTION_UVW_LOW_SIDE_ENABLE    273
#define TMC9660_PARAM_VGS_SHORT_ON_PROTECTION_UVW_HIGH_SIDE_ENABLE    274
#define TMC9660_PARAM_VGS_SHORT_OFF_PROTECTION_UVW_HIGH_SIDE_ENABLE   275
#define TMC9660_PARAM_VGS_SHORT_ON_PROTECTION_Y2_LOW_SIDE_ENABLE      276
#define TMC9660_PARAM_VGS_SHORT_OFF_PROTECTION_Y2_LOW_SIDE_ENABLE     277
#define TMC9660_PARAM_VGS_SHORT_ON_PROTECTION_Y2_HIGH_SIDE_ENABLE     278
#define TMC9660_PARAM_VGS_SHORT_OFF_PROTECTION_Y2_HIGH_SIDE_ENABLE    279
#define TMC9660_PARAM_VGS_SHORT_PROTECTION_UVW_BLANKING               280
#define TMC9660_PARAM_VGS_SHORT_PROTECTION_Y2_BLANKING                281
#define TMC9660_PARAM_VGS_SHORT_PROTECTION_UVW_DEGLITCH               282
#define TMC9660_PARAM_VGS_SHORT_PROTECTION_Y2_DEGLITCH                283
#define TMC9660_PARAM_GDRV_RETRY_BEHAVIOUR                            286
#define TMC9660_PARAM_DRIVE_FAULT_BEHAVIOUR                           287
#define TMC9660_PARAM_FAULT_HANDLER_NUMBER_OF_RETRIES                 288
#define TMC9660_PARAM_GENERAL_STATUS_FLAGS                            289
#define TMC9660_PARAM_SUPPLY_VOLTAGE                                  290
#define TMC9660_PARAM_SUPPLY_OVERVOLTAGE_WARNING_THRESHOLD            291
#define TMC9660_PARAM_SUPPLY_UNDERVOLTAGE_WARNING_THRESHOLD           292
#define TMC9660_PARAM_EXTERNAL_TEMPERATURE                            293
#define TMC9660_PARAM_EXTERNAL_TEMPERATURE_SHUTDOWN_THRESHOLD         294
#define TMC9660_PARAM_EXTERNAL_TEMPERATURE_WARNING_THRESHOLD          295
#define TMC9660_PARAM_CHIP_TEMPERATURE                                296
#define TMC9660_PARAM_CHIP_TEMPERATURE_SHUTDOWN_THRESHOLD             297
#define TMC9660_PARAM_CHIP_TEMPERATURE_WARNING_THRESHOLD              298
#define TMC9660_PARAM_GENERAL_ERROR_FLAGS                             299
#define TMC9660_PARAM_GDRV_ERROR_FLAGS                                300
#define TMC9660_PARAM_ADC_STATUS_FLAGS                                301
#define TMC9660_PARAM_MCC_INPUTS_RAW                                  304
#define TMC9660_PARAM_FOC_VOLTAGE_UX                                  305
#define TMC9660_PARAM_FOC_VOLTAGE_WY                                  306
#define TMC9660_PARAM_FOC_VOLTAGE_V                                   307
#define TMC9660_PARAM_FIELDWEAKENING_I                                308
#define TMC9660_PARAM_FIELDWEAKENING_VOLTAGE_THRESHOLD                310
#define TMC9660_PARAM_FOC_CURRENT_UX                                  311
#define TMC9660_PARAM_FOC_CURRENT_V                                   312
#define TMC9660_PARAM_FOC_CURRENT_WY                                  313
#define TMC9660_PARAM_FOC_VOLTAGE_UQ                                  314
#define TMC9660_PARAM_FOC_CURRENT_IQ                                  315
#define TMC9660_PARAM_TARGET_TORQUE_BIQUAD_FILTER_ENABLE              318
#define TMC9660_PARAM_TARGET_TORQUE_BIQUAD_FILTER_ACOEFF_1            319
#define TMC9660_PARAM_TARGET_TORQUE_BIQUAD_FILTER_ACOEFF_2            320
#define TMC9660_PARAM_TARGET_TORQUE_BIQUAD_FILTER_BCOEFF_0            321
#define TMC9660_PARAM_TARGET_TORQUE_BIQUAD_FILTER_BCOEFF_1            322
#define TMC9660_PARAM_TARGET_TORQUE_BIQUAD_FILTER_BCOEFF_2            323
#define TMC9660_PARAM_ACTUAL_VELOCITY_BIQUAD_FILTER_ENABLE            324
#define TMC9660_PARAM_ACTUAL_VELOCITY_BIQUAD_FILTER_ACOEFF_1          325
#define TMC9660_PARAM_ACTUAL_VELOCITY_BIQUAD_FILTER_ACOEFF_2          326
#define TMC9660_PARAM_ACTUAL_VELOCITY_BIQUAD_FILTER_BCOEFF_0          327
#define TMC9660_PARAM_ACTUAL_VELOCITY_BIQUAD_FILTER_BCOEFF_1          328
#define TMC9660_PARAM_ACTUAL_VELOCITY_BIQUAD_FILTER_BCOEFF_2          329
#define TMC9660_PARAM_TORQUE_FLUX_COMBINED_TARGET_VALUES              330
#define TMC9660_PARAM_TORQUE_FLUX_COMBINED_ACTUAL_VALUES              331
#define TMC9660_PARAM_VOLTAGE_D_Q_COMBINED_ACTUAL_VALUES              332
#define TMC9660_PARAM_INTEGRATED_ACTUAL_TORQUE_VALUE                  333
#define TMC9660_PARAM_INTEGRATED_ACTUAL_VELOCITY_VALUE                334

#endif /* TMC9660_PARAM_HW_ABSTRACTION_H_ */
