/*******************************************************************************
* Copyright © 2017 TRINAMIC Motion Control GmbH & Co. KG
* (now owned by Analog Devices Inc.),
*
* Copyright © 2024 Analog Devices Inc. All Rights Reserved. This software is
* proprietary & confidential to Analog Devices, Inc. and its licensors.
*******************************************************************************/


// Autogenerated C header for registers in TMC5262
// Generator version: 1.0

#ifndef TMC5262_REGISTERS
#define TMC5262_REGISTERS

#define TMC5262_GCONF                      0x00
#define TMC5262_GSTAT                      0x01
#define TMC5262_DIAG_CONF                  0x02
#define TMC5262_DIAG_DAC_CONF              0x03
#define TMC5262_IOIN                       0x04
#define TMC5262_X_COMPARE                  0x05
#define TMC5262_X_COMPARE_REPEAT           0x06
#define TMC5262_DRV_CONF                   0x0A
#define TMC5262_PLL                        0x0B
#define TMC5262_IHOLD_IRUN                 0x10
#define TMC5262_TPOWERDOWN                 0x11
#define TMC5262_TSTEP                      0x12
#define TMC5262_TPWMTHRS                   0x13
#define TMC5262_TCOOLTHRS                  0x14
#define TMC5262_THIGH                      0x15
#define TMC5262_TSGP_LOW_VEL_THRS          0x16
#define TMC5262_T_RCOIL_MEAS               0x17
#define TMC5262_TUDCSTEP                   0x18
#define TMC5262_UDC_CONF                   0x19
#define TMC5262_STEPS_LOST                 0x1A
#define TMC5262_RAMPMODE                   0x20
#define TMC5262_XACTUAL                    0x21
#define TMC5262_VACTUAL                    0x22
#define TMC5262_VSTART                     0x23
#define TMC5262_A1                         0x24
#define TMC5262_V1                         0x25
#define TMC5262_AMAX                       0x26
#define TMC5262_VMAX                       0x27
#define TMC5262_DMAX                       0x28
#define TMC5262_TVMAX                      0x29
#define TMC5262_D1                         0x2A
#define TMC5262_VSTOP                      0x2B
#define TMC5262_TZEROWAIT                  0x2C
#define TMC5262_XTARGET                    0x2D
#define TMC5262_V2                         0x2E
#define TMC5262_A2                         0x2F
#define TMC5262_D2                         0x30
#define TMC5262_AACTUAL                    0x31
#define TMC5262_SW_MODE                    0x34
#define TMC5262_RAMP_STAT                  0x35
#define TMC5262_XLATCH                     0x36
#define TMC5262_ENCMODE                    0x38
#define TMC5262_X_ENC                      0x39
#define TMC5262_ENC_CONST                  0x3A
#define TMC5262_ENC_STATUS                 0x3B
#define TMC5262_ENC_LATCH                  0x3C
#define TMC5262_ENC_DEVIATION              0x3D
#define TMC5262_VIRTUAL_STOP_L             0x3E
#define TMC5262_VIRTUAL_STOP_R             0x3F
#define TMC5262_CURRENT_PI_REG             0x40
#define TMC5262_ANGLE_PI_REG               0x41
#define TMC5262_CUR_ANGLE_LIMIT            0x42
#define TMC5262_ANGLE_LOWER_LIMIT          0x43
#define TMC5262_CUR_ANGLE_MEAS             0x44
#define TMC5262_PI_RESULTS                 0x45
#define TMC5262_COIL_INDUCT                0x46
#define TMC5262_R_COIL                     0x47
#define TMC5262_R_COIL_USER                0x48
#define TMC5262_SGP_CONF                   0x49
#define TMC5262_SGP_IND_2_3                0x4A
#define TMC5262_SGP_IND_0_1                0x4B
#define TMC5262_INDUCTANCE_VOLTAGE         0x4C
#define TMC5262_SGP_BEMF                   0x4D
#define TMC5262_COOLSTEPPLUS_CONF          0x4E
#define TMC5262_COOLSTEPPLUS_PI_REG        0x4F
#define TMC5262_COOLSTEPPLUS_PI_DOWN       0x50
#define TMC5262_COOLSTEPPLUS_RESERVE_CONF  0x51
#define TMC5262_COOLSTEPPLUS_LOAD_RESERVE  0x52
#define TMC5262_TSTEP_VELOCITY             0x53
#define TMC5262_ADC_VSUPPLY_TEMP           0x58
#define TMC5262_ADC_I                      0x59
#define TMC5262_OTW_OV_VTH                 0x5A
#define TMC5262_MSLUT_0                    0x60
#define TMC5262_MSLUT_1                    0x61
#define TMC5262_MSLUT_2                    0x62
#define TMC5262_MSLUT_3                    0x63
#define TMC5262_MSLUT_4                    0x64
#define TMC5262_MSLUT_5                    0x65
#define TMC5262_MSLUT_6                    0x66
#define TMC5262_MSLUT_7                    0x67
#define TMC5262_MSLUTSEL                   0x68
#define TMC5262_MSLUTSTART                 0x69
#define TMC5262_MSCNT                      0x6A
#define TMC5262_MSCURACT                   0x6B
#define TMC5262_CHOPCONF                   0x6C
#define TMC5262_COOLCONF                   0x6D
#define TMC5262_DRV_STATUS                 0x6F
#define TMC5262_PWMCONF                    0x70

#endif
