// Autogenerated C header for register fields in TMC2130
// Generator version: 1.0

#ifndef TMC2130_FIELDS
#define TMC2130_FIELDS

typedef struct
{
	uint32_t mask;
	uint8_t shift;
	uint8_t address;
} RegisterField;

#define TMC2130_I_SCALE_ANALOG_MASK           0x00000001
#define TMC2130_I_SCALE_ANALOG_SHIFT          0
#define TMC2130_I_SCALE_ANALOG_FIELD          ((RegisterField) { 0x00000001, 0, 0x00 })
#define TMC2130_INTERNAL_RSENSE_MASK          0x00000002
#define TMC2130_INTERNAL_RSENSE_SHIFT         1
#define TMC2130_INTERNAL_RSENSE_FIELD         ((RegisterField) { 0x00000002, 1, 0x00 })
#define TMC2130_EN_PWM_MODE_MASK              0x00000004
#define TMC2130_EN_PWM_MODE_SHIFT             2
#define TMC2130_EN_PWM_MODE_FIELD             ((RegisterField) { 0x00000004, 2, 0x00 })
#define TMC2130_ENC_COMMUTATION_MASK          0x00000008
#define TMC2130_ENC_COMMUTATION_SHIFT         3
#define TMC2130_ENC_COMMUTATION_FIELD         ((RegisterField) { 0x00000008, 3, 0x00 })
#define TMC2130_SHAFT_MASK                    0x00000010
#define TMC2130_SHAFT_SHIFT                   4
#define TMC2130_SHAFT_FIELD                   ((RegisterField) { 0x00000010, 4, 0x00 })
#define TMC2130_DIAG0_ERROR_MASK              0x00000020
#define TMC2130_DIAG0_ERROR_SHIFT             5
#define TMC2130_DIAG0_ERROR_FIELD             ((RegisterField) { 0x00000020, 5, 0x00 })
#define TMC2130_DIAG0_OTPW_MASK               0x00000040
#define TMC2130_DIAG0_OTPW_SHIFT              6
#define TMC2130_DIAG0_OTPW_FIELD              ((RegisterField) { 0x00000040, 6, 0x00 })
#define TMC2130_DIAG0_STALL_MASK              0x00000080
#define TMC2130_DIAG0_STALL_SHIFT             7
#define TMC2130_DIAG0_STALL_FIELD             ((RegisterField) { 0x00000080, 7, 0x00 })
#define TMC2130_DIAG1_STALL_MASK              0x00000100
#define TMC2130_DIAG1_STALL_SHIFT             8
#define TMC2130_DIAG1_STALL_FIELD             ((RegisterField) { 0x00000100, 8, 0x00 })
#define TMC2130_DIAG1_INDEX_MASK              0x00000200
#define TMC2130_DIAG1_INDEX_SHIFT             9
#define TMC2130_DIAG1_INDEX_FIELD             ((RegisterField) { 0x00000200, 9, 0x00 })
#define TMC2130_DIAG1_ONSTATE_MASK            0x00000400
#define TMC2130_DIAG1_ONSTATE_SHIFT           10
#define TMC2130_DIAG1_ONSTATE_FIELD           ((RegisterField) { 0x00000400, 10, 0x00 })
#define TMC2130_DIAG1_STEPS_SKIPPED_MASK      0x00000800
#define TMC2130_DIAG1_STEPS_SKIPPED_SHIFT     11
#define TMC2130_DIAG1_STEPS_SKIPPED_FIELD     ((RegisterField) { 0x00000800, 11, 0x00 })
#define TMC2130_DIAG0_INT_PUSHPULL_MASK       0x00001000
#define TMC2130_DIAG0_INT_PUSHPULL_SHIFT      12
#define TMC2130_DIAG0_INT_PUSHPULL_FIELD      ((RegisterField) { 0x00001000, 12, 0x00 })
#define TMC2130_DIAG1_POSCOMP_PUSHPULL_MASK   0x00002000
#define TMC2130_DIAG1_POSCOMP_PUSHPULL_SHIFT  13
#define TMC2130_DIAG1_POSCOMP_PUSHPULL_FIELD  ((RegisterField) { 0x00002000, 13, 0x00 })
#define TMC2130_SMALL_HYSTERESIS_MASK         0x00004000
#define TMC2130_SMALL_HYSTERESIS_SHIFT        14
#define TMC2130_SMALL_HYSTERESIS_FIELD        ((RegisterField) { 0x00004000, 14, 0x00 })
#define TMC2130_STOP_ENABLE_MASK              0x00008000
#define TMC2130_STOP_ENABLE_SHIFT             15
#define TMC2130_STOP_ENABLE_FIELD             ((RegisterField) { 0x00008000, 15, 0x00 })
#define TMC2130_DIRECT_MODE_MASK              0x00010000
#define TMC2130_DIRECT_MODE_SHIFT             16
#define TMC2130_DIRECT_MODE_FIELD             ((RegisterField) { 0x00010000, 16, 0x00 })
#define TMC2130_TEST_MODE_MASK                0x00020000
#define TMC2130_TEST_MODE_SHIFT               17
#define TMC2130_TEST_MODE_FIELD               ((RegisterField) { 0x00020000, 17, 0x00 })
#define TMC2130_RESET_MASK                    0x00000001
#define TMC2130_RESET_SHIFT                   0
#define TMC2130_RESET_FIELD                   ((RegisterField) { 0x00000001, 0, 0x01 })
#define TMC2130_DRV_ERR_MASK                  0x00000002
#define TMC2130_DRV_ERR_SHIFT                 1
#define TMC2130_DRV_ERR_FIELD                 ((RegisterField) { 0x00000002, 1, 0x01 })
#define TMC2130_UV_CP_MASK                    0x00000004
#define TMC2130_UV_CP_SHIFT                   2
#define TMC2130_UV_CP_FIELD                   ((RegisterField) { 0x00000004, 2, 0x01 })
#define TMC2130_REFL_STEP_MASK                0x00000001
#define TMC2130_REFL_STEP_SHIFT               0
#define TMC2130_REFL_STEP_FIELD               ((RegisterField) { 0x00000001, 0, 0x04 })
#define TMC2130_REFR_DIR_MASK                 0x00000002
#define TMC2130_REFR_DIR_SHIFT                1
#define TMC2130_REFR_DIR_FIELD                ((RegisterField) { 0x00000002, 1, 0x04 })
#define TMC2130_ENCB_DCEN_CFG4_MASK           0x00000004
#define TMC2130_ENCB_DCEN_CFG4_SHIFT          2
#define TMC2130_ENCB_DCEN_CFG4_FIELD          ((RegisterField) { 0x00000004, 2, 0x04 })
#define TMC2130_ENCA_DCIN_CFG5_MASK           0x00000008
#define TMC2130_ENCA_DCIN_CFG5_SHIFT          3
#define TMC2130_ENCA_DCIN_CFG5_FIELD          ((RegisterField) { 0x00000008, 3, 0x04 })
#define TMC2130_DRV_ENN_CFG6_MASK             0x00000010
#define TMC2130_DRV_ENN_CFG6_SHIFT            4
#define TMC2130_DRV_ENN_CFG6_FIELD            ((RegisterField) { 0x00000010, 4, 0x04 })
#define TMC2130_ENC_N_DCO_MASK                0x00000020
#define TMC2130_ENC_N_DCO_SHIFT               5
#define TMC2130_ENC_N_DCO_FIELD               ((RegisterField) { 0x00000020, 5, 0x04 })
#define TMC2130_VERSION_MASK                  0xFF000000
#define TMC2130_VERSION_SHIFT                 24
#define TMC2130_VERSION_FIELD                 ((RegisterField) { 0xFF000000, 24, 0x04 })
#define TMC2130_IHOLD_MASK                    0x0000001F
#define TMC2130_IHOLD_SHIFT                   0
#define TMC2130_IHOLD_FIELD                   ((RegisterField) { 0x0000001F, 0, 0x10 })
#define TMC2130_IRUN_MASK                     0x00001F00
#define TMC2130_IRUN_SHIFT                    8
#define TMC2130_IRUN_FIELD                    ((RegisterField) { 0x00001F00, 8, 0x10 })
#define TMC2130_IHOLDDELAY_MASK               0x000F0000
#define TMC2130_IHOLDDELAY_SHIFT              16
#define TMC2130_IHOLDDELAY_FIELD              ((RegisterField) { 0x000F0000, 16, 0x10 })
#define TMC2130_TPOWERDOWN_MASK               0x000000FF
#define TMC2130_TPOWERDOWN_SHIFT              0
#define TMC2130_TPOWERDOWN_FIELD              ((RegisterField) { 0x000000FF, 0, 0x11 })
#define TMC2130_TSTEP_MASK                    0x000FFFFF
#define TMC2130_TSTEP_SHIFT                   0
#define TMC2130_TSTEP_FIELD                   ((RegisterField) { 0x000FFFFF, 0, 0x12 })
#define TMC2130_TPWMTHRS_MASK                 0x000FFFFF
#define TMC2130_TPWMTHRS_SHIFT                0
#define TMC2130_TPWMTHRS_FIELD                ((RegisterField) { 0x000FFFFF, 0, 0x13 })
#define TMC2130_TCOOLTHRS_MASK                0x000FFFFF
#define TMC2130_TCOOLTHRS_SHIFT               0
#define TMC2130_TCOOLTHRS_FIELD               ((RegisterField) { 0x000FFFFF, 0, 0x14 })
#define TMC2130_THIGH_MASK                    0x000FFFFF
#define TMC2130_THIGH_SHIFT                   0
#define TMC2130_THIGH_FIELD                   ((RegisterField) { 0x000FFFFF, 0, 0x15 })
#define TMC2130_DIRECT_CURRENT_A_MASK         0x000000FF
#define TMC2130_DIRECT_CURRENT_A_SHIFT        0
#define TMC2130_DIRECT_CURRENT_A_FIELD        ((RegisterField) { 0x000000FF, 0, 0x2D })
#define TMC2130_DIRECT_CURRENT_B_MASK         0x00FF0000
#define TMC2130_DIRECT_CURRENT_B_SHIFT        16
#define TMC2130_DIRECT_CURRENT_B_FIELD        ((RegisterField) { 0x00FF0000, 16, 0x2D })
#define TMC2130_VDCMIN_MASK                   0x07FFFFFF
#define TMC2130_VDCMIN_SHIFT                  0
#define TMC2130_VDCMIN_FIELD                  ((RegisterField) { 0x07FFFFFF, 0, 0x33 })
#define TMC2130_OFS0_MASK                     0x00000001
#define TMC2130_OFS0_SHIFT                    0
#define TMC2130_OFS0_FIELD                    ((RegisterField) { 0x00000001, 0, 0x60 })
#define TMC2130_OFS1_MASK                     0x00000002
#define TMC2130_OFS1_SHIFT                    1
#define TMC2130_OFS1_FIELD                    ((RegisterField) { 0x00000002, 1, 0x60 })
#define TMC2130_OFS2_MASK                     0x00000004
#define TMC2130_OFS2_SHIFT                    2
#define TMC2130_OFS2_FIELD                    ((RegisterField) { 0x00000004, 2, 0x60 })
#define TMC2130_OFS3_MASK                     0x00000008
#define TMC2130_OFS3_SHIFT                    3
#define TMC2130_OFS3_FIELD                    ((RegisterField) { 0x00000008, 3, 0x60 })
#define TMC2130_OFS4_MASK                     0x00000010
#define TMC2130_OFS4_SHIFT                    4
#define TMC2130_OFS4_FIELD                    ((RegisterField) { 0x00000010, 4, 0x60 })
#define TMC2130_OFS5_MASK                     0x00000020
#define TMC2130_OFS5_SHIFT                    5
#define TMC2130_OFS5_FIELD                    ((RegisterField) { 0x00000020, 5, 0x60 })
#define TMC2130_OFS6_MASK                     0x00000040
#define TMC2130_OFS6_SHIFT                    6
#define TMC2130_OFS6_FIELD                    ((RegisterField) { 0x00000040, 6, 0x60 })
#define TMC2130_OFS7_MASK                     0x00000080
#define TMC2130_OFS7_SHIFT                    7
#define TMC2130_OFS7_FIELD                    ((RegisterField) { 0x00000080, 7, 0x60 })
#define TMC2130_OFS8_MASK                     0x00000100
#define TMC2130_OFS8_SHIFT                    8
#define TMC2130_OFS8_FIELD                    ((RegisterField) { 0x00000100, 8, 0x60 })
#define TMC2130_OFS9_MASK                     0x00000200
#define TMC2130_OFS9_SHIFT                    9
#define TMC2130_OFS9_FIELD                    ((RegisterField) { 0x00000200, 9, 0x60 })
#define TMC2130_OFS10_MASK                    0x00000400
#define TMC2130_OFS10_SHIFT                   10
#define TMC2130_OFS10_FIELD                   ((RegisterField) { 0x00000400, 10, 0x60 })
#define TMC2130_OFS11_MASK                    0x00000800
#define TMC2130_OFS11_SHIFT                   11
#define TMC2130_OFS11_FIELD                   ((RegisterField) { 0x00000800, 11, 0x60 })
#define TMC2130_OFS12_MASK                    0x00001000
#define TMC2130_OFS12_SHIFT                   12
#define TMC2130_OFS12_FIELD                   ((RegisterField) { 0x00001000, 12, 0x60 })
#define TMC2130_OFS13_MASK                    0x00002000
#define TMC2130_OFS13_SHIFT                   13
#define TMC2130_OFS13_FIELD                   ((RegisterField) { 0x00002000, 13, 0x60 })
#define TMC2130_OFS14_MASK                    0x00004000
#define TMC2130_OFS14_SHIFT                   14
#define TMC2130_OFS14_FIELD                   ((RegisterField) { 0x00004000, 14, 0x60 })
#define TMC2130_OFS15_MASK                    0x00008000
#define TMC2130_OFS15_SHIFT                   15
#define TMC2130_OFS15_FIELD                   ((RegisterField) { 0x00008000, 15, 0x60 })
#define TMC2130_OFS16_MASK                    0x00010000
#define TMC2130_OFS16_SHIFT                   16
#define TMC2130_OFS16_FIELD                   ((RegisterField) { 0x00010000, 16, 0x60 })
#define TMC2130_OFS17_MASK                    0x00020000
#define TMC2130_OFS17_SHIFT                   17
#define TMC2130_OFS17_FIELD                   ((RegisterField) { 0x00020000, 17, 0x60 })
#define TMC2130_OFS18_MASK                    0x00040000
#define TMC2130_OFS18_SHIFT                   18
#define TMC2130_OFS18_FIELD                   ((RegisterField) { 0x00040000, 18, 0x60 })
#define TMC2130_OFS19_MASK                    0x00080000
#define TMC2130_OFS19_SHIFT                   19
#define TMC2130_OFS19_FIELD                   ((RegisterField) { 0x00080000, 19, 0x60 })
#define TMC2130_OFS20_MASK                    0x00100000
#define TMC2130_OFS20_SHIFT                   20
#define TMC2130_OFS20_FIELD                   ((RegisterField) { 0x00100000, 20, 0x60 })
#define TMC2130_OFS21_MASK                    0x00200000
#define TMC2130_OFS21_SHIFT                   21
#define TMC2130_OFS21_FIELD                   ((RegisterField) { 0x00200000, 21, 0x60 })
#define TMC2130_OFS22_MASK                    0x00400000
#define TMC2130_OFS22_SHIFT                   22
#define TMC2130_OFS22_FIELD                   ((RegisterField) { 0x00400000, 22, 0x60 })
#define TMC2130_OFS23_MASK                    0x00800000
#define TMC2130_OFS23_SHIFT                   23
#define TMC2130_OFS23_FIELD                   ((RegisterField) { 0x00800000, 23, 0x60 })
#define TMC2130_OFS24_MASK                    0x01000000
#define TMC2130_OFS24_SHIFT                   24
#define TMC2130_OFS24_FIELD                   ((RegisterField) { 0x01000000, 24, 0x60 })
#define TMC2130_OFS25_MASK                    0x02000000
#define TMC2130_OFS25_SHIFT                   25
#define TMC2130_OFS25_FIELD                   ((RegisterField) { 0x02000000, 25, 0x60 })
#define TMC2130_OFS26_MASK                    0x04000000
#define TMC2130_OFS26_SHIFT                   26
#define TMC2130_OFS26_FIELD                   ((RegisterField) { 0x04000000, 26, 0x60 })
#define TMC2130_OFS27_MASK                    0x08000000
#define TMC2130_OFS27_SHIFT                   27
#define TMC2130_OFS27_FIELD                   ((RegisterField) { 0x08000000, 27, 0x60 })
#define TMC2130_OFS28_MASK                    0x10000000
#define TMC2130_OFS28_SHIFT                   28
#define TMC2130_OFS28_FIELD                   ((RegisterField) { 0x10000000, 28, 0x60 })
#define TMC2130_OFS29_MASK                    0x20000000
#define TMC2130_OFS29_SHIFT                   29
#define TMC2130_OFS29_FIELD                   ((RegisterField) { 0x20000000, 29, 0x60 })
#define TMC2130_OFS30_MASK                    0x40000000
#define TMC2130_OFS30_SHIFT                   30
#define TMC2130_OFS30_FIELD                   ((RegisterField) { 0x40000000, 30, 0x60 })
#define TMC2130_OFS31_MASK                    0x80000000
#define TMC2130_OFS31_SHIFT                   31
#define TMC2130_OFS31_FIELD                   ((RegisterField) { 0x80000000, 31, 0x60 })
#define TMC2130_OFS32_MASK                    0x00000001
#define TMC2130_OFS32_SHIFT                   0
#define TMC2130_OFS32_FIELD                   ((RegisterField) { 0x00000001, 0, 0x61 })
#define TMC2130_OFS33_MASK                    0x00000002
#define TMC2130_OFS33_SHIFT                   1
#define TMC2130_OFS33_FIELD                   ((RegisterField) { 0x00000002, 1, 0x61 })
#define TMC2130_OFS34_MASK                    0x00000004
#define TMC2130_OFS34_SHIFT                   2
#define TMC2130_OFS34_FIELD                   ((RegisterField) { 0x00000004, 2, 0x61 })
#define TMC2130_OFS35_MASK                    0x00000008
#define TMC2130_OFS35_SHIFT                   3
#define TMC2130_OFS35_FIELD                   ((RegisterField) { 0x00000008, 3, 0x61 })
#define TMC2130_OFS36_MASK                    0x00000010
#define TMC2130_OFS36_SHIFT                   4
#define TMC2130_OFS36_FIELD                   ((RegisterField) { 0x00000010, 4, 0x61 })
#define TMC2130_OFS37_MASK                    0x00000020
#define TMC2130_OFS37_SHIFT                   5
#define TMC2130_OFS37_FIELD                   ((RegisterField) { 0x00000020, 5, 0x61 })
#define TMC2130_OFS38_MASK                    0x00000040
#define TMC2130_OFS38_SHIFT                   6
#define TMC2130_OFS38_FIELD                   ((RegisterField) { 0x00000040, 6, 0x61 })
#define TMC2130_OFS39_MASK                    0x00000080
#define TMC2130_OFS39_SHIFT                   7
#define TMC2130_OFS39_FIELD                   ((RegisterField) { 0x00000080, 7, 0x61 })
#define TMC2130_OFS40_MASK                    0x00000100
#define TMC2130_OFS40_SHIFT                   8
#define TMC2130_OFS40_FIELD                   ((RegisterField) { 0x00000100, 8, 0x61 })
#define TMC2130_OFS41_MASK                    0x00000200
#define TMC2130_OFS41_SHIFT                   9
#define TMC2130_OFS41_FIELD                   ((RegisterField) { 0x00000200, 9, 0x61 })
#define TMC2130_OFS42_MASK                    0x00000400
#define TMC2130_OFS42_SHIFT                   10
#define TMC2130_OFS42_FIELD                   ((RegisterField) { 0x00000400, 10, 0x61 })
#define TMC2130_OFS43_MASK                    0x00000800
#define TMC2130_OFS43_SHIFT                   11
#define TMC2130_OFS43_FIELD                   ((RegisterField) { 0x00000800, 11, 0x61 })
#define TMC2130_OFS44_MASK                    0x00001000
#define TMC2130_OFS44_SHIFT                   12
#define TMC2130_OFS44_FIELD                   ((RegisterField) { 0x00001000, 12, 0x61 })
#define TMC2130_OFS45_MASK                    0x00002000
#define TMC2130_OFS45_SHIFT                   13
#define TMC2130_OFS45_FIELD                   ((RegisterField) { 0x00002000, 13, 0x61 })
#define TMC2130_OFS46_MASK                    0x00004000
#define TMC2130_OFS46_SHIFT                   14
#define TMC2130_OFS46_FIELD                   ((RegisterField) { 0x00004000, 14, 0x61 })
#define TMC2130_OFS47_MASK                    0x00008000
#define TMC2130_OFS47_SHIFT                   15
#define TMC2130_OFS47_FIELD                   ((RegisterField) { 0x00008000, 15, 0x61 })
#define TMC2130_OFS48_MASK                    0x00010000
#define TMC2130_OFS48_SHIFT                   16
#define TMC2130_OFS48_FIELD                   ((RegisterField) { 0x00010000, 16, 0x61 })
#define TMC2130_OFS49_MASK                    0x00020000
#define TMC2130_OFS49_SHIFT                   17
#define TMC2130_OFS49_FIELD                   ((RegisterField) { 0x00020000, 17, 0x61 })
#define TMC2130_OFS50_MASK                    0x00040000
#define TMC2130_OFS50_SHIFT                   18
#define TMC2130_OFS50_FIELD                   ((RegisterField) { 0x00040000, 18, 0x61 })
#define TMC2130_OFS51_MASK                    0x00080000
#define TMC2130_OFS51_SHIFT                   19
#define TMC2130_OFS51_FIELD                   ((RegisterField) { 0x00080000, 19, 0x61 })
#define TMC2130_OFS52_MASK                    0x00100000
#define TMC2130_OFS52_SHIFT                   20
#define TMC2130_OFS52_FIELD                   ((RegisterField) { 0x00100000, 20, 0x61 })
#define TMC2130_OFS53_MASK                    0x00200000
#define TMC2130_OFS53_SHIFT                   21
#define TMC2130_OFS53_FIELD                   ((RegisterField) { 0x00200000, 21, 0x61 })
#define TMC2130_OFS54_MASK                    0x00400000
#define TMC2130_OFS54_SHIFT                   22
#define TMC2130_OFS54_FIELD                   ((RegisterField) { 0x00400000, 22, 0x61 })
#define TMC2130_OFS55_MASK                    0x00800000
#define TMC2130_OFS55_SHIFT                   23
#define TMC2130_OFS55_FIELD                   ((RegisterField) { 0x00800000, 23, 0x61 })
#define TMC2130_OFS56_MASK                    0x01000000
#define TMC2130_OFS56_SHIFT                   24
#define TMC2130_OFS56_FIELD                   ((RegisterField) { 0x01000000, 24, 0x61 })
#define TMC2130_OFS57_MASK                    0x02000000
#define TMC2130_OFS57_SHIFT                   25
#define TMC2130_OFS57_FIELD                   ((RegisterField) { 0x02000000, 25, 0x61 })
#define TMC2130_OFS58_MASK                    0x04000000
#define TMC2130_OFS58_SHIFT                   26
#define TMC2130_OFS58_FIELD                   ((RegisterField) { 0x04000000, 26, 0x61 })
#define TMC2130_OFS59_MASK                    0x08000000
#define TMC2130_OFS59_SHIFT                   27
#define TMC2130_OFS59_FIELD                   ((RegisterField) { 0x08000000, 27, 0x61 })
#define TMC2130_OFS60_MASK                    0x10000000
#define TMC2130_OFS60_SHIFT                   28
#define TMC2130_OFS60_FIELD                   ((RegisterField) { 0x10000000, 28, 0x61 })
#define TMC2130_OFS61_MASK                    0x20000000
#define TMC2130_OFS61_SHIFT                   29
#define TMC2130_OFS61_FIELD                   ((RegisterField) { 0x20000000, 29, 0x61 })
#define TMC2130_OFS62_MASK                    0x40000000
#define TMC2130_OFS62_SHIFT                   30
#define TMC2130_OFS62_FIELD                   ((RegisterField) { 0x40000000, 30, 0x61 })
#define TMC2130_OFS63_MASK                    0x80000000
#define TMC2130_OFS63_SHIFT                   31
#define TMC2130_OFS63_FIELD                   ((RegisterField) { 0x80000000, 31, 0x61 })
#define TMC2130_OFS64_MASK                    0x00000001
#define TMC2130_OFS64_SHIFT                   0
#define TMC2130_OFS64_FIELD                   ((RegisterField) { 0x00000001, 0, 0x62 })
#define TMC2130_OFS65_MASK                    0x00000002
#define TMC2130_OFS65_SHIFT                   1
#define TMC2130_OFS65_FIELD                   ((RegisterField) { 0x00000002, 1, 0x62 })
#define TMC2130_OFS66_MASK                    0x00000004
#define TMC2130_OFS66_SHIFT                   2
#define TMC2130_OFS66_FIELD                   ((RegisterField) { 0x00000004, 2, 0x62 })
#define TMC2130_OFS67_MASK                    0x00000008
#define TMC2130_OFS67_SHIFT                   3
#define TMC2130_OFS67_FIELD                   ((RegisterField) { 0x00000008, 3, 0x62 })
#define TMC2130_OFS68_MASK                    0x00000010
#define TMC2130_OFS68_SHIFT                   4
#define TMC2130_OFS68_FIELD                   ((RegisterField) { 0x00000010, 4, 0x62 })
#define TMC2130_OFS69_MASK                    0x00000020
#define TMC2130_OFS69_SHIFT                   5
#define TMC2130_OFS69_FIELD                   ((RegisterField) { 0x00000020, 5, 0x62 })
#define TMC2130_OFS70_MASK                    0x00000040
#define TMC2130_OFS70_SHIFT                   6
#define TMC2130_OFS70_FIELD                   ((RegisterField) { 0x00000040, 6, 0x62 })
#define TMC2130_OFS71_MASK                    0x00000080
#define TMC2130_OFS71_SHIFT                   7
#define TMC2130_OFS71_FIELD                   ((RegisterField) { 0x00000080, 7, 0x62 })
#define TMC2130_OFS72_MASK                    0x00000100
#define TMC2130_OFS72_SHIFT                   8
#define TMC2130_OFS72_FIELD                   ((RegisterField) { 0x00000100, 8, 0x62 })
#define TMC2130_OFS73_MASK                    0x00000200
#define TMC2130_OFS73_SHIFT                   9
#define TMC2130_OFS73_FIELD                   ((RegisterField) { 0x00000200, 9, 0x62 })
#define TMC2130_OFS74_MASK                    0x00000400
#define TMC2130_OFS74_SHIFT                   10
#define TMC2130_OFS74_FIELD                   ((RegisterField) { 0x00000400, 10, 0x62 })
#define TMC2130_OFS75_MASK                    0x00000800
#define TMC2130_OFS75_SHIFT                   11
#define TMC2130_OFS75_FIELD                   ((RegisterField) { 0x00000800, 11, 0x62 })
#define TMC2130_OFS76_MASK                    0x00001000
#define TMC2130_OFS76_SHIFT                   12
#define TMC2130_OFS76_FIELD                   ((RegisterField) { 0x00001000, 12, 0x62 })
#define TMC2130_OFS77_MASK                    0x00002000
#define TMC2130_OFS77_SHIFT                   13
#define TMC2130_OFS77_FIELD                   ((RegisterField) { 0x00002000, 13, 0x62 })
#define TMC2130_OFS78_MASK                    0x00004000
#define TMC2130_OFS78_SHIFT                   14
#define TMC2130_OFS78_FIELD                   ((RegisterField) { 0x00004000, 14, 0x62 })
#define TMC2130_OFS79_MASK                    0x00008000
#define TMC2130_OFS79_SHIFT                   15
#define TMC2130_OFS79_FIELD                   ((RegisterField) { 0x00008000, 15, 0x62 })
#define TMC2130_OFS80_MASK                    0x00010000
#define TMC2130_OFS80_SHIFT                   16
#define TMC2130_OFS80_FIELD                   ((RegisterField) { 0x00010000, 16, 0x62 })
#define TMC2130_OFS81_MASK                    0x00020000
#define TMC2130_OFS81_SHIFT                   17
#define TMC2130_OFS81_FIELD                   ((RegisterField) { 0x00020000, 17, 0x62 })
#define TMC2130_OFS82_MASK                    0x00040000
#define TMC2130_OFS82_SHIFT                   18
#define TMC2130_OFS82_FIELD                   ((RegisterField) { 0x00040000, 18, 0x62 })
#define TMC2130_OFS83_MASK                    0x00080000
#define TMC2130_OFS83_SHIFT                   19
#define TMC2130_OFS83_FIELD                   ((RegisterField) { 0x00080000, 19, 0x62 })
#define TMC2130_OFS84_MASK                    0x00100000
#define TMC2130_OFS84_SHIFT                   20
#define TMC2130_OFS84_FIELD                   ((RegisterField) { 0x00100000, 20, 0x62 })
#define TMC2130_OFS85_MASK                    0x00200000
#define TMC2130_OFS85_SHIFT                   21
#define TMC2130_OFS85_FIELD                   ((RegisterField) { 0x00200000, 21, 0x62 })
#define TMC2130_OFS86_MASK                    0x00400000
#define TMC2130_OFS86_SHIFT                   22
#define TMC2130_OFS86_FIELD                   ((RegisterField) { 0x00400000, 22, 0x62 })
#define TMC2130_OFS87_MASK                    0x00800000
#define TMC2130_OFS87_SHIFT                   23
#define TMC2130_OFS87_FIELD                   ((RegisterField) { 0x00800000, 23, 0x62 })
#define TMC2130_OFS88_MASK                    0x01000000
#define TMC2130_OFS88_SHIFT                   24
#define TMC2130_OFS88_FIELD                   ((RegisterField) { 0x01000000, 24, 0x62 })
#define TMC2130_OFS89_MASK                    0x02000000
#define TMC2130_OFS89_SHIFT                   25
#define TMC2130_OFS89_FIELD                   ((RegisterField) { 0x02000000, 25, 0x62 })
#define TMC2130_OFS90_MASK                    0x04000000
#define TMC2130_OFS90_SHIFT                   26
#define TMC2130_OFS90_FIELD                   ((RegisterField) { 0x04000000, 26, 0x62 })
#define TMC2130_OFS91_MASK                    0x08000000
#define TMC2130_OFS91_SHIFT                   27
#define TMC2130_OFS91_FIELD                   ((RegisterField) { 0x08000000, 27, 0x62 })
#define TMC2130_OFS92_MASK                    0x10000000
#define TMC2130_OFS92_SHIFT                   28
#define TMC2130_OFS92_FIELD                   ((RegisterField) { 0x10000000, 28, 0x62 })
#define TMC2130_OFS93_MASK                    0x20000000
#define TMC2130_OFS93_SHIFT                   29
#define TMC2130_OFS93_FIELD                   ((RegisterField) { 0x20000000, 29, 0x62 })
#define TMC2130_OFS94_MASK                    0x40000000
#define TMC2130_OFS94_SHIFT                   30
#define TMC2130_OFS94_FIELD                   ((RegisterField) { 0x40000000, 30, 0x62 })
#define TMC2130_OFS95_MASK                    0x80000000
#define TMC2130_OFS95_SHIFT                   31
#define TMC2130_OFS95_FIELD                   ((RegisterField) { 0x80000000, 31, 0x62 })
#define TMC2130_OFS96_MASK                    0x00000001
#define TMC2130_OFS96_SHIFT                   0
#define TMC2130_OFS96_FIELD                   ((RegisterField) { 0x00000001, 0, 0x63 })
#define TMC2130_OFS97_MASK                    0x00000002
#define TMC2130_OFS97_SHIFT                   1
#define TMC2130_OFS97_FIELD                   ((RegisterField) { 0x00000002, 1, 0x63 })
#define TMC2130_OFS98_MASK                    0x00000004
#define TMC2130_OFS98_SHIFT                   2
#define TMC2130_OFS98_FIELD                   ((RegisterField) { 0x00000004, 2, 0x63 })
#define TMC2130_OFS99_MASK                    0x00000008
#define TMC2130_OFS99_SHIFT                   3
#define TMC2130_OFS99_FIELD                   ((RegisterField) { 0x00000008, 3, 0x63 })
#define TMC2130_OFS100_MASK                   0x00000010
#define TMC2130_OFS100_SHIFT                  4
#define TMC2130_OFS100_FIELD                  ((RegisterField) { 0x00000010, 4, 0x63 })
#define TMC2130_OFS101_MASK                   0x00000020
#define TMC2130_OFS101_SHIFT                  5
#define TMC2130_OFS101_FIELD                  ((RegisterField) { 0x00000020, 5, 0x63 })
#define TMC2130_OFS102_MASK                   0x00000040
#define TMC2130_OFS102_SHIFT                  6
#define TMC2130_OFS102_FIELD                  ((RegisterField) { 0x00000040, 6, 0x63 })
#define TMC2130_OFS103_MASK                   0x00000080
#define TMC2130_OFS103_SHIFT                  7
#define TMC2130_OFS103_FIELD                  ((RegisterField) { 0x00000080, 7, 0x63 })
#define TMC2130_OFS104_MASK                   0x00000100
#define TMC2130_OFS104_SHIFT                  8
#define TMC2130_OFS104_FIELD                  ((RegisterField) { 0x00000100, 8, 0x63 })
#define TMC2130_OFS105_MASK                   0x00000200
#define TMC2130_OFS105_SHIFT                  9
#define TMC2130_OFS105_FIELD                  ((RegisterField) { 0x00000200, 9, 0x63 })
#define TMC2130_OFS106_MASK                   0x00000400
#define TMC2130_OFS106_SHIFT                  10
#define TMC2130_OFS106_FIELD                  ((RegisterField) { 0x00000400, 10, 0x63 })
#define TMC2130_OFS107_MASK                   0x00000800
#define TMC2130_OFS107_SHIFT                  11
#define TMC2130_OFS107_FIELD                  ((RegisterField) { 0x00000800, 11, 0x63 })
#define TMC2130_OFS108_MASK                   0x00001000
#define TMC2130_OFS108_SHIFT                  12
#define TMC2130_OFS108_FIELD                  ((RegisterField) { 0x00001000, 12, 0x63 })
#define TMC2130_OFS109_MASK                   0x00002000
#define TMC2130_OFS109_SHIFT                  13
#define TMC2130_OFS109_FIELD                  ((RegisterField) { 0x00002000, 13, 0x63 })
#define TMC2130_OFS110_MASK                   0x00004000
#define TMC2130_OFS110_SHIFT                  14
#define TMC2130_OFS110_FIELD                  ((RegisterField) { 0x00004000, 14, 0x63 })
#define TMC2130_OFS111_MASK                   0x00008000
#define TMC2130_OFS111_SHIFT                  15
#define TMC2130_OFS111_FIELD                  ((RegisterField) { 0x00008000, 15, 0x63 })
#define TMC2130_OFS112_MASK                   0x00010000
#define TMC2130_OFS112_SHIFT                  16
#define TMC2130_OFS112_FIELD                  ((RegisterField) { 0x00010000, 16, 0x63 })
#define TMC2130_OFS113_MASK                   0x00020000
#define TMC2130_OFS113_SHIFT                  17
#define TMC2130_OFS113_FIELD                  ((RegisterField) { 0x00020000, 17, 0x63 })
#define TMC2130_OFS114_MASK                   0x00040000
#define TMC2130_OFS114_SHIFT                  18
#define TMC2130_OFS114_FIELD                  ((RegisterField) { 0x00040000, 18, 0x63 })
#define TMC2130_OFS115_MASK                   0x00080000
#define TMC2130_OFS115_SHIFT                  19
#define TMC2130_OFS115_FIELD                  ((RegisterField) { 0x00080000, 19, 0x63 })
#define TMC2130_OFS116_MASK                   0x00100000
#define TMC2130_OFS116_SHIFT                  20
#define TMC2130_OFS116_FIELD                  ((RegisterField) { 0x00100000, 20, 0x63 })
#define TMC2130_OFS117_MASK                   0x00200000
#define TMC2130_OFS117_SHIFT                  21
#define TMC2130_OFS117_FIELD                  ((RegisterField) { 0x00200000, 21, 0x63 })
#define TMC2130_OFS118_MASK                   0x00400000
#define TMC2130_OFS118_SHIFT                  22
#define TMC2130_OFS118_FIELD                  ((RegisterField) { 0x00400000, 22, 0x63 })
#define TMC2130_OFS119_MASK                   0x00800000
#define TMC2130_OFS119_SHIFT                  23
#define TMC2130_OFS119_FIELD                  ((RegisterField) { 0x00800000, 23, 0x63 })
#define TMC2130_OFS120_MASK                   0x01000000
#define TMC2130_OFS120_SHIFT                  24
#define TMC2130_OFS120_FIELD                  ((RegisterField) { 0x01000000, 24, 0x63 })
#define TMC2130_OFS121_MASK                   0x02000000
#define TMC2130_OFS121_SHIFT                  25
#define TMC2130_OFS121_FIELD                  ((RegisterField) { 0x02000000, 25, 0x63 })
#define TMC2130_OFS122_MASK                   0x04000000
#define TMC2130_OFS122_SHIFT                  26
#define TMC2130_OFS122_FIELD                  ((RegisterField) { 0x04000000, 26, 0x63 })
#define TMC2130_OFS123_MASK                   0x08000000
#define TMC2130_OFS123_SHIFT                  27
#define TMC2130_OFS123_FIELD                  ((RegisterField) { 0x08000000, 27, 0x63 })
#define TMC2130_OFS124_MASK                   0x10000000
#define TMC2130_OFS124_SHIFT                  28
#define TMC2130_OFS124_FIELD                  ((RegisterField) { 0x10000000, 28, 0x63 })
#define TMC2130_OFS125_MASK                   0x20000000
#define TMC2130_OFS125_SHIFT                  29
#define TMC2130_OFS125_FIELD                  ((RegisterField) { 0x20000000, 29, 0x63 })
#define TMC2130_OFS126_MASK                   0x40000000
#define TMC2130_OFS126_SHIFT                  30
#define TMC2130_OFS126_FIELD                  ((RegisterField) { 0x40000000, 30, 0x63 })
#define TMC2130_OFS127_MASK                   0x80000000
#define TMC2130_OFS127_SHIFT                  31
#define TMC2130_OFS127_FIELD                  ((RegisterField) { 0x80000000, 31, 0x63 })
#define TMC2130_OFS128_MASK                   0x00000001
#define TMC2130_OFS128_SHIFT                  0
#define TMC2130_OFS128_FIELD                  ((RegisterField) { 0x00000001, 0, 0x64 })
#define TMC2130_OFS129_MASK                   0x00000002
#define TMC2130_OFS129_SHIFT                  1
#define TMC2130_OFS129_FIELD                  ((RegisterField) { 0x00000002, 1, 0x64 })
#define TMC2130_OFS130_MASK                   0x00000004
#define TMC2130_OFS130_SHIFT                  2
#define TMC2130_OFS130_FIELD                  ((RegisterField) { 0x00000004, 2, 0x64 })
#define TMC2130_OFS131_MASK                   0x00000008
#define TMC2130_OFS131_SHIFT                  3
#define TMC2130_OFS131_FIELD                  ((RegisterField) { 0x00000008, 3, 0x64 })
#define TMC2130_OFS132_MASK                   0x00000010
#define TMC2130_OFS132_SHIFT                  4
#define TMC2130_OFS132_FIELD                  ((RegisterField) { 0x00000010, 4, 0x64 })
#define TMC2130_OFS133_MASK                   0x00000020
#define TMC2130_OFS133_SHIFT                  5
#define TMC2130_OFS133_FIELD                  ((RegisterField) { 0x00000020, 5, 0x64 })
#define TMC2130_OFS134_MASK                   0x00000040
#define TMC2130_OFS134_SHIFT                  6
#define TMC2130_OFS134_FIELD                  ((RegisterField) { 0x00000040, 6, 0x64 })
#define TMC2130_OFS135_MASK                   0x00000080
#define TMC2130_OFS135_SHIFT                  7
#define TMC2130_OFS135_FIELD                  ((RegisterField) { 0x00000080, 7, 0x64 })
#define TMC2130_OFS136_MASK                   0x00000100
#define TMC2130_OFS136_SHIFT                  8
#define TMC2130_OFS136_FIELD                  ((RegisterField) { 0x00000100, 8, 0x64 })
#define TMC2130_OFS137_MASK                   0x00000200
#define TMC2130_OFS137_SHIFT                  9
#define TMC2130_OFS137_FIELD                  ((RegisterField) { 0x00000200, 9, 0x64 })
#define TMC2130_OFS138_MASK                   0x00000400
#define TMC2130_OFS138_SHIFT                  10
#define TMC2130_OFS138_FIELD                  ((RegisterField) { 0x00000400, 10, 0x64 })
#define TMC2130_OFS139_MASK                   0x00000800
#define TMC2130_OFS139_SHIFT                  11
#define TMC2130_OFS139_FIELD                  ((RegisterField) { 0x00000800, 11, 0x64 })
#define TMC2130_OFS140_MASK                   0x00001000
#define TMC2130_OFS140_SHIFT                  12
#define TMC2130_OFS140_FIELD                  ((RegisterField) { 0x00001000, 12, 0x64 })
#define TMC2130_OFS141_MASK                   0x00002000
#define TMC2130_OFS141_SHIFT                  13
#define TMC2130_OFS141_FIELD                  ((RegisterField) { 0x00002000, 13, 0x64 })
#define TMC2130_OFS142_MASK                   0x00004000
#define TMC2130_OFS142_SHIFT                  14
#define TMC2130_OFS142_FIELD                  ((RegisterField) { 0x00004000, 14, 0x64 })
#define TMC2130_OFS143_MASK                   0x00008000
#define TMC2130_OFS143_SHIFT                  15
#define TMC2130_OFS143_FIELD                  ((RegisterField) { 0x00008000, 15, 0x64 })
#define TMC2130_OFS144_MASK                   0x00010000
#define TMC2130_OFS144_SHIFT                  16
#define TMC2130_OFS144_FIELD                  ((RegisterField) { 0x00010000, 16, 0x64 })
#define TMC2130_OFS145_MASK                   0x00020000
#define TMC2130_OFS145_SHIFT                  17
#define TMC2130_OFS145_FIELD                  ((RegisterField) { 0x00020000, 17, 0x64 })
#define TMC2130_OFS146_MASK                   0x00040000
#define TMC2130_OFS146_SHIFT                  18
#define TMC2130_OFS146_FIELD                  ((RegisterField) { 0x00040000, 18, 0x64 })
#define TMC2130_OFS147_MASK                   0x00080000
#define TMC2130_OFS147_SHIFT                  19
#define TMC2130_OFS147_FIELD                  ((RegisterField) { 0x00080000, 19, 0x64 })
#define TMC2130_OFS148_MASK                   0x00100000
#define TMC2130_OFS148_SHIFT                  20
#define TMC2130_OFS148_FIELD                  ((RegisterField) { 0x00100000, 20, 0x64 })
#define TMC2130_OFS149_MASK                   0x00200000
#define TMC2130_OFS149_SHIFT                  21
#define TMC2130_OFS149_FIELD                  ((RegisterField) { 0x00200000, 21, 0x64 })
#define TMC2130_OFS150_MASK                   0x00400000
#define TMC2130_OFS150_SHIFT                  22
#define TMC2130_OFS150_FIELD                  ((RegisterField) { 0x00400000, 22, 0x64 })
#define TMC2130_OFS151_MASK                   0x00800000
#define TMC2130_OFS151_SHIFT                  23
#define TMC2130_OFS151_FIELD                  ((RegisterField) { 0x00800000, 23, 0x64 })
#define TMC2130_OFS152_MASK                   0x01000000
#define TMC2130_OFS152_SHIFT                  24
#define TMC2130_OFS152_FIELD                  ((RegisterField) { 0x01000000, 24, 0x64 })
#define TMC2130_OFS153_MASK                   0x02000000
#define TMC2130_OFS153_SHIFT                  25
#define TMC2130_OFS153_FIELD                  ((RegisterField) { 0x02000000, 25, 0x64 })
#define TMC2130_OFS154_MASK                   0x04000000
#define TMC2130_OFS154_SHIFT                  26
#define TMC2130_OFS154_FIELD                  ((RegisterField) { 0x04000000, 26, 0x64 })
#define TMC2130_OFS155_MASK                   0x08000000
#define TMC2130_OFS155_SHIFT                  27
#define TMC2130_OFS155_FIELD                  ((RegisterField) { 0x08000000, 27, 0x64 })
#define TMC2130_OFS156_MASK                   0x10000000
#define TMC2130_OFS156_SHIFT                  28
#define TMC2130_OFS156_FIELD                  ((RegisterField) { 0x10000000, 28, 0x64 })
#define TMC2130_OFS157_MASK                   0x20000000
#define TMC2130_OFS157_SHIFT                  29
#define TMC2130_OFS157_FIELD                  ((RegisterField) { 0x20000000, 29, 0x64 })
#define TMC2130_OFS158_MASK                   0x40000000
#define TMC2130_OFS158_SHIFT                  30
#define TMC2130_OFS158_FIELD                  ((RegisterField) { 0x40000000, 30, 0x64 })
#define TMC2130_OFS159_MASK                   0x80000000
#define TMC2130_OFS159_SHIFT                  31
#define TMC2130_OFS159_FIELD                  ((RegisterField) { 0x80000000, 31, 0x64 })
#define TMC2130_OFS160_MASK                   0x00000001
#define TMC2130_OFS160_SHIFT                  0
#define TMC2130_OFS160_FIELD                  ((RegisterField) { 0x00000001, 0, 0x65 })
#define TMC2130_OFS161_MASK                   0x00000002
#define TMC2130_OFS161_SHIFT                  1
#define TMC2130_OFS161_FIELD                  ((RegisterField) { 0x00000002, 1, 0x65 })
#define TMC2130_OFS162_MASK                   0x00000004
#define TMC2130_OFS162_SHIFT                  2
#define TMC2130_OFS162_FIELD                  ((RegisterField) { 0x00000004, 2, 0x65 })
#define TMC2130_OFS163_MASK                   0x00000008
#define TMC2130_OFS163_SHIFT                  3
#define TMC2130_OFS163_FIELD                  ((RegisterField) { 0x00000008, 3, 0x65 })
#define TMC2130_OFS164_MASK                   0x00000010
#define TMC2130_OFS164_SHIFT                  4
#define TMC2130_OFS164_FIELD                  ((RegisterField) { 0x00000010, 4, 0x65 })
#define TMC2130_OFS165_MASK                   0x00000020
#define TMC2130_OFS165_SHIFT                  5
#define TMC2130_OFS165_FIELD                  ((RegisterField) { 0x00000020, 5, 0x65 })
#define TMC2130_OFS166_MASK                   0x00000040
#define TMC2130_OFS166_SHIFT                  6
#define TMC2130_OFS166_FIELD                  ((RegisterField) { 0x00000040, 6, 0x65 })
#define TMC2130_OFS167_MASK                   0x00000080
#define TMC2130_OFS167_SHIFT                  7
#define TMC2130_OFS167_FIELD                  ((RegisterField) { 0x00000080, 7, 0x65 })
#define TMC2130_OFS168_MASK                   0x00000100
#define TMC2130_OFS168_SHIFT                  8
#define TMC2130_OFS168_FIELD                  ((RegisterField) { 0x00000100, 8, 0x65 })
#define TMC2130_OFS169_MASK                   0x00000200
#define TMC2130_OFS169_SHIFT                  9
#define TMC2130_OFS169_FIELD                  ((RegisterField) { 0x00000200, 9, 0x65 })
#define TMC2130_OFS170_MASK                   0x00000400
#define TMC2130_OFS170_SHIFT                  10
#define TMC2130_OFS170_FIELD                  ((RegisterField) { 0x00000400, 10, 0x65 })
#define TMC2130_OFS171_MASK                   0x00000800
#define TMC2130_OFS171_SHIFT                  11
#define TMC2130_OFS171_FIELD                  ((RegisterField) { 0x00000800, 11, 0x65 })
#define TMC2130_OFS172_MASK                   0x00001000
#define TMC2130_OFS172_SHIFT                  12
#define TMC2130_OFS172_FIELD                  ((RegisterField) { 0x00001000, 12, 0x65 })
#define TMC2130_OFS173_MASK                   0x00002000
#define TMC2130_OFS173_SHIFT                  13
#define TMC2130_OFS173_FIELD                  ((RegisterField) { 0x00002000, 13, 0x65 })
#define TMC2130_OFS174_MASK                   0x00004000
#define TMC2130_OFS174_SHIFT                  14
#define TMC2130_OFS174_FIELD                  ((RegisterField) { 0x00004000, 14, 0x65 })
#define TMC2130_OFS175_MASK                   0x00008000
#define TMC2130_OFS175_SHIFT                  15
#define TMC2130_OFS175_FIELD                  ((RegisterField) { 0x00008000, 15, 0x65 })
#define TMC2130_OFS176_MASK                   0x00010000
#define TMC2130_OFS176_SHIFT                  16
#define TMC2130_OFS176_FIELD                  ((RegisterField) { 0x00010000, 16, 0x65 })
#define TMC2130_OFS177_MASK                   0x00020000
#define TMC2130_OFS177_SHIFT                  17
#define TMC2130_OFS177_FIELD                  ((RegisterField) { 0x00020000, 17, 0x65 })
#define TMC2130_OFS178_MASK                   0x00040000
#define TMC2130_OFS178_SHIFT                  18
#define TMC2130_OFS178_FIELD                  ((RegisterField) { 0x00040000, 18, 0x65 })
#define TMC2130_OFS179_MASK                   0x00080000
#define TMC2130_OFS179_SHIFT                  19
#define TMC2130_OFS179_FIELD                  ((RegisterField) { 0x00080000, 19, 0x65 })
#define TMC2130_OFS180_MASK                   0x00100000
#define TMC2130_OFS180_SHIFT                  20
#define TMC2130_OFS180_FIELD                  ((RegisterField) { 0x00100000, 20, 0x65 })
#define TMC2130_OFS181_MASK                   0x00200000
#define TMC2130_OFS181_SHIFT                  21
#define TMC2130_OFS181_FIELD                  ((RegisterField) { 0x00200000, 21, 0x65 })
#define TMC2130_OFS182_MASK                   0x00400000
#define TMC2130_OFS182_SHIFT                  22
#define TMC2130_OFS182_FIELD                  ((RegisterField) { 0x00400000, 22, 0x65 })
#define TMC2130_OFS183_MASK                   0x00800000
#define TMC2130_OFS183_SHIFT                  23
#define TMC2130_OFS183_FIELD                  ((RegisterField) { 0x00800000, 23, 0x65 })
#define TMC2130_OFS184_MASK                   0x01000000
#define TMC2130_OFS184_SHIFT                  24
#define TMC2130_OFS184_FIELD                  ((RegisterField) { 0x01000000, 24, 0x65 })
#define TMC2130_OFS185_MASK                   0x02000000
#define TMC2130_OFS185_SHIFT                  25
#define TMC2130_OFS185_FIELD                  ((RegisterField) { 0x02000000, 25, 0x65 })
#define TMC2130_OFS186_MASK                   0x04000000
#define TMC2130_OFS186_SHIFT                  26
#define TMC2130_OFS186_FIELD                  ((RegisterField) { 0x04000000, 26, 0x65 })
#define TMC2130_OFS187_MASK                   0x08000000
#define TMC2130_OFS187_SHIFT                  27
#define TMC2130_OFS187_FIELD                  ((RegisterField) { 0x08000000, 27, 0x65 })
#define TMC2130_OFS188_MASK                   0x10000000
#define TMC2130_OFS188_SHIFT                  28
#define TMC2130_OFS188_FIELD                  ((RegisterField) { 0x10000000, 28, 0x65 })
#define TMC2130_OFS189_MASK                   0x20000000
#define TMC2130_OFS189_SHIFT                  29
#define TMC2130_OFS189_FIELD                  ((RegisterField) { 0x20000000, 29, 0x65 })
#define TMC2130_OFS190_MASK                   0x40000000
#define TMC2130_OFS190_SHIFT                  30
#define TMC2130_OFS190_FIELD                  ((RegisterField) { 0x40000000, 30, 0x65 })
#define TMC2130_OFS191_MASK                   0x80000000
#define TMC2130_OFS191_SHIFT                  31
#define TMC2130_OFS191_FIELD                  ((RegisterField) { 0x80000000, 31, 0x65 })
#define TMC2130_OFS192_MASK                   0x00000001
#define TMC2130_OFS192_SHIFT                  0
#define TMC2130_OFS192_FIELD                  ((RegisterField) { 0x00000001, 0, 0x66 })
#define TMC2130_OFS193_MASK                   0x00000002
#define TMC2130_OFS193_SHIFT                  1
#define TMC2130_OFS193_FIELD                  ((RegisterField) { 0x00000002, 1, 0x66 })
#define TMC2130_OFS194_MASK                   0x00000004
#define TMC2130_OFS194_SHIFT                  2
#define TMC2130_OFS194_FIELD                  ((RegisterField) { 0x00000004, 2, 0x66 })
#define TMC2130_OFS195_MASK                   0x00000008
#define TMC2130_OFS195_SHIFT                  3
#define TMC2130_OFS195_FIELD                  ((RegisterField) { 0x00000008, 3, 0x66 })
#define TMC2130_OFS196_MASK                   0x00000010
#define TMC2130_OFS196_SHIFT                  4
#define TMC2130_OFS196_FIELD                  ((RegisterField) { 0x00000010, 4, 0x66 })
#define TMC2130_OFS197_MASK                   0x00000020
#define TMC2130_OFS197_SHIFT                  5
#define TMC2130_OFS197_FIELD                  ((RegisterField) { 0x00000020, 5, 0x66 })
#define TMC2130_OFS198_MASK                   0x00000040
#define TMC2130_OFS198_SHIFT                  6
#define TMC2130_OFS198_FIELD                  ((RegisterField) { 0x00000040, 6, 0x66 })
#define TMC2130_OFS199_MASK                   0x00000080
#define TMC2130_OFS199_SHIFT                  7
#define TMC2130_OFS199_FIELD                  ((RegisterField) { 0x00000080, 7, 0x66 })
#define TMC2130_OFS200_MASK                   0x00000100
#define TMC2130_OFS200_SHIFT                  8
#define TMC2130_OFS200_FIELD                  ((RegisterField) { 0x00000100, 8, 0x66 })
#define TMC2130_OFS201_MASK                   0x00000200
#define TMC2130_OFS201_SHIFT                  9
#define TMC2130_OFS201_FIELD                  ((RegisterField) { 0x00000200, 9, 0x66 })
#define TMC2130_OFS202_MASK                   0x00000400
#define TMC2130_OFS202_SHIFT                  10
#define TMC2130_OFS202_FIELD                  ((RegisterField) { 0x00000400, 10, 0x66 })
#define TMC2130_OFS203_MASK                   0x00000800
#define TMC2130_OFS203_SHIFT                  11
#define TMC2130_OFS203_FIELD                  ((RegisterField) { 0x00000800, 11, 0x66 })
#define TMC2130_OFS204_MASK                   0x00001000
#define TMC2130_OFS204_SHIFT                  12
#define TMC2130_OFS204_FIELD                  ((RegisterField) { 0x00001000, 12, 0x66 })
#define TMC2130_OFS205_MASK                   0x00002000
#define TMC2130_OFS205_SHIFT                  13
#define TMC2130_OFS205_FIELD                  ((RegisterField) { 0x00002000, 13, 0x66 })
#define TMC2130_OFS206_MASK                   0x00004000
#define TMC2130_OFS206_SHIFT                  14
#define TMC2130_OFS206_FIELD                  ((RegisterField) { 0x00004000, 14, 0x66 })
#define TMC2130_OFS207_MASK                   0x00008000
#define TMC2130_OFS207_SHIFT                  15
#define TMC2130_OFS207_FIELD                  ((RegisterField) { 0x00008000, 15, 0x66 })
#define TMC2130_OFS208_MASK                   0x00010000
#define TMC2130_OFS208_SHIFT                  16
#define TMC2130_OFS208_FIELD                  ((RegisterField) { 0x00010000, 16, 0x66 })
#define TMC2130_OFS209_MASK                   0x00020000
#define TMC2130_OFS209_SHIFT                  17
#define TMC2130_OFS209_FIELD                  ((RegisterField) { 0x00020000, 17, 0x66 })
#define TMC2130_OFS210_MASK                   0x00040000
#define TMC2130_OFS210_SHIFT                  18
#define TMC2130_OFS210_FIELD                  ((RegisterField) { 0x00040000, 18, 0x66 })
#define TMC2130_OFS211_MASK                   0x00080000
#define TMC2130_OFS211_SHIFT                  19
#define TMC2130_OFS211_FIELD                  ((RegisterField) { 0x00080000, 19, 0x66 })
#define TMC2130_OFS212_MASK                   0x00100000
#define TMC2130_OFS212_SHIFT                  20
#define TMC2130_OFS212_FIELD                  ((RegisterField) { 0x00100000, 20, 0x66 })
#define TMC2130_OFS213_MASK                   0x00200000
#define TMC2130_OFS213_SHIFT                  21
#define TMC2130_OFS213_FIELD                  ((RegisterField) { 0x00200000, 21, 0x66 })
#define TMC2130_OFS214_MASK                   0x00400000
#define TMC2130_OFS214_SHIFT                  22
#define TMC2130_OFS214_FIELD                  ((RegisterField) { 0x00400000, 22, 0x66 })
#define TMC2130_OFS215_MASK                   0x00800000
#define TMC2130_OFS215_SHIFT                  23
#define TMC2130_OFS215_FIELD                  ((RegisterField) { 0x00800000, 23, 0x66 })
#define TMC2130_OFS216_MASK                   0x01000000
#define TMC2130_OFS216_SHIFT                  24
#define TMC2130_OFS216_FIELD                  ((RegisterField) { 0x01000000, 24, 0x66 })
#define TMC2130_OFS217_MASK                   0x02000000
#define TMC2130_OFS217_SHIFT                  25
#define TMC2130_OFS217_FIELD                  ((RegisterField) { 0x02000000, 25, 0x66 })
#define TMC2130_OFS218_MASK                   0x04000000
#define TMC2130_OFS218_SHIFT                  26
#define TMC2130_OFS218_FIELD                  ((RegisterField) { 0x04000000, 26, 0x66 })
#define TMC2130_OFS219_MASK                   0x08000000
#define TMC2130_OFS219_SHIFT                  27
#define TMC2130_OFS219_FIELD                  ((RegisterField) { 0x08000000, 27, 0x66 })
#define TMC2130_OFS220_MASK                   0x10000000
#define TMC2130_OFS220_SHIFT                  28
#define TMC2130_OFS220_FIELD                  ((RegisterField) { 0x10000000, 28, 0x66 })
#define TMC2130_OFS221_MASK                   0x20000000
#define TMC2130_OFS221_SHIFT                  29
#define TMC2130_OFS221_FIELD                  ((RegisterField) { 0x20000000, 29, 0x66 })
#define TMC2130_OFS222_MASK                   0x40000000
#define TMC2130_OFS222_SHIFT                  30
#define TMC2130_OFS222_FIELD                  ((RegisterField) { 0x40000000, 30, 0x66 })
#define TMC2130_OFS223_MASK                   0x80000000
#define TMC2130_OFS223_SHIFT                  31
#define TMC2130_OFS223_FIELD                  ((RegisterField) { 0x80000000, 31, 0x66 })
#define TMC2130_OFS224_MASK                   0x00000001
#define TMC2130_OFS224_SHIFT                  0
#define TMC2130_OFS224_FIELD                  ((RegisterField) { 0x00000001, 0, 0x67 })
#define TMC2130_OFS225_MASK                   0x00000002
#define TMC2130_OFS225_SHIFT                  1
#define TMC2130_OFS225_FIELD                  ((RegisterField) { 0x00000002, 1, 0x67 })
#define TMC2130_OFS226_MASK                   0x00000004
#define TMC2130_OFS226_SHIFT                  2
#define TMC2130_OFS226_FIELD                  ((RegisterField) { 0x00000004, 2, 0x67 })
#define TMC2130_OFS227_MASK                   0x00000008
#define TMC2130_OFS227_SHIFT                  3
#define TMC2130_OFS227_FIELD                  ((RegisterField) { 0x00000008, 3, 0x67 })
#define TMC2130_OFS228_MASK                   0x00000010
#define TMC2130_OFS228_SHIFT                  4
#define TMC2130_OFS228_FIELD                  ((RegisterField) { 0x00000010, 4, 0x67 })
#define TMC2130_OFS229_MASK                   0x00000020
#define TMC2130_OFS229_SHIFT                  5
#define TMC2130_OFS229_FIELD                  ((RegisterField) { 0x00000020, 5, 0x67 })
#define TMC2130_OFS230_MASK                   0x00000040
#define TMC2130_OFS230_SHIFT                  6
#define TMC2130_OFS230_FIELD                  ((RegisterField) { 0x00000040, 6, 0x67 })
#define TMC2130_OFS231_MASK                   0x00000080
#define TMC2130_OFS231_SHIFT                  7
#define TMC2130_OFS231_FIELD                  ((RegisterField) { 0x00000080, 7, 0x67 })
#define TMC2130_OFS232_MASK                   0x00000100
#define TMC2130_OFS232_SHIFT                  8
#define TMC2130_OFS232_FIELD                  ((RegisterField) { 0x00000100, 8, 0x67 })
#define TMC2130_OFS233_MASK                   0x00000200
#define TMC2130_OFS233_SHIFT                  9
#define TMC2130_OFS233_FIELD                  ((RegisterField) { 0x00000200, 9, 0x67 })
#define TMC2130_OFS234_MASK                   0x00000400
#define TMC2130_OFS234_SHIFT                  10
#define TMC2130_OFS234_FIELD                  ((RegisterField) { 0x00000400, 10, 0x67 })
#define TMC2130_OFS235_MASK                   0x00000800
#define TMC2130_OFS235_SHIFT                  11
#define TMC2130_OFS235_FIELD                  ((RegisterField) { 0x00000800, 11, 0x67 })
#define TMC2130_OFS236_MASK                   0x00001000
#define TMC2130_OFS236_SHIFT                  12
#define TMC2130_OFS236_FIELD                  ((RegisterField) { 0x00001000, 12, 0x67 })
#define TMC2130_OFS237_MASK                   0x00002000
#define TMC2130_OFS237_SHIFT                  13
#define TMC2130_OFS237_FIELD                  ((RegisterField) { 0x00002000, 13, 0x67 })
#define TMC2130_OFS238_MASK                   0x00004000
#define TMC2130_OFS238_SHIFT                  14
#define TMC2130_OFS238_FIELD                  ((RegisterField) { 0x00004000, 14, 0x67 })
#define TMC2130_OFS239_MASK                   0x00008000
#define TMC2130_OFS239_SHIFT                  15
#define TMC2130_OFS239_FIELD                  ((RegisterField) { 0x00008000, 15, 0x67 })
#define TMC2130_OFS240_MASK                   0x00010000
#define TMC2130_OFS240_SHIFT                  16
#define TMC2130_OFS240_FIELD                  ((RegisterField) { 0x00010000, 16, 0x67 })
#define TMC2130_OFS241_MASK                   0x00020000
#define TMC2130_OFS241_SHIFT                  17
#define TMC2130_OFS241_FIELD                  ((RegisterField) { 0x00020000, 17, 0x67 })
#define TMC2130_OFS242_MASK                   0x00040000
#define TMC2130_OFS242_SHIFT                  18
#define TMC2130_OFS242_FIELD                  ((RegisterField) { 0x00040000, 18, 0x67 })
#define TMC2130_OFS243_MASK                   0x00080000
#define TMC2130_OFS243_SHIFT                  19
#define TMC2130_OFS243_FIELD                  ((RegisterField) { 0x00080000, 19, 0x67 })
#define TMC2130_OFS244_MASK                   0x00100000
#define TMC2130_OFS244_SHIFT                  20
#define TMC2130_OFS244_FIELD                  ((RegisterField) { 0x00100000, 20, 0x67 })
#define TMC2130_OFS245_MASK                   0x00200000
#define TMC2130_OFS245_SHIFT                  21
#define TMC2130_OFS245_FIELD                  ((RegisterField) { 0x00200000, 21, 0x67 })
#define TMC2130_OFS246_MASK                   0x00400000
#define TMC2130_OFS246_SHIFT                  22
#define TMC2130_OFS246_FIELD                  ((RegisterField) { 0x00400000, 22, 0x67 })
#define TMC2130_OFS247_MASK                   0x00800000
#define TMC2130_OFS247_SHIFT                  23
#define TMC2130_OFS247_FIELD                  ((RegisterField) { 0x00800000, 23, 0x67 })
#define TMC2130_OFS248_MASK                   0x01000000
#define TMC2130_OFS248_SHIFT                  24
#define TMC2130_OFS248_FIELD                  ((RegisterField) { 0x01000000, 24, 0x67 })
#define TMC2130_OFS249_MASK                   0x02000000
#define TMC2130_OFS249_SHIFT                  25
#define TMC2130_OFS249_FIELD                  ((RegisterField) { 0x02000000, 25, 0x67 })
#define TMC2130_OFS250_MASK                   0x04000000
#define TMC2130_OFS250_SHIFT                  26
#define TMC2130_OFS250_FIELD                  ((RegisterField) { 0x04000000, 26, 0x67 })
#define TMC2130_OFS251_MASK                   0x08000000
#define TMC2130_OFS251_SHIFT                  27
#define TMC2130_OFS251_FIELD                  ((RegisterField) { 0x08000000, 27, 0x67 })
#define TMC2130_OFS252_MASK                   0x10000000
#define TMC2130_OFS252_SHIFT                  28
#define TMC2130_OFS252_FIELD                  ((RegisterField) { 0x10000000, 28, 0x67 })
#define TMC2130_OFS253_MASK                   0x20000000
#define TMC2130_OFS253_SHIFT                  29
#define TMC2130_OFS253_FIELD                  ((RegisterField) { 0x20000000, 29, 0x67 })
#define TMC2130_OFS254_MASK                   0x40000000
#define TMC2130_OFS254_SHIFT                  30
#define TMC2130_OFS254_FIELD                  ((RegisterField) { 0x40000000, 30, 0x67 })
#define TMC2130_OFS255_MASK                   0x80000000
#define TMC2130_OFS255_SHIFT                  31
#define TMC2130_OFS255_FIELD                  ((RegisterField) { 0x80000000, 31, 0x67 })
#define TMC2130_W0_MASK                       0x00000003
#define TMC2130_W0_SHIFT                      0
#define TMC2130_W0_FIELD                      ((RegisterField) { 0x00000003, 0, 0x68 })
#define TMC2130_W1_MASK                       0x0000000C
#define TMC2130_W1_SHIFT                      2
#define TMC2130_W1_FIELD                      ((RegisterField) { 0x0000000C, 2, 0x68 })
#define TMC2130_W2_MASK                       0x00000030
#define TMC2130_W2_SHIFT                      4
#define TMC2130_W2_FIELD                      ((RegisterField) { 0x00000030, 4, 0x68 })
#define TMC2130_W3_MASK                       0x000000C0
#define TMC2130_W3_SHIFT                      6
#define TMC2130_W3_FIELD                      ((RegisterField) { 0x000000C0, 6, 0x68 })
#define TMC2130_X1_MASK                       0x0000FF00
#define TMC2130_X1_SHIFT                      8
#define TMC2130_X1_FIELD                      ((RegisterField) { 0x0000FF00, 8, 0x68 })
#define TMC2130_X2_MASK                       0x00FF0000
#define TMC2130_X2_SHIFT                      16
#define TMC2130_X2_FIELD                      ((RegisterField) { 0x00FF0000, 16, 0x68 })
#define TMC2130_X3_MASK                       0xFF000000
#define TMC2130_X3_SHIFT                      24
#define TMC2130_X3_FIELD                      ((RegisterField) { 0xFF000000, 24, 0x68 })
#define TMC2130_START_SIN_MASK                0x000000FF
#define TMC2130_START_SIN_SHIFT               0
#define TMC2130_START_SIN_FIELD               ((RegisterField) { 0x000000FF, 0, 0x69 })
#define TMC2130_START_SIN90_MASK              0x00FF0000
#define TMC2130_START_SIN90_SHIFT             16
#define TMC2130_START_SIN90_FIELD             ((RegisterField) { 0x00FF0000, 16, 0x69 })
#define TMC2130_MSCNT_MASK                    0x000003FF
#define TMC2130_MSCNT_SHIFT                   0
#define TMC2130_MSCNT_FIELD                   ((RegisterField) { 0x000003FF, 0, 0x6A })
#define TMC2130_CUR_A_MASK                    0x000001FF
#define TMC2130_CUR_A_SHIFT                   0
#define TMC2130_CUR_A_FIELD                   ((RegisterField) { 0x000001FF, 0, 0x6B })
#define TMC2130_CUR_B_MASK                    0x01FF0000
#define TMC2130_CUR_B_SHIFT                   16
#define TMC2130_CUR_B_FIELD                   ((RegisterField) { 0x01FF0000, 16, 0x6B })
#define TMC2130_TOFF_MASK                     0x0000000F
#define TMC2130_TOFF_SHIFT                    0
#define TMC2130_TOFF_FIELD                    ((RegisterField) { 0x0000000F, 0, 0x6C })
#define TMC2130_TFD_2_0_MASK                  0x00000070
#define TMC2130_TFD_2_0_SHIFT                 4
#define TMC2130_TFD_2_0_FIELD                 ((RegisterField) { 0x00000070, 4, 0x6C })
#define TMC2130_OFFSET_MASK                   0x00000780
#define TMC2130_OFFSET_SHIFT                  7
#define TMC2130_OFFSET_FIELD                  ((RegisterField) { 0x00000780, 7, 0x6C })
#define TMC2130_TFD_3_MASK                    0x00000800
#define TMC2130_TFD_3_SHIFT                   11
#define TMC2130_TFD_3_FIELD                   ((RegisterField) { 0x00000800, 11, 0x6C })
#define TMC2130_DISFDCC_MASK                  0x00001000
#define TMC2130_DISFDCC_SHIFT                 12
#define TMC2130_DISFDCC_FIELD                 ((RegisterField) { 0x00001000, 12, 0x6C })
#define TMC2130_RNDTF_MASK                    0x00002000
#define TMC2130_RNDTF_SHIFT                   13
#define TMC2130_RNDTF_FIELD                   ((RegisterField) { 0x00002000, 13, 0x6C })
#define TMC2130_CHM_MASK                      0x00004000
#define TMC2130_CHM_SHIFT                     14
#define TMC2130_CHM_FIELD                     ((RegisterField) { 0x00004000, 14, 0x6C })
#define TMC2130_TBL_MASK                      0x00018000
#define TMC2130_TBL_SHIFT                     15
#define TMC2130_TBL_FIELD                     ((RegisterField) { 0x00018000, 15, 0x6C })
#define TMC2130_VSENSE_MASK                   0x00020000
#define TMC2130_VSENSE_SHIFT                  17
#define TMC2130_VSENSE_FIELD                  ((RegisterField) { 0x00020000, 17, 0x6C })
#define TMC2130_VHIGHFS_MASK                  0x00040000
#define TMC2130_VHIGHFS_SHIFT                 18
#define TMC2130_VHIGHFS_FIELD                 ((RegisterField) { 0x00040000, 18, 0x6C })
#define TMC2130_VHIGHCHM_MASK                 0x00080000
#define TMC2130_VHIGHCHM_SHIFT                19
#define TMC2130_VHIGHCHM_FIELD                ((RegisterField) { 0x00080000, 19, 0x6C })
#define TMC2130_SYNC_MASK                     0x00F00000
#define TMC2130_SYNC_SHIFT                    20
#define TMC2130_SYNC_FIELD                    ((RegisterField) { 0x00F00000, 20, 0x6C })
#define TMC2130_MRES_MASK                     0x0F000000
#define TMC2130_MRES_SHIFT                    24
#define TMC2130_MRES_FIELD                    ((RegisterField) { 0x0F000000, 24, 0x6C })
#define TMC2130_INTPOL_MASK                   0x10000000
#define TMC2130_INTPOL_SHIFT                  28
#define TMC2130_INTPOL_FIELD                  ((RegisterField) { 0x10000000, 28, 0x6C })
#define TMC2130_DEDGE_MASK                    0x20000000
#define TMC2130_DEDGE_SHIFT                   29
#define TMC2130_DEDGE_FIELD                   ((RegisterField) { 0x20000000, 29, 0x6C })
#define TMC2130_DISS2G_MASK                   0x40000000
#define TMC2130_DISS2G_SHIFT                  30
#define TMC2130_DISS2G_FIELD                  ((RegisterField) { 0x40000000, 30, 0x6C })
//#define TMC2130_TOFF_MASK                     0x0000000F
//#define TMC2130_TOFF_SHIFT                    0
//#define TMC2130_TOFF_FIELD                    ((RegisterField) { 0x0000000F, 0, 0x6C })
//#define TMC2130_TFD_2_0_MASK                  0x00000070
//#define TMC2130_TFD_2_0_SHIFT                 4
//#define TMC2130_TFD_2_0_FIELD                 ((RegisterField) { 0x00000070, 4, 0x6C })
//#define TMC2130_OFFSET_MASK                   0x00000780
//#define TMC2130_OFFSET_SHIFT                  7
//#define TMC2130_OFFSET_FIELD                  ((RegisterField) { 0x00000780, 7, 0x6C })
//#define TMC2130_TFD_3_MASK                    0x00000800
//#define TMC2130_TFD_3_SHIFT                   11
//#define TMC2130_TFD_3_FIELD                   ((RegisterField) { 0x00000800, 11, 0x6C })
//#define TMC2130_DISFDCC_MASK                  0x00001000
//#define TMC2130_DISFDCC_SHIFT                 12
//#define TMC2130_DISFDCC_FIELD                 ((RegisterField) { 0x00001000, 12, 0x6C })
//#define TMC2130_RNDTF_MASK                    0x00002000
//#define TMC2130_RNDTF_SHIFT                   13
//#define TMC2130_RNDTF_FIELD                   ((RegisterField) { 0x00002000, 13, 0x6C })
//#define TMC2130_CHM_MASK                      0x00004000
//#define TMC2130_CHM_SHIFT                     14
//#define TMC2130_CHM_FIELD                     ((RegisterField) { 0x00004000, 14, 0x6C })
//#define TMC2130_TBL_MASK                      0x00018000
//#define TMC2130_TBL_SHIFT                     15
//#define TMC2130_TBL_FIELD                     ((RegisterField) { 0x00018000, 15, 0x6C })
//#define TMC2130_VSENSE_MASK                   0x00020000
//#define TMC2130_VSENSE_SHIFT                  17
//#define TMC2130_VSENSE_FIELD                  ((RegisterField) { 0x00020000, 17, 0x6C })
//#define TMC2130_VHIGHFS_MASK                  0x00040000
//#define TMC2130_VHIGHFS_SHIFT                 18
//#define TMC2130_VHIGHFS_FIELD                 ((RegisterField) { 0x00040000, 18, 0x6C })
//#define TMC2130_VHIGHCHM_MASK                 0x00080000
//#define TMC2130_VHIGHCHM_SHIFT                19
//#define TMC2130_VHIGHCHM_FIELD                ((RegisterField) { 0x00080000, 19, 0x6C })
//#define TMC2130_SYNC_MASK                     0x00F00000
//#define TMC2130_SYNC_SHIFT                    20
//#define TMC2130_SYNC_FIELD                    ((RegisterField) { 0x00F00000, 20, 0x6C })
//#define TMC2130_MRES_MASK                     0x0F000000
//#define TMC2130_MRES_SHIFT                    24
//#define TMC2130_MRES_FIELD                    ((RegisterField) { 0x0F000000, 24, 0x6C })
//#define TMC2130_INTPOL_MASK                   0x10000000
//#define TMC2130_INTPOL_SHIFT                  28
//#define TMC2130_INTPOL_FIELD                  ((RegisterField) { 0x10000000, 28, 0x6C })
//#define TMC2130_DEDGE_MASK                    0x20000000
//#define TMC2130_DEDGE_SHIFT                   29
//#define TMC2130_DEDGE_FIELD                   ((RegisterField) { 0x20000000, 29, 0x6C })
//#define TMC2130_DISS2G_MASK                   0x40000000
//#define TMC2130_DISS2G_SHIFT                  30
//#define TMC2130_DISS2G_FIELD                  ((RegisterField) { 0x40000000, 30, 0x6C })
//#define TMC2130_TOFF_MASK                     0x0000000F
//#define TMC2130_TOFF_SHIFT                    0
//#define TMC2130_TOFF_FIELD                    ((RegisterField) { 0x0000000F, 0, 0x6C })
#define TMC2130_HSTRT_MASK                    0x00000070
#define TMC2130_HSTRT_SHIFT                   4
#define TMC2130_HSTRT_FIELD                   ((RegisterField) { 0x00000070, 4, 0x6C })
#define TMC2130_HEND_MASK                     0x00000780
#define TMC2130_HEND_SHIFT                    7
#define TMC2130_HEND_FIELD                    ((RegisterField) { 0x00000780, 7, 0x6C })
//#define TMC2130_RNDTF_MASK                    0x00002000
//#define TMC2130_RNDTF_SHIFT                   13
//#define TMC2130_RNDTF_FIELD                   ((RegisterField) { 0x00002000, 13, 0x6C })
//#define TMC2130_CHM_MASK                      0x00004000
//#define TMC2130_CHM_SHIFT                     14
//#define TMC2130_CHM_FIELD                     ((RegisterField) { 0x00004000, 14, 0x6C })
//#define TMC2130_TBL_MASK                      0x00018000
//#define TMC2130_TBL_SHIFT                     15
//#define TMC2130_TBL_FIELD                     ((RegisterField) { 0x00018000, 15, 0x6C })
//#define TMC2130_VSENSE_MASK                   0x00020000
//#define TMC2130_VSENSE_SHIFT                  17
//#define TMC2130_VSENSE_FIELD                  ((RegisterField) { 0x00020000, 17, 0x6C })
//#define TMC2130_VHIGHFS_MASK                  0x00040000
//#define TMC2130_VHIGHFS_SHIFT                 18
//#define TMC2130_VHIGHFS_FIELD                 ((RegisterField) { 0x00040000, 18, 0x6C })
//#define TMC2130_VHIGHCHM_MASK                 0x00080000
//#define TMC2130_VHIGHCHM_SHIFT                19
//#define TMC2130_VHIGHCHM_FIELD                ((RegisterField) { 0x00080000, 19, 0x6C })
//#define TMC2130_SYNC_MASK                     0x00F00000
//#define TMC2130_SYNC_SHIFT                    20
//#define TMC2130_SYNC_FIELD                    ((RegisterField) { 0x00F00000, 20, 0x6C })
//#define TMC2130_MRES_MASK                     0x0F000000
//#define TMC2130_MRES_SHIFT                    24
//#define TMC2130_MRES_FIELD                    ((RegisterField) { 0x0F000000, 24, 0x6C })
//#define TMC2130_INTPOL_MASK                   0x10000000
//#define TMC2130_INTPOL_SHIFT                  28
//#define TMC2130_INTPOL_FIELD                  ((RegisterField) { 0x10000000, 28, 0x6C })
//#define TMC2130_DEDGE_MASK                    0x20000000
//#define TMC2130_DEDGE_SHIFT                   29
//#define TMC2130_DEDGE_FIELD                   ((RegisterField) { 0x20000000, 29, 0x6C })
//#define TMC2130_DISS2G_MASK                   0x40000000
//#define TMC2130_DISS2G_SHIFT                  30
//#define TMC2130_DISS2G_FIELD                  ((RegisterField) { 0x40000000, 30, 0x6C })
#define TMC2130_SEMIN_MASK                    0x0000000F
#define TMC2130_SEMIN_SHIFT                   0
#define TMC2130_SEMIN_FIELD                   ((RegisterField) { 0x0000000F, 0, 0x6D })
#define TMC2130_SEUP_MASK                     0x00000060
#define TMC2130_SEUP_SHIFT                    5
#define TMC2130_SEUP_FIELD                    ((RegisterField) { 0x00000060, 5, 0x6D })
#define TMC2130_SEMAX_MASK                    0x00000F00
#define TMC2130_SEMAX_SHIFT                   8
#define TMC2130_SEMAX_FIELD                   ((RegisterField) { 0x00000F00, 8, 0x6D })
#define TMC2130_SEDN_MASK                     0x00006000
#define TMC2130_SEDN_SHIFT                    13
#define TMC2130_SEDN_FIELD                    ((RegisterField) { 0x00006000, 13, 0x6D })
#define TMC2130_SEIMIN_MASK                   0x00008000
#define TMC2130_SEIMIN_SHIFT                  15
#define TMC2130_SEIMIN_FIELD                  ((RegisterField) { 0x00008000, 15, 0x6D })
#define TMC2130_SGT_MASK                      0x007F0000
#define TMC2130_SGT_SHIFT                     16
#define TMC2130_SGT_FIELD                     ((RegisterField) { 0x007F0000, 16, 0x6D })
#define TMC2130_SFILT_MASK                    0x01000000
#define TMC2130_SFILT_SHIFT                   24
#define TMC2130_SFILT_FIELD                   ((RegisterField) { 0x01000000, 24, 0x6D })
#define TMC2130_DC_TIME_MASK                  0x000003FF
#define TMC2130_DC_TIME_SHIFT                 0
#define TMC2130_DC_TIME_FIELD                 ((RegisterField) { 0x000003FF, 0, 0x6E })
#define TMC2130_DC_SG_MASK                    0x00FF0000
#define TMC2130_DC_SG_SHIFT                   16
#define TMC2130_DC_SG_FIELD                   ((RegisterField) { 0x00FF0000, 16, 0x6E })
#define TMC2130_SG_RESULT_MASK                0x000003FF
#define TMC2130_SG_RESULT_SHIFT               0
#define TMC2130_SG_RESULT_FIELD               ((RegisterField) { 0x000003FF, 0, 0x6F })
#define TMC2130_FSACTIVE_MASK                 0x00008000
#define TMC2130_FSACTIVE_SHIFT                15
#define TMC2130_FSACTIVE_FIELD                ((RegisterField) { 0x00008000, 15, 0x6F })
#define TMC2130_CS_ACTUAL_MASK                0x001F0000
#define TMC2130_CS_ACTUAL_SHIFT               16
#define TMC2130_CS_ACTUAL_FIELD               ((RegisterField) { 0x001F0000, 16, 0x6F })
#define TMC2130_STALLGUARD_MASK               0x01000000
#define TMC2130_STALLGUARD_SHIFT              24
#define TMC2130_STALLGUARD_FIELD              ((RegisterField) { 0x01000000, 24, 0x6F })
#define TMC2130_OT_MASK                       0x02000000
#define TMC2130_OT_SHIFT                      25
#define TMC2130_OT_FIELD                      ((RegisterField) { 0x02000000, 25, 0x6F })
#define TMC2130_OTPW_MASK                     0x04000000
#define TMC2130_OTPW_SHIFT                    26
#define TMC2130_OTPW_FIELD                    ((RegisterField) { 0x04000000, 26, 0x6F })
#define TMC2130_S2GA_MASK                     0x08000000
#define TMC2130_S2GA_SHIFT                    27
#define TMC2130_S2GA_FIELD                    ((RegisterField) { 0x08000000, 27, 0x6F })
#define TMC2130_S2GB_MASK                     0x10000000
#define TMC2130_S2GB_SHIFT                    28
#define TMC2130_S2GB_FIELD                    ((RegisterField) { 0x10000000, 28, 0x6F })
#define TMC2130_OLA_MASK                      0x20000000
#define TMC2130_OLA_SHIFT                     29
#define TMC2130_OLA_FIELD                     ((RegisterField) { 0x20000000, 29, 0x6F })
#define TMC2130_OLB_MASK                      0x40000000
#define TMC2130_OLB_SHIFT                     30
#define TMC2130_OLB_FIELD                     ((RegisterField) { 0x40000000, 30, 0x6F })
#define TMC2130_STST_MASK                     0x80000000
#define TMC2130_STST_SHIFT                    31
#define TMC2130_STST_FIELD                    ((RegisterField) { 0x80000000, 31, 0x6F })
#define TMC2130_PWM_AMPL_MASK                 0x000000FF
#define TMC2130_PWM_AMPL_SHIFT                0
#define TMC2130_PWM_AMPL_FIELD                ((RegisterField) { 0x000000FF, 0, 0x70 })
#define TMC2130_PWM_GRAD_MASK                 0x0000FF00
#define TMC2130_PWM_GRAD_SHIFT                8
#define TMC2130_PWM_GRAD_FIELD                ((RegisterField) { 0x0000FF00, 8, 0x70 })
#define TMC2130_PWM_FREQ_MASK                 0x00030000
#define TMC2130_PWM_FREQ_SHIFT                16
#define TMC2130_PWM_FREQ_FIELD                ((RegisterField) { 0x00030000, 16, 0x70 })
#define TMC2130_PWM_AUTOSCALE_MASK            0x00040000
#define TMC2130_PWM_AUTOSCALE_SHIFT           18
#define TMC2130_PWM_AUTOSCALE_FIELD           ((RegisterField) { 0x00040000, 18, 0x70 })
#define TMC2130_PWM_SYMMETRIC_MASK            0x00080000
#define TMC2130_PWM_SYMMETRIC_SHIFT           19
#define TMC2130_PWM_SYMMETRIC_FIELD           ((RegisterField) { 0x00080000, 19, 0x70 })
#define TMC2130_FREEWHEEL_MASK                0x00300000
#define TMC2130_FREEWHEEL_SHIFT               20
#define TMC2130_FREEWHEEL_FIELD               ((RegisterField) { 0x00300000, 20, 0x70 })
//#define TMC2130_PWM_AMPL_MASK                 0x000000FF
//#define TMC2130_PWM_AMPL_SHIFT                0
//#define TMC2130_PWM_AMPL_FIELD                ((RegisterField) { 0x000000FF, 0, 0x70 })
//#define TMC2130_PWM_GRAD_MASK                 0x0000FF00
//#define TMC2130_PWM_GRAD_SHIFT                8
//#define TMC2130_PWM_GRAD_FIELD                ((RegisterField) { 0x0000FF00, 8, 0x70 })
//#define TMC2130_PWM_FREQ_MASK                 0x00030000
//#define TMC2130_PWM_FREQ_SHIFT                16
//#define TMC2130_PWM_FREQ_FIELD                ((RegisterField) { 0x00030000, 16, 0x70 })
//#define TMC2130_PWM_AUTOSCALE_MASK            0x00040000
//#define TMC2130_PWM_AUTOSCALE_SHIFT           18
//#define TMC2130_PWM_AUTOSCALE_FIELD           ((RegisterField) { 0x00040000, 18, 0x70 })
//#define TMC2130_PWM_SYMMETRIC_MASK            0x00080000
//#define TMC2130_PWM_SYMMETRIC_SHIFT           19
//#define TMC2130_PWM_SYMMETRIC_FIELD           ((RegisterField) { 0x00080000, 19, 0x70 })
//#define TMC2130_FREEWHEEL_MASK                0x00300000
//#define TMC2130_FREEWHEEL_SHIFT               20
//#define TMC2130_FREEWHEEL_FIELD               ((RegisterField) { 0x00300000, 20, 0x70 })
#define TMC2130_PWM_SCALE_MASK                0x000000FF
#define TMC2130_PWM_SCALE_SHIFT               0
#define TMC2130_PWM_SCALE_FIELD               ((RegisterField) { 0x000000FF, 0, 0x71 })
#define TMC2130_INV_MASK                      0x00000001
#define TMC2130_INV_SHIFT                     0
#define TMC2130_INV_FIELD                     ((RegisterField) { 0x00000001, 0, 0x72 })
#define TMC2130_MAXSPEED_MASK                 0x00000002
#define TMC2130_MAXSPEED_SHIFT                1
#define TMC2130_MAXSPEED_FIELD                ((RegisterField) { 0x00000002, 1, 0x72 })
#define TMC2130_LOST_STEPS_MASK               0x000FFFFF
#define TMC2130_LOST_STEPS_SHIFT              0
#define TMC2130_LOST_STEPS_FIELD              ((RegisterField) { 0x000FFFFF, 0, 0x73 })

#endif
