/*******************************************************************************
* Copyright © 2019 TRINAMIC Motion Control GmbH & Co. KG
* (now owned by Analog Devices Inc.),
*
* Copyright © 2023 Analog Devices Inc. All Rights Reserved. This software is
* proprietary & confidential to Analog Devices, Inc. and its licensors.
*******************************************************************************/


// Autogenerated C header for registers in TMC5272
// Generator version: 1.0

#ifndef TMC5272_REGISTERS
#define TMC5272_REGISTERS

#define MOTOR_ADDR(m)      (0x35 * m)

#define TMC5272_GCONF                0x00
#define TMC5272_GSTAT                0x01
#define TMC5272_IFCNT                0x02
#define TMC5272_SLAVECONF            0x03
#define TMC5272_IOIN                 0x04
#define TMC5272_DRV_CONF             0x05
#define TMC5272_GLOBAL_SCALER        0x06
#define TMC5272_RAMPMODE             0x07
#define TMC5272_MSLUT_ADDR           0x08
#define TMC5272_MSLUT_SEL_START      0x09

										 // motor = 0       motor = 1
#define TMC5272_X_COMPARE(motor)          (0x10 + MOTOR_ADDR(motor))      //      0x10            0x45
#define TMC5272_X_COMPARE_REPEAT(motor)   (0x11 + MOTOR_ADDR(motor))      //      0x11            0x46
#define TMC5272_IHOLD_IRUN(motor)         (0x12 + MOTOR_ADDR(motor))      //      0x12            0x47
#define TMC5272_TPOWERDOWN(motor)         (0x13 + MOTOR_ADDR(motor))      //      0x13            0x48
#define TMC5272_TSTEP(motor)              (0x14 + MOTOR_ADDR(motor))      //      0x14            0x49
#define TMC5272_TPWMTHRS(motor)           (0x15 + MOTOR_ADDR(motor))      //      0x15            0x4A
#define TMC5272_TCOOLTHRS(motor)          (0x16 + MOTOR_ADDR(motor))      //      0x16            0x4B
#define TMC5272_THIGH(motor)              (0x17 + MOTOR_ADDR(motor))      //      0x17            0x4C
#define TMC5272_XACTUAL(motor)            (0x18 + MOTOR_ADDR(motor))      //      0x18            0x4D
#define TMC5272_VACTUAL(motor)            (0x19 + MOTOR_ADDR(motor))      //      0x19            0x4E
#define TMC5272_AACTUAL(motor)            (0x1A + MOTOR_ADDR(motor))      //      0x1A            0x4F
#define TMC5272_VSTART(motor)             (0x1B + MOTOR_ADDR(motor))      //      0x1B            0x50
#define TMC5272_A1(motor)                 (0x1C + MOTOR_ADDR(motor))      //      0x1C            0x51
#define TMC5272_V1(motor)                 (0x1D + MOTOR_ADDR(motor))      //      0x1D            0x52
#define TMC5272_A2(motor)                 (0x1E + MOTOR_ADDR(motor))      //      0x1E            0x53
#define TMC5272_V2(motor)                 (0x1F + MOTOR_ADDR(motor))      //      0x1F            0x54
#define TMC5272_AMAX(motor)               (0x20 + MOTOR_ADDR(motor))      //      0x20            0x55
#define TMC5272_VMAX(motor)               (0x21 + MOTOR_ADDR(motor))      //      0x21            0x56
#define TMC5272_DMAX(motor)               (0x22 + MOTOR_ADDR(motor))      //      0x22            0x57
#define TMC5272_D2(motor)                 (0x23 + MOTOR_ADDR(motor))      //      0x23            0x58
#define TMC5272_D1(motor)                 (0x24 + MOTOR_ADDR(motor))      //      0x24            0x59
#define TMC5272_VSTOP(motor)              (0x25 + MOTOR_ADDR(motor))      //      0x25            0x5A
#define TMC5272_TVMAX(motor)              (0x26 + MOTOR_ADDR(motor))      //      0x26            0x5B
#define TMC5272_TZEROWAIT(motor)          (0x27 + MOTOR_ADDR(motor))      //      0x27            0x5C
#define TMC5272_XTARGET(motor)            (0x28 + MOTOR_ADDR(motor))      //      0x28            0x5D
#define TMC5272_VDCMIN(motor)             (0x29 + MOTOR_ADDR(motor))      //      0x29            0x5E
#define TMC5272_SW_MODE(motor)            (0x2A + MOTOR_ADDR(motor))      //      0x2A            0x5F
#define TMC5272_RAMP_STAT(motor)          (0x2B + MOTOR_ADDR(motor))      //      0x2B            0x60
#define TMC5272_XLATCH(motor)             (0x2C + MOTOR_ADDR(motor))      //      0x2C            0x61
#define TMC5272_POSITION_PI_CTRL(motor)   (0x2D + MOTOR_ADDR(motor))      //      0x2D            0x62
#define TMC5272_X_ENC(motor)              (0x2E + MOTOR_ADDR(motor))      //      0x2E            0x63
#define TMC5272_ENCMODE(motor)            (0x2F + MOTOR_ADDR(motor))      //      0x2F            0x64
#define TMC5272_ENC_CONST(motor)          (0x30 + MOTOR_ADDR(motor))      //      0x30            0x65
#define TMC5272_ENC_STATUS(motor)         (0x31 + MOTOR_ADDR(motor))      //      0x31            0x66
#define TMC5272_ENC_LATCH(motor)          (0x32 + MOTOR_ADDR(motor))      //      0x32            0x67
#define TMC5272_ENC_DEVIATION(motor)      (0x33 + MOTOR_ADDR(motor))      //      0x33            0x68
#define TMC5272_VIRTUAL_STOP_L(motor)     (0x34 + MOTOR_ADDR(motor))      //      0x34            0x69
#define TMC5272_VIRTUAL_STOP_R(motor)     (0x35 + MOTOR_ADDR(motor))      //      0x35            0x6A
#define TMC5272_MSCNT(motor)              (0x36 + MOTOR_ADDR(motor))      //      0x36            0x6B
#define TMC5272_MSCURACT(motor)           (0x37 + MOTOR_ADDR(motor))      //      0x37            0x6C
#define TMC5272_CHOPCONF(motor)           (0x38 + MOTOR_ADDR(motor))      //      0x38            0x6D
#define TMC5272_COOLCONF(motor)           (0x39 + MOTOR_ADDR(motor))      //      0x39            0x6E
#define TMC5272_DCCTRL(motor)             (0x3A + MOTOR_ADDR(motor))      //      0x3A            0x6F
#define TMC5272_DRV_STATUS(motor)         (0x3B + MOTOR_ADDR(motor))      //      0x3B            0x70
#define TMC5272_PWMCONF(motor)            (0x3C + MOTOR_ADDR(motor))      //      0x3C            0x71
#define TMC5272_PWM_SCALE(motor)          (0x3D + MOTOR_ADDR(motor))      //      0x3D            0x72
#define TMC5272_PWM_AUTO(motor)           (0x3E + MOTOR_ADDR(motor))      //      0x3E            0x73
#define TMC5272_SG4_THRS(motor)           (0x3F + MOTOR_ADDR(motor))      //      0x3F            0x74
#define TMC5272_SG4_RESULT(motor)         (0x40 + MOTOR_ADDR(motor))      //      0x40            0x75
#define TMC5272_SG4_IND(motor)            (0x41 + MOTOR_ADDR(motor))      //      0x41            0x76


#endif
