/*
 *  TMC6630_Fields.h
 *  Author: LK
 *  Generated by MaskShiftConverter (unchecked)
 */

#ifndef TMC6630_FIELDS_H
#define TMC6630_FIELDS_H

#define TMC6630_SI_TYPE_MASK                         0xFFFFFFFF // CHIPINFO_DATA //
#define TMC6630_SI_TYPE_SHIFT                        0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_SI_VERSION_MASK                      0xFFFFFFFF // CHIPINFO_DATA //
#define TMC6630_SI_VERSION_SHIFT                     0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_SI_DATE_MASK                         0xFFFFFFFF // CHIPINFO_DATA //
#define TMC6630_SI_DATE_SHIFT                        0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_SI_TIME_MASK                         0xFFFFFFFF // CHIPINFO_DATA //
#define TMC6630_SI_TIME_SHIFT                        0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_SI_VARIANT_MASK                      0xFFFFFFFF // CHIPINFO_DATA //
#define TMC6630_SI_VARIANT_SHIFT                     0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_CHIP_INFO_ADDRESS_MASK               0xFF // CHIPINFO_ADDR //
#define TMC6630_CHIP_INFO_ADDRESS_SHIFT              0 // min.: 0, max.: 4, default: 0
#define TMC6630_DISABLE_S2G_MASK                     0x01 // GENERAL_CONF // ---
#define TMC6630_DISABLE_S2G_SHIFT                    0 // min.: 0, max.: 1, default: 0
#define TMC6630_DISABLE_S2VS_MASK                    0x02 // GENERAL_CONF // ---
#define TMC6630_DISABLE_S2VS_SHIFT                   1 // min.: 0, max.: 1, default: 0
#define TMC6630_SHORT_DELAY_MASK                     0x04 // GENERAL_CONF // ---
#define TMC6630_SHORT_DELAY_SHIFT                    2 // min.: 0, max.: 1, default: 0
#define TMC6630_PROTECT_PARALLEL_MASK                0x08 // GENERAL_CONF // ---
#define TMC6630_PROTECT_PARALLEL_SHIFT               3 // min.: 0, max.: 1, default: 0
#define TMC6630_SHORT_RETRY_MASK                     0x30 // GENERAL_CONF //
#define TMC6630_SHORT_RETRY_SHIFT                    4 // min.: 0, max.: 3, default: 0
#define TMC6630_FILTER_SHORT_MASK                    0xC0 // GENERAL_CONF //
#define TMC6630_FILTER_SHORT_SHIFT                   6 // min.: 0, max.: 3, default: 0
#define TMC6630_S2G_DAC_MASK                         0x0F00 // GENERAL_CONF //
#define TMC6630_S2G_DAC_SHIFT                        8 // min.: 0, max.: 15, default: 0
#define TMC6630_S2VS_DAC_MASK                        0xF000 // GENERAL_CONF //
#define TMC6630_S2VS_DAC_SHIFT                       12 // min.: 0, max.: 15, default: 0
//#define TMC6630_SHORT_DELAY_MASK                   0x030000 // GENERAL_CONF //
//#define TMC6630_SHORT_DELAY_SHIFT                  16 // min.: 0, max.: 3, default: 0
#define TMC6630_UNUSED_MASK                          0x040000 // GENERAL_CONF //
#define TMC6630_UNUSED_SHIFT                         18 // min.: 0, max.: 1, default: 0
#define TMC6630_AMPLIFICATION_MASK                   0x080000 // GENERAL_CONF //
#define TMC6630_AMPLIFICATION_SHIFT                  19 // min.: 0, max.: 1, default: 0
#define TMC6630_TEMP_SHUTOFF_LIMIT_MASK              0x300000 // GENERAL_CONF //
#define TMC6630_TEMP_SHUTOFF_LIMIT_SHIFT             20 // min.: 0, max.: 3, default: 0
#define TMC6630_FILT_ISENSE_MASK                     0xC00000 // GENERAL_CONF //
#define TMC6630_FILT_ISENSE_SHIFT                    22 // min.: 0, max.: 3, default: 0
#define TMC6630_TST_MODE_ON_MASK                     0x01000000 // GENERAL_CONF //
#define TMC6630_TST_MODE_ON_SHIFT                    24 // min.: 0, max.: 1, default: 0
#define TMC6630_DISABLE_EXT_DIR_MASK                 0x02000000 // GENERAL_CONF //
#define TMC6630_DISABLE_EXT_DIR_SHIFT                25 // min.: 0, max.: 1, default: 0
//#define TMC6630_UNUSED_MASK                        0x04000000 // GENERAL_CONF //
//#define TMC6630_UNUSED_SHIFT                       26 // min.: 0, max.: 1, default: 0
//#define //TMC6630_UNUSED_MASK                      0x08000000 // GENERAL_CONF //
//#define //TMC6630_UNUSED_SHIFT                     27 // min.: 0, max.: 1, default: 0
//#define ////TMC6630_UNUSED_MASK                    0x10000000 // GENERAL_CONF //
//#define ////TMC6630_UNUSED_SHIFT                   28 // min.: 0, max.: 1, default: 0
//#define //////TMC6630_UNUSED_MASK                  0x20000000 // GENERAL_CONF //
//#define //////TMC6630_UNUSED_SHIFT                 29 // min.: 0, max.: 1, default: 0
//#define ////////TMC6630_UNUSED_MASK                0x40000000 // GENERAL_CONF //
//#define ////////TMC6630_UNUSED_SHIFT               30 // min.: 0, max.: 1, default: 0
//#define //////////TMC6630_UNUSED_MASK              0x80000000 // GENERAL_CONF //
//#define //////////TMC6630_UNUSED_SHIFT             31 // min.: 0, max.: 1, default: 0
#define TMC6630_LS_U_SHORT_MASK                      0x01 // STATUS //
#define TMC6630_LS_U_SHORT_SHIFT                     0 // min.: 0, max.: 1, default: 0
#define TMC6630_HS_U_SHORT_MASK                      0x02 // STATUS //
#define TMC6630_HS_U_SHORT_SHIFT                     1 // min.: 0, max.: 1, default: 0
#define TMC6630_LS_V_SHORT_MASK                      0x04 // STATUS //
#define TMC6630_LS_V_SHORT_SHIFT                     2 // min.: 0, max.: 1, default: 0
#define TMC6630_HS_V_SHORT_MASK                      0x08 // STATUS //
#define TMC6630_HS_V_SHORT_SHIFT                     3 // min.: 0, max.: 1, default: 0
#define TMC6630_LS_W_SHORT_MASK                      0x10 // STATUS //
#define TMC6630_LS_W_SHORT_SHIFT                     4 // min.: 0, max.: 1, default: 0
#define TMC6630_HS_W_SHORT_MASK                      0x20 // STATUS //
#define TMC6630_HS_W_SHORT_SHIFT                     5 // min.: 0, max.: 1, default: 0
#define TMC6630_TEMP_PREWARNING_MASK                 0x40 // STATUS //
#define TMC6630_TEMP_PREWARNING_SHIFT                6 // min.: 0, max.: 1, default: 0
#define TMC6630_TEMP_SHUTOFF_MASK                    0x80 // STATUS //
#define TMC6630_TEMP_SHUTOFF_SHIFT                   7 // min.: 0, max.: 1, default: 0
#define TMC6630_STST_MASK                            0x0100 // STATUS //
#define TMC6630_STST_SHIFT                           8 // min.: 0, max.: 1, default: 0
#define TMC6630_UV_CP_MASK                           0x0200 // STATUS //
#define TMC6630_UV_CP_SHIFT                          9 // min.: 0, max.: 1, default: 0
#define TMC6630_TONE_ACTIVE_MASK                     0x0400 // STATUS //
#define TMC6630_TONE_ACTIVE_SHIFT                    10 // min.: 0, max.: 1, default: 0
#define TMC6630_SHORTS_LS_DETECTED_MASK              0x0800 // STATUS //
#define TMC6630_SHORTS_LS_DETECTED_SHIFT             11 // min.: 0, max.: 1, default: 0
#define TMC6630_SHORTS_HS_DETECTED_MASK              0x1000 // STATUS //
#define TMC6630_SHORTS_HS_DETECTED_SHIFT             12 // min.: 0, max.: 1, default: 0
#define TMC6630_STDBY_STATE_MASK                     0x6000 // STATUS //
#define TMC6630_STDBY_STATE_SHIFT                    13 // min.: 0, max.: 3, default: 0
#define TMC6630_RST_DONE_MASK                        0x8000 // STATUS //
#define TMC6630_RST_DONE_SHIFT                       15 // min.: 0, max.: 1, default: 0
#define TMC6630_LS_U_SHORT_SELECT_MASK               0x010000 // STATUS //
#define TMC6630_LS_U_SHORT_SELECT_SHIFT              16 // min.: 0, max.: 1, default: 0
#define TMC6630_HS_U_SHORT_SELECT_MASK               0x020000 // STATUS //
#define TMC6630_HS_U_SHORT_SELECT_SHIFT              17 // min.: 0, max.: 1, default: 0
#define TMC6630_LS_V_SHORT_SELECT_MASK               0x040000 // STATUS //
#define TMC6630_LS_V_SHORT_SELECT_SHIFT              18 // min.: 0, max.: 1, default: 0
#define TMC6630_HS_V_SHORT_SELECT_MASK               0x080000 // STATUS //
#define TMC6630_HS_V_SHORT_SELECT_SHIFT              19 // min.: 0, max.: 1, default: 0
#define TMC6630_LS_W_SHORT_SELECT_MASK               0x100000 // STATUS //
#define TMC6630_LS_W_SHORT_SELECT_SHIFT              20 // min.: 0, max.: 1, default: 0
#define TMC6630_HS_W_SHORT_SELECT_MASK               0x200000 // STATUS //
#define TMC6630_HS_W_SHORT_SELECT_SHIFT              21 // min.: 0, max.: 1, default: 0
#define TMC6630_TEMP_PREWARNING_SELECT_MASK          0x400000 // STATUS //
#define TMC6630_TEMP_PREWARNING_SELECT_SHIFT         22 // min.: 0, max.: 1, default: 0
#define TMC6630_TEMP_SHUTOFF_SELECT_MASK             0x800000 // STATUS //
#define TMC6630_TEMP_SHUTOFF_SELECT_SHIFT            23 // min.: 0, max.: 1, default: 0
#define TMC6630_STST_SELECT_MASK                     0x01000000 // STATUS //
#define TMC6630_STST_SELECT_SHIFT                    24 // min.: 0, max.: 1, default: 0
#define TMC6630_UV_CP_SELECT_MASK                    0x02000000 // STATUS //
#define TMC6630_UV_CP_SELECT_SHIFT                   25 // min.: 0, max.: 1, default: 0
#define TMC6630_SHORTS_LS_DETECTED_SELECT_MASK       0x08000000 // STATUS //
#define TMC6630_SHORTS_LS_DETECTED_SELECT_SHIFT      27 // min.: 0, max.: 1, default: 0
#define TMC6630_SHORTS_HS_DETECTED_SELECT_MASK       0x10000000 // STATUS //
#define TMC6630_SHORTS_HS_DETECTED_SELECT_SHIFT      28 // min.: 0, max.: 1, default: 0
#define TMC6630_RST_DONE_SELECT_MASK                 0x80000000 // STATUS //
#define TMC6630_RST_DONE_SELECT_SHIFT                31 // min.: 0, max.: 1, default: 0
#define TMC6630_DRV_EN_MASK                          0x01 // INPUT_RAW //
#define TMC6630_DRV_EN_SHIFT                         0 // min.: 0, max.: 1, default: 0
#define TMC6630_EXT_GATE_SG_ON_MASK                  0x02 // INPUT_RAW //
#define TMC6630_EXT_GATE_SG_ON_SHIFT                 1 // min.: 0, max.: 1, default: 0
#define TMC6630_BL_U_INPUT_MASK                      0x04 // INPUT_RAW //
#define TMC6630_BL_U_INPUT_SHIFT                     2 // min.: 0, max.: 1, default: 0
#define TMC6630_BH_U_INPUT_MASK                      0x08 // INPUT_RAW //
#define TMC6630_BH_U_INPUT_SHIFT                     3 // min.: 0, max.: 1, default: 0
#define TMC6630_BL_V_INPUT_MASK                      0x10 // INPUT_RAW //
#define TMC6630_BL_V_INPUT_SHIFT                     4 // min.: 0, max.: 1, default: 0
#define TMC6630_BH_V_INPUT_MASK                      0x20 // INPUT_RAW //
#define TMC6630_BH_V_INPUT_SHIFT                     5 // min.: 0, max.: 1, default: 0
#define TMC6630_BL_W_INPUT_MASK                      0x40 // INPUT_RAW //
#define TMC6630_BL_W_INPUT_SHIFT                     6 // min.: 0, max.: 1, default: 0
#define TMC6630_BH_W_INPUT_MASK                      0x80 // INPUT_RAW //
#define TMC6630_BH_W_INPUT_SHIFT                     7 // min.: 0, max.: 1, default: 0
#define TMC6630_S2G_U_MASK                           0x0100 // INPUT_RAW //
#define TMC6630_S2G_U_SHIFT                          8 // min.: 0, max.: 1, default: 0
#define TMC6630_S2G_V_MASK                           0x0200 // INPUT_RAW //
#define TMC6630_S2G_V_SHIFT                          9 // min.: 0, max.: 1, default: 0
#define TMC6630_S2G_W_MASK                           0x0400 // INPUT_RAW //
#define TMC6630_S2G_W_SHIFT                          10 // min.: 0, max.: 1, default: 0
#define TMC6630_S2VS_U_MASK                          0x0800 // INPUT_RAW //
#define TMC6630_S2VS_U_SHIFT                         11 // min.: 0, max.: 1, default: 0
#define TMC6630_S2VS_V_MASK                          0x1000 // INPUT_RAW //
#define TMC6630_S2VS_V_SHIFT                         12 // min.: 0, max.: 1, default: 0
#define TMC6630_S2VS_W_MASK                          0x2000 // INPUT_RAW //
#define TMC6630_S2VS_W_SHIFT                         13 // min.: 0, max.: 1, default: 0
//#define TMC6630_UV_CP_MASK                         0x4000 // INPUT_RAW //
//#define TMC6630_UV_CP_SHIFT                        14 // min.: 0, max.: 1, default: 0
#define TMC6630_OTP_IN_MASK                          0x8000 // INPUT_RAW //
#define TMC6630_OTP_IN_SHIFT                         15 // min.: 0, max.: 1, default: 0
#define TMC6630_TEMP_PRE_MASK                        0x010000 // INPUT_RAW //
#define TMC6630_TEMP_PRE_SHIFT                       16 // min.: 0, max.: 1, default: 0
#define TMC6630_OV136_MASK                           0x020000 // INPUT_RAW //
#define TMC6630_OV136_SHIFT                          17 // min.: 0, max.: 1, default: 0
#define TMC6630_OV143_MASK                           0x040000 // INPUT_RAW //
#define TMC6630_OV143_SHIFT                          18 // min.: 0, max.: 1, default: 0
#define TMC6630_OV150_MASK                           0x080000 // INPUT_RAW //
#define TMC6630_OV150_SHIFT                          19 // min.: 0, max.: 1, default: 0
#define TMC6630_COMP_U_VW_MASK                       0x100000 // INPUT_RAW //
#define TMC6630_COMP_U_VW_SHIFT                      20 // min.: 0, max.: 1, default: 0
#define TMC6630_COMP_V_UW_MASK                       0x200000 // INPUT_RAW //
#define TMC6630_COMP_V_UW_SHIFT                      21 // min.: 0, max.: 1, default: 0
#define TMC6630_COMP_W_UV_MASK                       0x400000 // INPUT_RAW //
#define TMC6630_COMP_W_UV_SHIFT                      22 // min.: 0, max.: 1, default: 0
#define TMC6630_COMP_DAC_MASK                        0x800000 // INPUT_RAW //
#define TMC6630_COMP_DAC_SHIFT                       23 // min.: 0, max.: 1, default: 0
#define TMC6630_PWM_CNTL_MASK                        0x01000000 // INPUT_RAW //
#define TMC6630_PWM_CNTL_SHIFT                       24 // min.: 0, max.: 1, default: 0
#define TMC6630_CLK_WD_ERROR_MASK                    0x02000000 // INPUT_RAW //
#define TMC6630_CLK_WD_ERROR_SHIFT                   25 // min.: 0, max.: 1, default: 0
#define TMC6630_INPUTS_RAW_26_MASK                   0x04000000 // INPUT_RAW // ---
#define TMC6630_INPUTS_RAW_26_SHIFT                  26 // min.: 0, max.: 1, default: 0
#define TMC6630_INPUTS_RAW_27_MASK                   0x08000000 // INPUT_RAW // ---
#define TMC6630_INPUTS_RAW_27_SHIFT                  27 // min.: 0, max.: 1, default: 0
#define TMC6630_INPUTS_RAW_28_MASK                   0x10000000 // INPUT_RAW // ---
#define TMC6630_INPUTS_RAW_28_SHIFT                  28 // min.: 0, max.: 1, default: 0
#define TMC6630_INPUTS_RAW_29_MASK                   0x20000000 // INPUT_RAW // ---
#define TMC6630_INPUTS_RAW_29_SHIFT                  29 // min.: 0, max.: 1, default: 0
#define TMC6630_INPUTS_RAW_30_MASK                   0x40000000 // INPUT_RAW // ---
#define TMC6630_INPUTS_RAW_30_SHIFT                  30 // min.: 0, max.: 1, default: 0
#define TMC6630_INPUTS_RAW_31_MASK                   0x80000000 // INPUT_RAW // ---
#define TMC6630_INPUTS_RAW_31_SHIFT                  31 // min.: 0, max.: 1, default: 0
#define TMC6630_COMP_RAW_U_MASK                      0x03FF // COMP_RAW_WVU //
#define TMC6630_COMP_RAW_U_SHIFT                     0 // min.: 0, max.: 1023, default: 0
#define TMC6630_COMP_RAW_V_MASK                      0x0FFC00 // COMP_RAW_WVU //
#define TMC6630_COMP_RAW_V_SHIFT                     10 // min.: 0, max.: 1023, default: 0
#define TMC6630_COMP_RAW_W_MASK                      0x3FF00000 // COMP_RAW_WVU //
#define TMC6630_COMP_RAW_W_SHIFT                     20 // min.: 0, max.: 1023, default: 0
#define TMC6630_U_BEMF_MASK                          0xFFFF // ADC_RAW_N_CALCULATED_U_BEMF //
#define TMC6630_U_BEMF_SHIFT                         0 // min.: 0, max.: 65535, default: 0
#define TMC6630_ADC_RAW_N_CALCULATED_MASK            0xFFFF0000 // ADC_RAW_N_CALCULATED_U_BEMF //
#define TMC6630_ADC_RAW_N_CALCULATED_SHIFT           16 // min.: 0, max.: 65535, default: 0
#define TMC6630_FILT_LENGTH_NCALC_MASK               0xFF // Z_BLK_CNTS_FILT_LENGTH_NCALC //
#define TMC6630_FILT_LENGTH_NCALC_SHIFT              0 // min.: 0, max.: 8, default: 0
#define TMC6630_Z_BLK_CNTS_MASK                      0xFF00 // Z_BLK_CNTS_FILT_LENGTH_NCALC //
#define TMC6630_Z_BLK_CNTS_SHIFT                     8 // min.: 0, max.: 255, default: 0
#define TMC6630_IB_COMP_MASK                         0xFFFF // AUTO_ZERO_VAL_IB_COMP //
#define TMC6630_IB_COMP_SHIFT                        0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_AUTO_ZERO_VAL_MASK                   0xFFFF0000 // AUTO_ZERO_VAL_IB_COMP //
#define TMC6630_AUTO_ZERO_VAL_SHIFT                  16 // min.: -32768, max.: 32767, default: 0
#define TMC6630_FILT_LENGTH_IB_MASK                  0xFF // IB_OFFSET_CONF_FILT_LENGTH //
#define TMC6630_FILT_LENGTH_IB_SHIFT                 0 // min.: 0, max.: 8, default: 0
#define TMC6630_IB_CONF_MASK                         0x0300 // IB_OFFSET_CONF_FILT_LENGTH //
#define TMC6630_IB_CONF_SHIFT                        8 // min.: 0, max.: 3, default: 0
#define TMC6630_EXT_COMP_VAL_0_MASK                  0x1000 // IB_OFFSET_CONF_FILT_LENGTH //
#define TMC6630_EXT_COMP_VAL_0_SHIFT                 12 // min.: 0, max.: 1, default: 0
#define TMC6630_EXT_COMP_VAL_1_MASK                  0x2000 // IB_OFFSET_CONF_FILT_LENGTH //
#define TMC6630_EXT_COMP_VAL_1_SHIFT                 13 // min.: 0, max.: 1, default: 0
#define TMC6630_EXT_COMP_VAL_2_MASK                  0x4000 // IB_OFFSET_CONF_FILT_LENGTH //
#define TMC6630_EXT_COMP_VAL_2_SHIFT                 14 // min.: 0, max.: 1, default: 0
#define TMC6630_EXT_COMP_VAL_3_MASK                  0x8000 // IB_OFFSET_CONF_FILT_LENGTH //
#define TMC6630_EXT_COMP_VAL_3_SHIFT                 15 // min.: 0, max.: 1, default: 0
#define TMC6630_IB_OFFSET_MASK                       0xFFFF0000 // IB_OFFSET_CONF_FILT_LENGTH //
#define TMC6630_IB_OFFSET_SHIFT                      16 // min.: -32768, max.: 32767, default: 0
#define TMC6630_ADC_IB_FILTERED_MASK                 0xFFFF // DIR_HALL_ACTUAL_ADC_IB //
#define TMC6630_ADC_IB_FILTERED_SHIFT                0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_HALL_ACTUAL_MASK                     0xFF0000 // DIR_HALL_ACTUAL_ADC_IB //
#define TMC6630_HALL_ACTUAL_SHIFT                    16 // min.: 0, max.: 255, default: 0
#define TMC6630_DIR_MASK                             0x01000000 // DIR_HALL_ACTUAL_ADC_IB //
#define TMC6630_DIR_SHIFT                            24 // min.: 0, max.: 255, default: 0
#define TMC6630_TRIGGER_HALL_STATE_MASK              0xFF // TRIGGER_PWM_CNT_SG_HALL_STATE //
#define TMC6630_TRIGGER_HALL_STATE_SHIFT             0 // min.: 0, max.: 255, default: 0
#define TMC6630_TRIGGER_SG_MASK                      0xFF00 // TRIGGER_PWM_CNT_SG_HALL_STATE //
#define TMC6630_TRIGGER_SG_SHIFT                     8 // min.: 0, max.: 255, default: 0
#define TMC6630_TRIGGER_PWM_CNT_MASK                 0xFF0000 // TRIGGER_PWM_CNT_SG_HALL_STATE //
#define TMC6630_TRIGGER_PWM_CNT_SHIFT                16 // min.: 0, max.: 255, default: 0
#define TMC6630_ANAOUT_SW_MASK                       0xFF000000 // TRIGGER_PWM_CNT_SG_HALL_STATE //
#define TMC6630_ANAOUT_SW_SHIFT                      24 // min.: 0, max.: 255, default: 0
#define TMC6630_START_PWM_VALUE_MASK                 0xFFFF // START_CONF //
#define TMC6630_START_PWM_VALUE_SHIFT                0 // min.: 0, max.: 32767, default: 0
#define TMC6630_START_ALIGNMENT_CNT_MASK             0xFFFF0000 // START_CONF // Number of CROSSING_CNTS_MAX-Intervals during Startphase. (Number of PWM cycles during Inductance SensingMode.)
#define TMC6630_START_ALIGNMENT_CNT_SHIFT            16 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_EXT_VALUE_MASK                   0xFFFF // HALL_VALUE_PWM_EXT_VALUE //
#define TMC6630_PWM_EXT_VALUE_SHIFT                  0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_PWM_IN_DIR_MASK                      0x010000 // HALL_VALUE_PWM_EXT_VALUE //
#define TMC6630_PWM_IN_DIR_SHIFT                     16 // min.: 0, max.: 1, default: 0
#define TMC6630_HALL_EXTSTART_VALUE_MASK             0xFF000000 // HALL_VALUE_PWM_EXT_VALUE //
#define TMC6630_HALL_EXTSTART_VALUE_SHIFT            24 // min.: 0, max.: 255, default: 0
#define TMC6630_MOTION_MODE_MASK                     0xFF // OP_MODE //
#define TMC6630_MOTION_MODE_SHIFT                    0 // min.: 0, max.: 17, default: 0
#define TMC6630_STOP_MODE_MASK                       0xFF00 // OP_MODE //
#define TMC6630_STOP_MODE_SHIFT                      8 // min.: 0, max.: 64, default: 0
#define TMC6630_COMMUTATION_MODE_MASK                0xFF0000 // OP_MODE //
#define TMC6630_COMMUTATION_MODE_SHIFT               16 // min.: 0, max.: 8, default: 0
#define TMC6630_SOUND_EN_MASK                        0x01 // PWM_BBM_CHOP_OPTS //
#define TMC6630_SOUND_EN_SHIFT                       0 // min.: 0, max.: 1, default: 0
#define TMC6630_USE_DYNAMIC_PWM_MASK                 0x02 // PWM_BBM_CHOP_OPTS //
#define TMC6630_USE_DYNAMIC_PWM_SHIFT                1 // min.: 0, max.: 1, default: 0
#define TMC6630_USE_PWM_LIMIT_DDT_MASK               0x04 // PWM_BBM_CHOP_OPTS //
#define TMC6630_USE_PWM_LIMIT_DDT_SHIFT              2 // min.: 0, max.: 1, default: 0
#define TMC6630_USE_AUTO_BLK_MASK                    0x08 // PWM_BBM_CHOP_OPTS //
#define TMC6630_USE_AUTO_BLK_SHIFT                   3 // min.: 0, max.: 1, default: 0
#define TMC6630_USE_EXT_GATE_SG_MASK                 0x10 // PWM_BBM_CHOP_OPTS //
#define TMC6630_USE_EXT_GATE_SG_SHIFT                4 // min.: 0, max.: 1, default: 0
#define TMC6630_EXT_GATE_SG_DIFF_ENABLE_MASK         0x20 // PWM_BBM_CHOP_OPTS //
#define TMC6630_EXT_GATE_SG_DIFF_ENABLE_SHIFT        5 // min.: 0, max.: 1, default: 0
#define TMC6630_PWM_MAXCNTLIM_MASK                   0xC0 // PWM_BBM_CHOP_OPTS //
#define TMC6630_PWM_MAXCNTLIM_SHIFT                  6 // min.: 0, max.: 3, default: 0
#define TMC6630_CHOP_OPTS_MASK                       0x0700 // PWM_BBM_CHOP_OPTS //
#define TMC6630_CHOP_OPTS_SHIFT                      8 // min.: 0, max.: 4, default: 0
#define TMC6630_PWM_BBM_L_MASK                       0xFF0000 // PWM_BBM_CHOP_OPTS //
#define TMC6630_PWM_BBM_L_SHIFT                      16 // min.: 0, max.: 255, default: 0
#define TMC6630_PWM_BBM_H_MASK                       0xFF000000 // PWM_BBM_CHOP_OPTS //
#define TMC6630_PWM_BBM_H_SHIFT                      24 // min.: 0, max.: 255, default: 0
#define TMC6630_PWM_MAXCNT_MASK                      0xFFFF // PWM_FREQ_MAXCNT //
#define TMC6630_PWM_MAXCNT_SHIFT                     0 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_FREQ_MASK                        0x070000 // PWM_FREQ_MAXCNT //
#define TMC6630_PWM_FREQ_SHIFT                       16 // min.: 0, max.: 7, default: 0
#define TMC6630_USE_PWM_FREQ_DIRECTLY_MASK           0x080000 // PWM_FREQ_MAXCNT //
#define TMC6630_USE_PWM_FREQ_DIRECTLY_SHIFT          5 // min.: 0, max.: 1, default: 0
#define TMC6630_CLK_FREQ_MASK                        0x03000000 // PWM_FREQ_MAXCNT //
#define TMC6630_CLK_FREQ_SHIFT                       24 // min.: 0, max.: 3, default: 0
#define TMC6630_CLK_CORE_MASK                        0x08000000 // PWM_FREQ_MAXCNT //
#define TMC6630_CLK_CORE_SHIFT                       5 // min.: 0, max.: 1, default: 0
#define TMC6630_PWM_LIMIT_LOW_MASK                   0xFFFF // PWM_LIMIT_HIGH_LOW //
#define TMC6630_PWM_LIMIT_LOW_SHIFT                  0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_PWM_LIMIT_HIGH_MASK                  0xFFFF0000 // PWM_LIMIT_HIGH_LOW //
#define TMC6630_PWM_LIMIT_HIGH_SHIFT                 16 // min.: -32768, max.: 32767, default: 0
#define TMC6630_PWM_LIMIT_DDT_MASK                   0xFFFFFFFF // PWM_LIMIT_DDT //
#define TMC6630_PWM_LIMIT_DDT_SHIFT                  0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_PWM_MIN_STALL_VALUE_MASK             0xFFFF // PWM_AUTO_SWITCH_MIN_STALL_VALUE //
#define TMC6630_PWM_MIN_STALL_VALUE_SHIFT            0 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_AUTO_SWITCH_MASK                 0xFFFF0000 // PWM_AUTO_SWITCH_MIN_STALL_VALUE //
#define TMC6630_PWM_AUTO_SWITCH_SHIFT                16 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_VALUE_INT_MASK                   0xFFFF // PWM_MAXCNT_INT_VALUE_INT //
#define TMC6630_PWM_VALUE_INT_SHIFT                  0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_PWM_MAXCNT_INT_MASK                  0xFFFF0000 // PWM_MAXCNT_INT_VALUE_INT //
#define TMC6630_PWM_MAXCNT_INT_SHIFT                 16 // min.: 0, max.: 65535, default: 0
#define TMC6630_CNT_PWM_CYCLES_MASK                  0xFFFF // PWM_VALUE_DEBUG //
#define TMC6630_CNT_PWM_CYCLES_SHIFT                 0 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_VALUE_RELATIV_ACTUAL_MASK        0xFFFF0000 // PWM_VALUE_DEBUG //
#define TMC6630_PWM_VALUE_RELATIV_ACTUAL_SHIFT       16 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_VALUE_RELATIV_MASK               0xFFFF // PWM_VALUE_RELATIV //
#define TMC6630_PWM_VALUE_RELATIV_SHIFT              0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_TONE_FREQ_MASK                       0xFFFF // SOUND_OPTS // tone_frequency [Hz] = PWM-frequency / TONE_FREQ
#define TMC6630_TONE_FREQ_SHIFT                      0 // min.: 0, max.: 65535, default: 0
#define TMC6630_TONE_LOUDNESS_MASK                   0xFF0000 // SOUND_OPTS // PWM_VALUE_OFFSET = TONE_LOUDNESS * 128
#define TMC6630_TONE_LOUDNESS_SHIFT                  16 // min.: 0, max.: 255, default: 0
#define TMC6630_TONE_DURATION_MASK                   0xFF000000 // SOUND_OPTS //
#define TMC6630_TONE_DURATION_SHIFT                  24 // min.: 0, max.: 255, default: 0
#define TMC6630_LED_BLUE_MASK                        0xFF // LED_CONF //
#define TMC6630_LED_BLUE_SHIFT                       0 // min.: 0, max.: 255, default: 0
#define TMC6630_LED_GREEN_MASK                       0xFF00 // LED_CONF //
#define TMC6630_LED_GREEN_SHIFT                      8 // min.: 0, max.: 255, default: 0
#define TMC6630_LED_RED_MASK                         0xFF0000 // LED_CONF //
#define TMC6630_LED_RED_SHIFT                        16 // min.: 0, max.: 255, default: 0
#define TMC6630_LED_FREQ_MASK                        0x0F000000 // LED_CONF //
#define TMC6630_LED_FREQ_SHIFT                       24 // min.: 0, max.: 15, default: 0
#define TMC6630_SINCOMM_PHI_MASK                     0xFFFF // SINCOMM_AMPLITUDE_PHI //
#define TMC6630_SINCOMM_PHI_SHIFT                    0 // min.: 0, max.: 65535, default: 0
#define TMC6630_SINCOMM_AMPLITUDE_MASK               0xFFFF0000 // SINCOMM_AMPLITUDE_PHI //
#define TMC6630_SINCOMM_AMPLITUDE_SHIFT              16 // min.: 0, max.: 65535, default: 0
#define TMC6630_SINCOMM_COS_MASK                     0xFFFF // SINCOMM_SIN_COS //
#define TMC6630_SINCOMM_COS_SHIFT                    0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_SINCOMM_SIN_MASK                     0xFFFF0000 // SINCOMM_SIN_COS //
#define TMC6630_SINCOMM_SIN_SHIFT                    16 // min.: -32768, max.: 32767, default: 0
#define TMC6630_SINCOMM_SCALED_W_MASK                0x03FF // SINCOMM_SCALED_U_V_W //
#define TMC6630_SINCOMM_SCALED_W_SHIFT               0 // min.: 0, max.: 65535, default: 0
#define TMC6630_SINCOMM_SCALED_V_MASK                0x0FFC00 // SINCOMM_SCALED_U_V_W //
#define TMC6630_SINCOMM_SCALED_V_SHIFT               10 // min.: 0, max.: 65535, default: 0
#define TMC6630_SINCOMM_SCALED_U_MASK                0x3FF00000 // SINCOMM_SCALED_U_V_W //
#define TMC6630_SINCOMM_SCALED_U_SHIFT               20 // min.: 0, max.: 65535, default: 0
#define TMC6630_SINCOMM_DIRECT_W_MASK                0x03FF // SINCOMM_DIRECT_U_V_W //
#define TMC6630_SINCOMM_DIRECT_W_SHIFT               0 // min.: 0, max.: 65535, default: 0
#define TMC6630_SINCOMM_DIRECT_V_MASK                0x0FFC00 // SINCOMM_DIRECT_U_V_W //
#define TMC6630_SINCOMM_DIRECT_V_SHIFT               10 // min.: 0, max.: 65535, default: 0
#define TMC6630_SINCOMM_DIRECT_U_MASK                0x3FF00000 // SINCOMM_DIRECT_U_V_W //
#define TMC6630_SINCOMM_DIRECT_U_SHIFT               20 // min.: 0, max.: 65535, default: 0
#define TMC6630_USE_HALL_DUR_TARGET_MASK             0x01 // CROSSING_OPTS //
#define TMC6630_USE_HALL_DUR_TARGET_SHIFT            0 // min.: 0, max.: 1, default: 0
#define TMC6630_CNT_ONLY_FLOAT_MASK                  0x02 // CROSSING_OPTS //
#define TMC6630_CNT_ONLY_FLOAT_SHIFT                 1 // min.: 0, max.: 1, default: 0
#define TMC6630_DIR_PROTECT_MASK                     0x04 // CROSSING_OPTS //
#define TMC6630_DIR_PROTECT_SHIFT                    2 // min.: 0, max.: 1, default: 0
#define TMC6630_USE_EXT_COMP_COMMU0_EVAL_MASK        0x30 // CROSSING_OPTS //
#define TMC6630_USE_EXT_COMP_COMMU0_EVAL_SHIFT       4 // min.: 0, max.: 3, default: 0
#define TMC6630_USE_EXT_COMP_COMMU1_EVAL_MASK        0xC0 // CROSSING_OPTS //
#define TMC6630_USE_EXT_COMP_COMMU1_EVAL_SHIFT       6 // min.: 0, max.: 3, default: 0
#define TMC6630_STALL_PREVENT_EN_MASK                0x0100 // CROSSING_OPTS //
#define TMC6630_STALL_PREVENT_EN_SHIFT               8 // min.: 0, max.: 1, default: 0
#define TMC6630_STALL_CNT_ONLY_FLOAT_MASK            0x0200 // CROSSING_OPTS //
#define TMC6630_STALL_CNT_ONLY_FLOAT_SHIFT           9 // min.: 0, max.: 1, default: 0
#define TMC6630_STALL_BLK_LIMIT_MASK                 0x0C00 // CROSSING_OPTS //
#define TMC6630_STALL_BLK_LIMIT_SHIFT                10 // min.: 0, max.: 3, default: 0
#define TMC6630_HALL_DURATION_FILT_LENGTH_MASK       0xFF0000 // CROSSING_OPTS //
#define TMC6630_HALL_DURATION_FILT_LENGTH_SHIFT      16 // min.: 0, max.: 255, default: 0
#define TMC6630_HALL_DUR_EXT_MASK                    0xFFFFFF // HALL_DUR_EXT //
#define TMC6630_HALL_DUR_EXT_SHIFT                   0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_CROSSING_CNTS_MIN_MASK               0xFFFFFF // CROSSING_CNTS_MIN //
#define TMC6630_CROSSING_CNTS_MIN_SHIFT              0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_CROSSING_CNTS_MAX_MASK               0xFFFFFF // CROSSING_CNTS_MAX //
#define TMC6630_CROSSING_CNTS_MAX_SHIFT              0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_CROSSING_VALUE_MASK                  0xFFFF // HALL_NEXT_HALL_ACTUAL_CROSSING //
#define TMC6630_CROSSING_VALUE_SHIFT                 0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_HALL_ACTUAL_MASK                     0xFF0000 // HALL_NEXT_HALL_ACTUAL_CROSSING //
#define TMC6630_HALL_ACTUAL_SHIFT                    16 // min.: 0, max.: 255, default: 0
#define TMC6630_HALL_NEXT_MASK                       0xFF000000 // HALL_NEXT_HALL_ACTUAL_CROSSING //
#define TMC6630_HALL_NEXT_SHIFT                      24 // min.: 0, max.: 255, default: 0
#define TMC6630_CROSSING_FILT_MASK                   0xFFFFFF // CROSSING_FILT //
#define TMC6630_CROSSING_FILT_SHIFT                  0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_CROSSING_COUNT_MASK                  0xFFFFFF // CROSSING_SIGNAL_COUNT //
#define TMC6630_CROSSING_COUNT_SHIFT                 0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_CROSSING_SIGNAL_MASK                 0xFF000000 // CROSSING_SIGNAL_COUNT //
#define TMC6630_CROSSING_SIGNAL_SHIFT                24 // min.: 0, max.: 255, default: 0
#define TMC6630_HALL_DUR_I_MASK                      0xFFFF // HALL_DUR_P_I //
#define TMC6630_HALL_DUR_I_SHIFT                     0 // min.: 0, max.: 65535, default: 0
#define TMC6630_HALL_DUR_P_MASK                      0xFFFF0000 // HALL_DUR_P_I //
#define TMC6630_HALL_DUR_P_SHIFT                     16 // min.: 0, max.: 65535, default: 0
#define TMC6630_HALL_DURATION_MASK                   0xFFFFFF // HALL_DURATION //
#define TMC6630_HALL_DURATION_SHIFT                  0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_HALL_DURATION_PI_MASK                0xFFFFFF // HALL_DURATION_PI //
#define TMC6630_HALL_DURATION_PI_SHIFT               0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_HALL_DURATION_FLT_MASK               0xFFFFFF // HALL_DURATION_FLT //
#define TMC6630_HALL_DURATION_FLT_SHIFT              0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_USE_TORQUE_LIMIT_DDT_MASK            0x01 // VELOCITY_PID_OPTS //
#define TMC6630_USE_TORQUE_LIMIT_DDT_SHIFT           0 // min.: 0, max.: 1, default: 0
#define TMC6630_USE_VELOCITY_LIMIT_DDT_MASK          0x02 // VELOCITY_PID_OPTS //
#define TMC6630_USE_VELOCITY_LIMIT_DDT_SHIFT         1 // min.: 0, max.: 1, default: 0
#define TMC6630_TORQUE_TRIGGER_CNT_MASK              0xFF00 // VELOCITY_PID_OPTS //
#define TMC6630_TORQUE_TRIGGER_CNT_SHIFT             8 // min.: 0, max.: 255, default: 0
#define TMC6630_VELOCITY_TRIGGER_CNT_MASK            0xFF0000 // VELOCITY_PID_OPTS //
#define TMC6630_VELOCITY_TRIGGER_CNT_SHIFT           16 // min.: 0, max.: 255, default: 0
#define TMC6630_VELOCITY_FILT_LENGTH_MASK            0xFF000000 // VELOCITY_PID_OPTS //
#define TMC6630_VELOCITY_FILT_LENGTH_SHIFT           24 // min.: 0, max.: 255, default: 0
#define TMC6630_TORQUE_I_MASK                        0xFFFF // TORQUE_P_I //
#define TMC6630_TORQUE_I_SHIFT                       0 // min.: 0, max.: 32767, default: 0
#define TMC6630_TORQUE_P_MASK                        0xFFFF0000 // TORQUE_P_I //
#define TMC6630_TORQUE_P_SHIFT                       16 // min.: 0, max.: 32767, default: 0
#define TMC6630_TORQUE_MIN_MASK                      0xFFFF // TORQUE_MAX_MIN //
#define TMC6630_TORQUE_MIN_SHIFT                     0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_TORQUE_MAX_MASK                      0xFFFF0000 // TORQUE_MAX_MIN //
#define TMC6630_TORQUE_MAX_SHIFT                     16 // min.: -32768, max.: 32767, default: 0
#define TMC6630_TORQUE_LIMIT_DDT_MASK                0xFFFF // TORQUE_TARGET_LIMIT_DDT //
#define TMC6630_TORQUE_LIMIT_DDT_SHIFT               0 // min.: 0, max.: 32767, default: 0
#define TMC6630_TORQUE_TARGET_MASK                   0xFFFF0000 // TORQUE_TARGET_LIMIT_DDT //
#define TMC6630_TORQUE_TARGET_SHIFT                  16 // min.: -32768, max.: 32767, default: 0
#define TMC6630_TORQUE_PWM_VALUE_MASK                0xFFFF // TORQUE_ERROR_PWM_VALUE //
#define TMC6630_TORQUE_PWM_VALUE_SHIFT               0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_TORQUE_ERROR_MASK                    0xFFFF0000 // TORQUE_ERROR_PWM_VALUE //
#define TMC6630_TORQUE_ERROR_SHIFT                   16 // min.: -32768, max.: 32767, default: 0
#define TMC6630_TORQUE_ERROR_SUM_MASK                0xFFFFFFFF // TORQUE_ERROR_SUM //
#define TMC6630_TORQUE_ERROR_SUM_SHIFT               0 // min.: -2147483648, max.: 2147483647, default: 0
#define TMC6630_VELOCITY_I_MASK                      0xFFFF // VELOCITY_P_I //
#define TMC6630_VELOCITY_I_SHIFT                     0 // min.: 0, max.: 32767, default: 0
#define TMC6630_VELOCITY_P_MASK                      0xFFFF0000 // VELOCITY_P_I //
#define TMC6630_VELOCITY_P_SHIFT                     16 // min.: 0, max.: 32767, default: 0
#define TMC6630_VELOCITY_MAX_MASK                    0xFFFFFF // VELOCITY_MAX //
#define TMC6630_VELOCITY_MAX_SHIFT                   0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_VELOCITY_MIN_MASK                    0xFFFFFF // VELOCITY_MIN //
#define TMC6630_VELOCITY_MIN_SHIFT                   0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_VELOCITY_LIMIT_DDT_MASK              0xFFFFFF // VELOCITY_LIMIT_DDT //
#define TMC6630_VELOCITY_LIMIT_DDT_SHIFT             0 // min.: 0, max.: 16777215, default: 0
#define TMC6630_VELOCITY_TARGET_MASK                 0xFFFFFF // VELOCITY_TARGET //
#define TMC6630_VELOCITY_TARGET_SHIFT                0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_VELOCITY_ACTUAL_MASK                 0xFFFFFF // VELOCITY_ACTUAL //
#define TMC6630_VELOCITY_ACTUAL_SHIFT                0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_VELOCITY_ERROR_MASK                  0xFFFFFF // VELOCITY_ERROR //
#define TMC6630_VELOCITY_ERROR_SHIFT                 0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_VELOCITY_ERROR_SUM_MASK              0xFFFFFFFF // VELOCITY_ERROR_SUM //
#define TMC6630_VELOCITY_ERROR_SUM_SHIFT             0 // min.: -2147483648, max.: 2147483647, default: 0
#define TMC6630_VELOCITY_TORQUE_TARGET_MASK          0xFFFFFF // VELOCITY_TORQUE_TARGET //
#define TMC6630_VELOCITY_TORQUE_TARGET_SHIFT         0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_TORQUE_TARGET_LIMIT_DDT_OUT_MASK     0xFFFF // TORQUE_TARGET_LIMIT_DDT_OUT //
#define TMC6630_TORQUE_TARGET_LIMIT_DDT_OUT_SHIFT    0 // min.: -32768, max.: 32767, default: 0
#define TMC6630_VELOCITY_TARGET_LIMIT_DDT_OUT_MASK   0xFFFFFF // VELOCITY_TARGET_LIMIT_DDT_OUT //
#define TMC6630_VELOCITY_TARGET_LIMIT_DDT_OUT_SHIFT  0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_PWM_CNTL_FILTER_LENGTH_MASK          0xFF // PWM_CNTL_FILTER_MAXCNT_LENGTH //
#define TMC6630_PWM_CNTL_FILTER_LENGTH_SHIFT         0 // min.: 0, max.: 255, default: 0
#define TMC6630_PWM_CNTL_FILTER_MAXCNT_MASK          0xFFFFFF00 // PWM_CNTL_FILTER_MAXCNT_LENGTH //
#define TMC6630_PWM_CNTL_FILTER_MAXCNT_SHIFT         8 // min.: 0, max.: 16777215, default: 0
#define TMC6630_PWM_CNTL_MAX_SHORT_CNT_MASK          0x0FFFFF // PWM_CNTL_LIMIT_MAX_SHORT_CNT //
#define TMC6630_PWM_CNTL_MAX_SHORT_CNT_SHIFT         0 // min.: 0, max.: 1048575, default: 0
#define TMC6630_PWM_CNTL_LIMIT_MASK                  0xFFF00000 // PWM_CNTL_LIMIT_MAX_SHORT_CNT //
#define TMC6630_PWM_CNTL_LIMIT_SHIFT                 20 // min.: 0, max.: 4095, default: 0
#define TMC6630_PWM_CNTL_DUTY_MIN_MASK               0xFFFF // PWM_CNTL_DUTY_MAX_MIN //
#define TMC6630_PWM_CNTL_DUTY_MIN_SHIFT              0 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_CNTL_DUTY_MAX_MASK               0xFFFF0000 // PWM_CNTL_DUTY_MAX_MIN //
#define TMC6630_PWM_CNTL_DUTY_MAX_SHIFT              16 // min.: 0, max.: 65535, default: 0
#define TMC6630_PWM_CNTL_DUTY_FILTERED_MASK          0xFFFF0000 // PWM_CNTL_DUTY_FILTERED_CALC //
#define TMC6630_PWM_CNTL_DUTY_FILTERED_SHIFT         16 // min.: 0, max.: 65535, default: 0
#define TMC6630_UART_BPS_MASK                        0xFFFFFFFF // UART_BPS //
#define TMC6630_UART_BPS_SHIFT                       0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_TEST_VECTOR_0_MASK                   0x01 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_0_SHIFT                  0 // min.: 0, max.: 1, default: 0
#define TMC6630_TEST_VECTOR_1_MASK                   0x02 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_1_SHIFT                  1 // min.: 0, max.: 1, default: 0
#define TMC6630_TEST_VECTOR_2_MASK                   0x04 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_2_SHIFT                  2 // min.: 0, max.: 1, default: 0
#define TMC6630_TEST_VECTOR_3_MASK                   0x08 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_3_SHIFT                  3 // min.: 0, max.: 1, default: 0
#define TMC6630_TEST_VECTOR_4_MASK                   0x10 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_4_SHIFT                  4 // min.: 0, max.: 1, default: 0
#define TMC6630_TEST_VECTOR_5_MASK                   0x20 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_5_SHIFT                  5 // min.: 0, max.: 1, default: 0
#define TMC6630_TEST_VECTOR_6_MASK                   0x40 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_6_SHIFT                  6 // min.: 0, max.: 1, default: 0
#define TMC6630_TEST_VECTOR_7_MASK                   0x80 // TEST_VECTOR //
#define TMC6630_TEST_VECTOR_7_SHIFT                  7 // min.: 0, max.: 1, default: 0
#define TMC6630_LOW_MASK                             0x03FF // HIGH_FLOAT_LOW //
#define TMC6630_LOW_SHIFT                            0 // min.: 0, max.: 65535, default: 0
#define TMC6630_FLOAT_MASK                           0x0FFC00 // HIGH_FLOAT_LOW //
#define TMC6630_FLOAT_SHIFT                          10 // min.: 0, max.: 65535, default: 0
#define TMC6630_HIGH_MASK                            0x3FF00000 // HIGH_FLOAT_LOW //
#define TMC6630_HIGH_SHIFT                           20 // min.: 0, max.: 65535, default: 0
#define TMC6630_INTEGRAL_ACTUAL_MASK                 0xFFFFFF // INTEGRAL_ACTUAL //
#define TMC6630_INTEGRAL_ACTUAL_SHIFT                0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_INTEGRAL_LAST_MASK                   0xFFFFFF // INTEGRAL_LAST //
#define TMC6630_INTEGRAL_LAST_SHIFT                  0 // min.: -8388608, max.: 8388607, default: 0
#define TMC6630_CNT01_INTEGRAL_LAST_MASK             0xFFFFFFFF // CNT01_INTEGRAL_LAST //
#define TMC6630_CNT01_INTEGRAL_LAST_SHIFT            0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_CNT01_INTEGRAL_MASK                  0xFFFFFFFF // CNT01_INTEGRAL //
#define TMC6630_CNT01_INTEGRAL_SHIFT                 0 // min.: 0, max.: 4294967295, default: 0
#define TMC6630_ORDER_MASK                           0xFFFFFF // ORDER //
#define TMC6630_ORDER_SHIFT                          0 // min.: 0, max.: 5461060, default: 0

#endif /* TMC6630_FIELDS_H */
