/*
 *  TMC8690_Mask_Shift.h
 *  Author: LK
 *  Generated by MaskShiftConverter (unchecked)
 */

#ifndef TMC8690_MASK_SHIFT_H
#define TMC8690_MASK_SHIFT_H

	// CHIPINFO_DATA
	#define TMC8690_SI_TYPE_MASK                      0xFFFFFFFF  //
	#define TMC8690_SI_TYPE_SHIFT                     0           // min.: 0, max.: 4294967295, default: 0
	// CHIPINFO_DATA
	#define TMC8690_SI_VERSION_MASK                   0xFFFFFFFF  //
	#define TMC8690_SI_VERSION_SHIFT                  0           // min.: 0, max.: 4294967295, default: 0
	// CHIPINFO_DATA
	#define TMC8690_SI_DATE_MASK                      0xFFFFFFFF  //
	#define TMC8690_SI_DATE_SHIFT                     0           // min.: 0, max.: 4294967295, default: 0
	// CHIPINFO_DATA
	#define TMC8690_SI_TIME_MASK                      0xFFFFFFFF  //
	#define TMC8690_SI_TIME_SHIFT                     0           // min.: 0, max.: 16777215, default: 0
	// CHIPINFO_DATA
	#define TMC8690_CHIPINFO_DATA_MASK                0x0000FFFF
	#define TMC8690_CHIPINFO_DATA_SHIFT               0
	// CHIPINFO_ADDR
	#define TMC8690_CHIP_INFO_ADDRESS_MASK            0x000000FF  //
	#define TMC8690_CHIP_INFO_ADDRESS_SHIFT           0           // min.: 0, max.: 3, default: 0
	// CHIPINFO_ADDR
	#define TMC8690_CHIPINFO_ADDR_MASK                0x0000FFFF
	#define TMC8690_CHIPINFO_ADDR_SHIFT               0
	// STATUS_WORD
	#define TMC8690_STATUS_WORD_MASK                  0xFFFFFFFF  // description of STATUS_WORD
	#define TMC8690_STATUS_WORD_SHIFT                 0           // min.: 0, max.: 4294967295, default: 0
	// COMMAND_WORD
	#define TMC8690_COMMAND_WORD_MASK                 0xFFFFFFFF  // description of COMMAND_WORD
	#define TMC8690_COMMAND_WORD_SHIFT                0           // min.: 0, max.: 4294967295, default: 0
	// P_FAK_BRAKE
	#define TMC8690_P_FAK_BRAKE_MASK                  0x0000FFFF  // description of P_FAK_BRAKE
	#define TMC8690_P_FAK_BRAKE_SHIFT                 0           // min.: -32768, max.: 32767, default: 0
	// I_FAK_BRAKE
	#define TMC8690_I_FAK_BRAKE_MASK                  0x0000FFFF  // description of I_FAK_BRAKE
	#define TMC8690_I_FAK_BRAKE_SHIFT                 0           // min.: -32768, max.: 32767, default: 0
	// P_FAK_HEAT
	#define TMC8690_P_FAK_HEAT_MASK                   0x0000FFFF  // description of P_FAK_HEAT
	#define TMC8690_P_FAK_HEAT_SHIFT                  0           // min.: -32768, max.: 32767, default: 0
	// I_FAK_HEAT
	#define TMC8690_I_FAK_HEAT_MASK                   0x0000FFFF  // description of I_FAK_HEAT
	#define TMC8690_I_FAK_HEAT_SHIFT                  0           // min.: -32768, max.: 32767, default: 0
	// P_FAK_VEL
	#define TMC8690_P_FAK_VEL_MASK                    0x0000FFFF  // description of P_FAK_VEL
	#define TMC8690_P_FAK_VEL_SHIFT                   0           // min.: -32768, max.: 32767, default: 0
	// I_FAK_VEL
	#define TMC8690_I_FAK_VEL_MASK                    0x0000FFFF  // description of I_FAK_VEL
	#define TMC8690_I_FAK_VEL_SHIFT                   0           // min.: -32768, max.: 32767, default: 0
	// P_FAK_POS
	#define TMC8690_P_FAK_POS_MASK                    0x0000FFFF  // description of P_FAK_POS
	#define TMC8690_P_FAK_POS_SHIFT                   0           // min.: -32768, max.: 32767, default: 0
	// ENC_Z_COMP_VAL
	#define TMC8690_ENC_Z_COMP_VAL_MASK               0x0000FFFF  // description of ENC_Z_COMP_VAL
	#define TMC8690_ENC_Z_COMP_VAL_SHIFT              0           // min.: -32768, max.: 32767, default: 0
	// TORQUE_TARGET
	#define TMC8690_TORQUE_TARGET_MASK                0x0000FFFF  // description of TORQUE_TARGET
	#define TMC8690_TORQUE_TARGET_SHIFT               0           // min.: -32768, max.: 32767, default: 0
	// VELOCITY_TARGET
	#define TMC8690_VELOCITY_TARGET_MASK              0xFFFFFFFF  // description of VELOCITY_TARGET
	#define TMC8690_VELOCITY_TARGET_SHIFT             0           // min.: -2147483648, max.: 2147483647, default: 0
	// POSITION_TARGET
	#define TMC8690_POSITION_TARGET_MASK              0xFFFFFFFF  // description of POSITION_TARGET
	#define TMC8690_POSITION_TARGET_SHIFT             0           // min.: -2147483648, max.: 2147483647, default: 0
	// TEMPERATURE_TARGET
	#define TMC8690_TEMPERATURE_TARGET_MASK           0x0000FFFF  // description of TEMPERATURE_TARGET
	#define TMC8690_TEMPERATURE_TARGET_SHIFT          0           // min.: 0, max.: 65535, default: 0
	// OSCI_MAIN_CONFIG_REG
	#define TMC8690_OSCI_MAIN_CONFIG_REG_MASK         0xFFFFFFFF  // description of OSCI_MAIN_CONFIG_REG
	#define TMC8690_OSCI_MAIN_CONFIG_REG_SHIFT        0           // min.: 0, max.: 4294967295, default: 0
	// OSCI_PRETRIGGER_CONFIG_REG
	#define TMC8690_OSCI_PRETRIGGER_CONFIG_REG_MASK   0x0000FFFF  // description of OSCI_PRETRIGGER_CONFIG_REG
	#define TMC8690_OSCI_PRETRIGGER_CONFIG_REG_SHIFT  0           // min.: 0, max.: 65535, default: 0
	// OSCI_DATA_ADDRESS
	#define TMC8690_OSCI_DATA_ADDRESS_MASK            0x0000FFFF  // description of OSCI_DATA_ADDRESS
	#define TMC8690_OSCI_DATA_ADDRESS_SHIFT           0           // min.: 0, max.: 65535, default: 0
	// OSCI_STATUS
	#define TMC8690_OSCI_STATUS_MASK                  0x0000FFFF  // description of OSCI_STATUS
	#define TMC8690_OSCI_STATUS_SHIFT                 0           // min.: -32768, max.: 32767, default: 0
	// OSCI_OUTPUT_DATA
	#define TMC8690_OSCI_OUTPUT_DATA_MASK             0x0000FFFF  // description of OSCI_OUTPUT_DATA
	#define TMC8690_OSCI_OUTPUT_DATA_SHIFT            0           // min.: -32768, max.: 32767, default: 0
	// ADC_ENC_TRACK_A
	#define TMC8690_ADC_ENC_TRACK_A_MASK              0x0000FFFF  // description of ADC_ENC_TRACK_A
	#define TMC8690_ADC_ENC_TRACK_A_SHIFT             0           // min.: -32768, max.: 32767, default: 0
	// ADC_ENC_TRACK_B
	#define TMC8690_ADC_ENC_TRACK_B_MASK              0x0000FFFF  // description of ADC_ENC_TRACK_B
	#define TMC8690_ADC_ENC_TRACK_B_SHIFT             0           // min.: -32768, max.: 32767, default: 0
	// ADC_ENC_TRACK_Z
	#define TMC8690_ADC_ENC_TRACK_Z_MASK              0x0000FFFF  // description of ADC_ENC_TRACK_Z
	#define TMC8690_ADC_ENC_TRACK_Z_SHIFT             0           // min.: 0, max.: 65535, default: 0
	// ADC_I_U
	#define TMC8690_ADC_I_U_MASK                      0x0000FFFF  // description of ADC_I_U
	#define TMC8690_ADC_I_U_SHIFT                     0           // min.: 0, max.: 65535, default: 0
	// ADC_I_V
	#define TMC8690_ADC_I_V_MASK                      0x0000FFFF  // description of ADC_I_V
	#define TMC8690_ADC_I_V_SHIFT                     0           // min.: 0, max.: 65535, default: 0
	// ADC_I_W
	#define TMC8690_ADC_I_W_MASK                      0x0000FFFF  // description of ADC_I_W
	#define TMC8690_ADC_I_W_SHIFT                     0           // min.: 0, max.: 65535, default: 0
	// ADC_I_SUPPLY
	#define TMC8690_ADC_I_SUPPLY_MASK                 0x0000FFFF  // description of ADC_I_SUPPLY
	#define TMC8690_ADC_I_SUPPLY_SHIFT                0           // min.: 0, max.: 65535, default: 0
	// ADC_I_SUPPLY_FILT
	#define TMC8690_ADC_I_SUPPLY_FILT_MASK            0x0000FFFF  // description of ADC_I_SUPPLY_FILT
	#define TMC8690_ADC_I_SUPPLY_FILT_SHIFT           0           // min.: 0, max.: 65535, default: 0
	// ADC_TORQUE
	#define TMC8690_ADC_TORQUE_MASK                   0x0000FFFF  // description of ADC_TORQUE
	#define TMC8690_ADC_TORQUE_SHIFT                  0           // min.: 0, max.: 65535, default: 0
	// ADC_TEMP
	#define TMC8690_ADC_TEMP_MASK                     0x0000FFFF  // description of ADC_TEMP
	#define TMC8690_ADC_TEMP_SHIFT                    0           // min.: 0, max.: 65535, default: 0
	// ADC_MICROPHONE
	#define TMC8690_ADC_MICROPHONE_MASK               0x0000FFFF  // description of ADC_MICROPHONE
	#define TMC8690_ADC_MICROPHONE_SHIFT              0           // min.: 0, max.: 65535, default: 0
	// ADC_I_BRAKE
	#define TMC8690_ADC_I_BRAKE_MASK                  0x0000FFFF  // description of ADC_I_BRAKE
	#define TMC8690_ADC_I_BRAKE_SHIFT                 0           // min.: 0, max.: 65535, default: 0
	// TRACK_A_OFFSET
	#define TMC8690_TRACK_A_OFFSET_MASK               0x0000FFFF  // description of TRACK_A_OFFSET
	#define TMC8690_TRACK_A_OFFSET_SHIFT              0           // min.: 0, max.: 65535, default: 0
	// TRACK_B_OFFSET
	#define TMC8690_TRACK_B_OFFSET_MASK               0x0000FFFF  // description of TRACK_B_OFFSET
	#define TMC8690_TRACK_B_OFFSET_SHIFT              0           // min.: 0, max.: 65535, default: 0
	// DAC_V_REF
	#define TMC8690_DAC_V_REF_MASK                    0x0000FFFF  // description of DAC_V_REF
	#define TMC8690_DAC_V_REF_SHIFT                   0           // min.: 0, max.: 65535, default: 0
	// T_PT1_FILTER_VEL
	#define TMC8690_T_PT1_FILTER_VEL_MASK             0x0000FFFF  // description of T_PT1_FILTER_VEL
	#define TMC8690_T_PT1_FILTER_VEL_SHIFT            0           // min.: 0, max.: 65535, default: 0
	// T_PT1_FILTER_I_SUPPLY
	#define TMC8690_T_PT1_FILTER_I_SUPPLY_MASK        0x0000FFFF  // description of T_PT1_FILTER_I_SUPPLY
	#define TMC8690_T_PT1_FILTER_I_SUPPLY_SHIFT       0           // min.: 0, max.: 65535, default: 0
	// DAC_BRAKE
	#define TMC8690_DAC_BRAKE_MASK                    0xFFFFFFFF  // description of DAC_BRAKE
	#define TMC8690_DAC_BRAKE_SHIFT                   0           // min.: -2147483648, max.: 2147483647, default: 0
	// DAC_BRAKE_TARGET
	#define TMC8690_DAC_BRAKE_TARGET_MASK             0xFFFFFFFF  // description of DAC_BRAKE_TARGET
	#define TMC8690_DAC_BRAKE_TARGET_SHIFT            0           // min.: -2147483648, max.: 2147483647, default: 0
	// VELOCITY_ACTUAL
	#define TMC8690_VELOCITY_ACTUAL_MASK              0xFFFFFFFF  // description of VELOCITY_ACTUAL
	#define TMC8690_VELOCITY_ACTUAL_SHIFT             0           // min.: -2147483648, max.: 2147483647, default: 0
	// VELOCITY_IN_RPM_ACTUAL
	#define TMC8690_VELOCITY_IN_RPM_ACTUAL_MASK       0xFFFFFFFF  // description of VELOCITY_IN_RPM_ACTUAL
	#define TMC8690_VELOCITY_IN_RPM_ACTUAL_SHIFT      0           // min.: -2147483648, max.: 2147483647, default: 0
	// VELOCITY_IN_RPM_ACTUAL_PT1
	#define TMC8690_VELOCITY_IN_RPM_ACTUAL_PT1_MASK   0xFFFFFFFF  // description of VELOCITY_IN_RPM_ACTUAL_PT1
	#define TMC8690_VELOCITY_IN_RPM_ACTUAL_PT1_SHIFT  0           // min.: -2147483648, max.: 2147483647, default: 0
	// VELOCITY_IN_RPM_ACTUAL_MAV
	#define TMC8690_VELOCITY_IN_RPM_ACTUAL_MAV_MASK   0xFFFFFFFF  // description of VELOCITY_IN_RPM_ACTUAL_MAV
	#define TMC8690_VELOCITY_IN_RPM_ACTUAL_MAV_SHIFT  0           // min.: -2147483648, max.: 2147483647, default: 0
	// POSITION_ACTUAL
	#define TMC8690_POSITION_ACTUAL_MASK              0xFFFFFFFF  // description of POSITION_ACTUAL
	#define TMC8690_POSITION_ACTUAL_SHIFT             0           // min.: -2147483648, max.: 2147483647, default: 0
	// VEL_CTRL_TORQUE_TARGET
	#define TMC8690_VEL_CTRL_TORQUE_TARGET_MASK       0x0000FFFF  // description of VEL_CTRL_TORQUE_TARGET
	#define TMC8690_VEL_CTRL_TORQUE_TARGET_SHIFT      0           // min.: 0, max.: 65535, default: 0
	// POS_CTRL_VEL_TARGET
	#define TMC8690_POS_CTRL_VEL_TARGET_MASK          0x0000FFFF  // description of POS_CTRL_VEL_TARGET
	#define TMC8690_POS_CTRL_VEL_TARGET_SHIFT         0           // min.: 0, max.: 65535, default: 0
	// PWM_HEATER
	#define TMC8690_PWM_HEATER_MASK                   0x0000FFFF  // description of PWM_HEATER
	#define TMC8690_PWM_HEATER_SHIFT                  0           // min.: 0, max.: 65535, default: 0
	// U_BRAKE
	#define TMC8690_U_BRAKE_MASK                      0x0000FFFF  // description of U_BRAKE
	#define TMC8690_U_BRAKE_SHIFT                     0           // min.: 0, max.: 65535, default: 0
	// DEBUG_AXIS_PARAM_0
	#define TMC8690_DEBUG_AXIS_PARAM_0_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_0
	#define TMC8690_DEBUG_AXIS_PARAM_0_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// DEBUG_AXIS_PARAM_1
	#define TMC8690_DEBUG_AXIS_PARAM_1_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_1
	#define TMC8690_DEBUG_AXIS_PARAM_1_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// DEBUG_AXIS_PARAM_2
	#define TMC8690_DEBUG_AXIS_PARAM_2_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_2
	#define TMC8690_DEBUG_AXIS_PARAM_2_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// DEBUG_AXIS_PARAM_3
	#define TMC8690_DEBUG_AXIS_PARAM_3_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_3
	#define TMC8690_DEBUG_AXIS_PARAM_3_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// DEBUG_AXIS_PARAM_4
	#define TMC8690_DEBUG_AXIS_PARAM_4_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_4
	#define TMC8690_DEBUG_AXIS_PARAM_4_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// DEBUG_AXIS_PARAM_5
	#define TMC8690_DEBUG_AXIS_PARAM_5_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_5
	#define TMC8690_DEBUG_AXIS_PARAM_5_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// DEBUG_AXIS_PARAM_6
	#define TMC8690_DEBUG_AXIS_PARAM_6_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_6
	#define TMC8690_DEBUG_AXIS_PARAM_6_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// DEBUG_AXIS_PARAM_7
	#define TMC8690_DEBUG_AXIS_PARAM_7_MASK           0xFFFFFFFF  // description of DEBUG_AXIS_PARAM_7
	#define TMC8690_DEBUG_AXIS_PARAM_7_SHIFT          0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_0
	#define TMC8690_STATE_VAR_PARAM_0_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_0
	#define TMC8690_STATE_VAR_PARAM_0_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_1
	#define TMC8690_STATE_VAR_PARAM_1_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_1
	#define TMC8690_STATE_VAR_PARAM_1_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_2
	#define TMC8690_STATE_VAR_PARAM_2_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_2
	#define TMC8690_STATE_VAR_PARAM_2_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_3
	#define TMC8690_STATE_VAR_PARAM_3_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_3
	#define TMC8690_STATE_VAR_PARAM_3_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_4
	#define TMC8690_STATE_VAR_PARAM_4_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_4
	#define TMC8690_STATE_VAR_PARAM_4_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_5
	#define TMC8690_STATE_VAR_PARAM_5_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_5
	#define TMC8690_STATE_VAR_PARAM_5_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_6
	#define TMC8690_STATE_VAR_PARAM_6_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_6
	#define TMC8690_STATE_VAR_PARAM_6_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// STATE_VAR_PARAM_7
	#define TMC8690_STATE_VAR_PARAM_7_MASK            0xFFFFFFFF  // description of STATE_VAR_PARAM_7
	#define TMC8690_STATE_VAR_PARAM_7_SHIFT           0           // min.: 0, max.: 4294967295, default: 0
	// SAMP_INPUTS_RAW
	#define TMC8690_SAMP_INPUTS_RAW_MASK              0xFFFFFFFF  // description of SAMP_INPUTS_RAW
	#define TMC8690_SAMP_INPUTS_RAW_SHIFT             0           // min.: 0, max.: 4294967295, default: 0
	// SAMP_OUTPUTS_RAW
	#define TMC8690_SAMP_OUTPUTS_RAW_MASK             0xFFFFFFFF  // description of SAMP_OUTPUTS_RAW
	#define TMC8690_SAMP_OUTPUTS_RAW_SHIFT            0           // min.: 0, max.: 4294967295, default: 0
	// STATUS_FLAGS
	#define TMC8690_STATUS_FLAGS_MASK                 0xFFFFFFFF  // description of STATUS_FLAGS
	#define TMC8690_STATUS_FLAGS_SHIFT                0           // min.: 0, max.: 4294967295, default: 0
	// WARNING_MASK
	#define TMC8690_WARNING_MASK_MASK                 0xFFFFFFFF  // description of WARNING_MASK
	#define TMC8690_WARNING_MASK_SHIFT                0           // min.: 0, max.: 4294967295, default: 0
	// ERROR_MASK
	#define TMC8690_ERROR_MASK_MASK                   0xFFFFFFFF  // description of ERROR_MASK
	#define TMC8690_ERROR_MASK_SHIFT                  0           // min.: 0, max.: 4294967295, default: 0
	// Trigger channel
	#define TMC8690_TRG_CHN_MASK                      0x070000
	#define TMC8690_TRG_CHN_SHIFT                     16
	// Trigger condition
	#define TMC8690_TRG_CND_MASK                      0xF80000
	#define TMC8690_TRG_CND_SHIFT                     19
	// Trigger value
	#define TMC8690_TRG_VAL_MASK                      0x0000FFFF
	#define TMC8690_TRG_VAL_SHIFT                     0
	// Oversampling ratio
	#define TMC8690_OSR_MASK                          0x07000000
	#define TMC8690_OSR_SHIFT                         24
	// Data sampling rate
	#define TMC8690_DSR_MASK                          0x38000000
	#define TMC8690_DSR_SHIFT                         27
	// Enable/disable measurement
	#define TMC8690_MEAS_EN_MASK                      0x40000000
	#define TMC8690_MEAS_EN_SHIFT                     30
	// Clear measurement
	#define TMC8690_MEAS_CLR_MASK                     0x80000000
	#define TMC8690_MEAS_CLR_SHIFT                    31

#endif /* TMC8690_MASK_SHIFT_H */
