/*******************************************************************************
* Copyright © 2019 TRINAMIC Motion Control GmbH & Co. KG
* (now owned by Analog Devices Inc.),
*
* Copyright © 2023 Analog Devices Inc. All Rights Reserved. This software is
* proprietary & confidential to Analog Devices, Inc. and its licensors.
*******************************************************************************/


// Autogenerated C header for registers in TMC5271
// Generator version: 1.0

#ifndef TMC5271_REGISTERS
#define TMC5271_REGISTERS

#define TMC5271_GCONF             0x00
#define TMC5271_GSTAT             0x01
#define TMC5271_IFCNT             0x02
#define TMC5271_SLAVECONF         0x03
#define TMC5271_IOIN              0x04
#define TMC5271_DRV_CONF          0x05
#define TMC5271_GLOBAL_SCALER     0x06
#define TMC5271_RAMPMODE          0x07
#define TMC5271_MSLUT_ADDR        0x08
#define TMC5271_MSLUT_DATA        0x09
#define TMC5271_X_COMPARE         0x10
#define TMC5271_X_COMPARE_REPEAT  0x11
#define TMC5271_IHOLD_IRUN        0x12
#define TMC5271_TPOWERDOWN        0x13
#define TMC5271_TSTEP             0x14
#define TMC5271_TPWMTHRS          0x15
#define TMC5271_TCOOLTHRS         0x16
#define TMC5271_THIGH             0x17
#define TMC5271_XACTUAL           0x18
#define TMC5271_VACTUAL           0x19
#define TMC5271_AACTUAL           0x1A
#define TMC5271_VSTART            0x1B
#define TMC5271_A1                0x1C
#define TMC5271_V1                0x1D
#define TMC5271_A2                0x1E
#define TMC5271_V2                0x1F
#define TMC5271_AMAX              0x20
#define TMC5271_VMAX              0x21
#define TMC5271_DMAX              0x22
#define TMC5271_D2                0x23
#define TMC5271_D1                0x24
#define TMC5271_VSTOP             0x25
#define TMC5271_TVMAX             0x26
#define TMC5271_TZEROWAIT         0x27
#define TMC5271_XTARGET           0x28
#define TMC5271_VDCMIN            0x29
#define TMC5271_SW_MODE           0x2A
#define TMC5271_RAMP_STAT         0x2B
#define TMC5271_XLATCH            0x2C
#define TMC5271_POSITION_PI_CTRL  0x2D
#define TMC5271_X_ENC             0x2E
#define TMC5271_ENCMODE           0x2F
#define TMC5271_ENC_CONST         0x30
#define TMC5271_ENC_STATUS        0x31
#define TMC5271_ENC_LATCH         0x32
#define TMC5271_ENC_DEVIATION     0x33
#define TMC5271_VIRTUAL_STOP_L    0x34
#define TMC5271_VIRTUAL_STOP_R    0x35
#define TMC5271_MSCNT             0x36
#define TMC5271_MSCURACT          0x37
#define TMC5271_CHOPCONF          0x38
#define TMC5271_COOLCONF          0x39
#define TMC5271_DCCTRL            0x3A
#define TMC5271_DRV_STATUS        0x3B
#define TMC5271_PWMCONF           0x3C
#define TMC5271_PWM_SCALE         0x3D
#define TMC5271_PWM_AUTO          0x3E
#define TMC5271_SG4_THRS          0x3F
#define TMC5271_SG4_RESULT        0x40
#define TMC5271_SG4_IND           0x41

#endif
